const CSAndroid_TO_ADD = [

    "_global/__Light/Notification Dot",
    "_global/_Dark/Notification Dot",
    "_global/__Light/Progress bar/00%",
    "_global/_Dark/Progress bar/00%",
    "_global/__Light/Progress bar/10%",
    "_global/_Dark/Progress bar/10%",
    "_global/__Light/Progress bar/20%",
    "_global/_Dark/Progress bar/20%",
    "_global/__Light/Progress bar/25%",
    "_global/_Dark/Progress bar/25%",
    "_global/__Light/Progress bar/40%",
    "_global/_Dark/Progress bar/40%",
    "_global/__Light/Progress bar/50%",
    "_global/_Dark/Progress bar/50%",
    "_global/__Light/Progress bar/60%",
    "_global/_Dark/Progress bar/60%",
    "_global/__Light/Progress bar/75%",
    "_global/_Dark/Progress bar/75%",
    "_global/__Light/Progress bar/80%",
    "_global/_Dark/Progress bar/80%",
    "_global/__Light/Progress bar/90%",
    "_global/_Dark/Progress bar/90%",
    "_global/__Light/Progress bar/100%",
    "_global/_Dark/Progress bar/100%",

    "_global/Ω _overrides/Rating/__Light/Rating #",
    "_global/Ω _overrides/Rating/_Dark/Rating #",

    "_global/__Light/Alert",
    "_global/_Dark/Alert",
    "_global/Ω _overrides/__Light/Alert/Title",
    "_global/Ω _overrides/_Dark/Alert/Title",
    "_global/Ω _overrides/__Light/Alert/Description",
    "_global/Ω _overrides/_Dark/Alert/Description",
    "_global/Ω _overrides/__Light/Alert/CTAs",
    "_global/Ω _overrides/_Dark/Alert/CTAs",
    "Button/Ω _overrides/Loader/White",
    "Button/Ω _overrides/Loader/Midnight",
    "Button/Ω _overrides/Loader/Chill",
    "Button/Ω _overrides/Ripple/On Light",
    "Button/Ω _overrides/Shadow/__Light",
    "Button/Ω _overrides/Shadow/_Dark",
    "Button/Ω _overrides/Ripple/On Dark",
    "SegmentedControl/_Light/2 Buttons",
    "SegmentedControl/Dark/2 Buttons",
    "SegmentedControl/_Light/3 Buttons",
    "SegmentedControl/Dark/3 Buttons",
    "SegmentedControl/_Light/4 Buttons",
    "SegmentedControl/Dark/4 Buttons",
    "SegmentedControl/Ω _overrides/Option/_Light/Active",
    "SegmentedControl/Ω _overrides/Option/Dark/Active",
    "SegmentedControl/Ω _overrides/Option/_Light/Default",
    "SegmentedControl/Ω _overrides/Option/Dark/Default",
    "SegmentedControl/Ω _overrides/Core/_Light",
    "SegmentedControl/Ω _overrides/Core/Dark",




    "Cards/__Light/Icon + Title + Progress",
    "Cards/_Dark/Icon + Title + Progress",
    "Cards/__Light/Image + Title",
    "Cards/_Dark/Image + Title",
    "Cards/__Light/Icon + Description",
    "Cards/_Dark/Icon + Description",

    "Cells/Ω _overrides/List item/__Light",
    "Cells/Ω _overrides/List item/_Dark",
    "Cells/Ω _overrides/Tag/__Light/Read",
    "Cells/Ω _overrides/Tag/_Dark/Read",
    "Cells/Ω _overrides/Tag/__Light/Watch",
    "Cells/Ω _overrides/Tag/_Dark/Watch",
    "Cells/Ω _overrides/Tag/__Light/Time",
    "Cells/Ω _overrides/Tag/_Dark/Time",
    "Cells/Ω _overrides/Tag/Icon",
    "Cells/Ω _overrides/#/__Light/Notification",
    "Cells/Ω _overrides/#/_Dark/Notification",
    "Cells/Ω _overrides/#/__Light/Negative",
    "Cells/Ω _overrides/#/_Dark/Negative",
    "Cells/Ω _overrides/#/__Light/Positive",
    "Cells/Ω _overrides/#/_Dark/Positive",
    "Cells/Ω _overrides/#/__Light/Default",
    "Cells/Ω _overrides/#/_Dark/Default",
    "Cells/Ω _overrides/Icon/__Light/Coaching [multiple]",
    "Cells/Ω _overrides/Icon/_Dark/Coaching [multiple]",
    "Cells/Ω _overrides/Icon/__Light/Coaching",
    "Cells/Ω _overrides/Icon/_Dark/Coaching",
    "Cells/Ω _overrides/Checkbox/__Light/Checked",
    "Cells/Ω _overrides/Checkbox/_Dark/Checked",
    "Cells/Ω _overrides/Checkbox/__Light/_Default",
    "Cells/Ω _overrides/Checkbox/_Dark/_Default",
    "Cells/Ω _overrides/Icon/__Light/_Default",
    "Cells/Ω _overrides/Icon/_Dark/_Default",
    "Cells/Ω _overrides/Right Accessory/__Light/Tag",
    "Cells/Ω _overrides/Right Accessory/_Dark/Tag",
    "Cells/Ω _overrides/Right Accessory/__Light/Detail",
    "Cells/Ω _overrides/Right Accessory/_Dark/Detail",
    "Cells/Ω _overrides/Right Accessory/__Light/Stack",
    "Cells/Ω _overrides/Right Accessory/_Dark/Stack",
    "Cells/Ω _overrides/Right Accessory/__Light/Notification",
    "Cells/Ω _overrides/Right Accessory/_Dark/Notification",
    "Cells/Ω _overrides/Border/__Light/68pt indent",
    "Cells/Ω _overrides/Border/_Dark/68pt indent",
    "Cells/Ω _overrides/Border/__Light/16pt Indent",
    "Cells/Ω _overrides/Border/__Light/52pt Indent",
    "Cells/Ω _overrides/Border/_Dark/16pt Indent",
    "Cells/Ω _overrides/Border/_Dark/52pt Indent",
    "Cells/Ω _overrides/Border/__Light/Full width",
    "Cells/Ω _overrides/Border/_Dark/Full width",
    "Cells/__Light/Button/Left/_Default",
    "Cells/__Light/Button/Center/_Default",
    "Cells/_Dark/Button/Left/Loading",
    "Cells/_Dark/Button/Center/Loading",
    "Cells/_Dark/Button/Left/Destructive",
    "Cells/_Dark/Button/Center/Destructive",
    "Cells/_Dark/Button/Left/Disabled",
    "Cells/_Dark/Button/Center/Disabled",
    "Cells/_Dark/Button/Left/Active",
    "Cells/_Dark/Button/Center/Active",
    "Cells/_Dark/Button/Left/_Default",
    "Cells/_Dark/Button/Center/_Default",
    "Cells/__Light/Button/Left/Active",
    "Cells/__Light/Button/Center/Active",
    "Cells/__Light/Button/Left/Disabled",
    "Cells/__Light/Button/Center/Disabled",
    "Cells/__Light/Button/Left/Destructive",
    "Cells/__Light/Button/Center/Destructive",
    "Cells/__Light/Button/Left/Loading",
    "Cells/__Light/Button/Center/Loading",
    "Cells/__Light/Action/Dropdown",
    "Cells/_Dark/Action/Dropdown",
    "Cells/__Light/Action/To-do",
    "Cells/_Dark/Action/To-do",
    "Cells/__Light/With icon/With CTA",
    "Cells/_Dark/With icon/With CTA",
    "Cells/__Light/With icon/ Label + Large Value + Balance [New]",
    "Cells/_Dark/With icon/ Label + Large Value + Balance [New]",
    "Cells/__Light/With icon/ Label + Large Value + Balance",
    "Cells/_Dark/With icon/ Label + Large Value + Balance",
    "Cells/__Light/With icon/Description + Title",
    "Cells/_Dark/With icon/Description + Title",
    "Cells/__Light/Text only/Caption",
    "Cells/_Dark/Text only/Caption",
    "Cells/__Light/Text only/Value",
    "Cells/_Dark/Text only/Value",
    "Cells/__Light/Text only/List",
    "Cells/_Dark/Text only/List",
    "Cells/__Light/Text only/Label + Value",
    "Cells/_Dark/Text only/Label + Value",
    "Cells/__Light/Text only/Label + Value + Description",
    "Cells/_Dark/Text only/Label + Value + Description",
    "Cells/__Light/Text only/Description + Title",
    "Cells/_Dark/Text only/Description + Title",
    "Cells/__Light/Heading/Overline + Header",
    "Cells/_Dark/Heading/Overline + Header",
    "Cells/__Light/_Base/_Default",
    "Cells/__Light/_Base/Button",
    "Cells/__Light/_Base/Active",
    "Cells/_Dark/_Base/_Default",
    "Cells/_Dark/_Base/Button",
    "Cells/_Dark/_Base/Active",
    "Cells/Ω _overrides/Radio/__Light/_Default",
    "Cells/Ω _overrides/Radio/__Light/_Default [Disabled]",
    "Cells/Ω _overrides/Radio/_Dark/_Default",
    "Cells/Ω _overrides/Radio/_Dark/_Default [Disabled]",
    "Cells/Ω _overrides/Radio/__Light/Checked",
    "Cells/Ω _overrides/Radio/__Light/Checked [Disabled]",
    "Cells/Ω _overrides/Radio/_Dark/Checked",
    "Cells/Ω _overrides/Radio/_Dark/Checked [Disabled]",
    "Cells/Ω _overrides/Switch/Knob",
    "Cells/Ω _overrides/Switch/Rail",
    "Cells/Ω _overrides/Right Accessory/__Light/Dropdown closed",
    "Cells/Ω _overrides/Right Accessory/_Dark/Dropdown closed",
    "Cells/Ω _overrides/Right Accessory/__Light/Dropdown open",
    "Cells/Ω _overrides/Right Accessory/_Dark/Dropdown open",
    "Cells/Ω _overrides/Right Accessory/__Light/CTA",
    "Cells/Ω _overrides/Right Accessory/_Dark/CTA",
    "Cells/Ω _overrides/Header accessory/__Light/Number",
    "Cells/Ω _overrides/Header accessory/_Dark/Number",
    "Cells/Ω _overrides/Header accessory/__Light/Help",
    "Cells/Ω _overrides/Header accessory/_Dark/Help",
    "Cells/Ω _overrides/Product/__Light/Guaranteed APR",
    "Cells/Ω _overrides/Product/_Dark/Guaranteed APR",
    "Cells/Ω _overrides/Product/__Light/Detail",
    "Cells/Ω _overrides/Product/_Dark/Detail",
    "Cells/Ω _overrides/Product/Image",
    "Cells/__Light/Product",
    "Cells/_Dark/Product",
    "Chat/Ω _overrides/__Light/Incoming",
    "Chat/Ω _overrides/_Dark/Incoming",
    "Chat/Ω _overrides/__Light/Outgoing",
    "Chat/Ω _overrides/_Dark/Outgoing",
    "Chat/Ω _overrides/__Light/Not sent",
    "Chat/Ω _overrides/_Dark/Not sent",
    "Chat/__Light/Incoming",
    "Chat/_Dark/Incoming",
    "Chat/__Light/Image",
    "Chat/_Dark/Image",
    "Chat/__Light/Writing",
    "Chat/_Dark/Writing",
    "Chat/__Light/Outgoing",
    "Chat/_Dark/Outgoing",
    "Chat/__Light/Not sent",
    "Chat/_Dark/Not sent",
    "Donuts/🚫 overrides/Ring/Change/Alpha/Stable",
    "Donuts/🚫 overrides/Ring/Change/Beta/Stable",
    "Donuts/🚫 overrides/Ring/Change/Gamma/Stable",
    "Donuts/🚫 overrides/Ring/Change/Delta/Stable",
    "Donuts/🚫 overrides/Ring/Change/Epsilon/Stable",
    "Donuts/_Tertiary/Start",
    "Donuts/_Tertiary/Continue",
    "Donuts/_Tertiary/Tasks",
    "Donuts/🚫 overrides/Ring/Epsilon/100%",
    "Donuts/🚫 overrides/Ring/Tertiary/100%",
    "Donuts/🚫 overrides/Ring/Short Term Debt/100%",
    "Donuts/🚫 overrides/Ring/Long Term Debt/100%",
    "Donuts/🚫 overrides/Ring/Alpha/30%",
    "Donuts/🚫 overrides/Ring/Tertiary/30%",
    "Donuts/🚫 overrides/Ring/Alpha/25%",
    "Donuts/🚫 overrides/Ring/Tertiary/25%",
    "Donuts/🚫 overrides/Ring/Short Term Debt/25%",
    "Donuts/🚫 overrides/Ring/Long Term Debt/25%",
    "Donuts/🚫 overrides/Ring/Alpha/15%",
    "Donuts/🚫 overrides/Ring/Change/Alpha/Up",
    "Donuts/🚫 overrides/Ring/Change/Beta/Up",
    "Donuts/🚫 overrides/Ring/Change/Gamma/Up",
    "Donuts/🚫 overrides/Ring/Change/Delta/Up",
    "Donuts/🚫 overrides/Ring/Change/Epsilon/Up",
    "Donuts/🚫 overrides/Ring/Change/Alpha/Down",
    "Donuts/🚫 overrides/Ring/Change/Beta/Down",
    "Donuts/🚫 overrides/Ring/Change/Gamma/Down",
    "Donuts/🚫 overrides/Ring/Change/Delta/Down",
    "Donuts/🚫 overrides/Ring/Change/Epsilon/Down",
    "Donuts/🚫 overrides/Ring/Tertiary/15%",
    "Donuts/🚫 overrides/Ring/Beta/35%",
    "Donuts/🚫 overrides/Ring/Tertiary/35%",
    "Donuts/🚫 overrides/Ring/Gamma/50%",
    "Donuts/🚫 overrides/Ring/Tertiary/50%",
    "Donuts/🚫 overrides/Ring/Short Term Debt/50%",
    "Donuts/🚫 overrides/Ring/Long Term Debt/50%",
    "Donuts/🚫 overrides/Ring/Beta/40%",
    "Donuts/🚫 overrides/Ring/Tertiary/40%",
    "Donuts/🚫 overrides/Ring/Epsilon/85%",
    "Donuts/🚫 overrides/Ring/Tertiary/85%",
    "Donuts/🚫 overrides/Ring/Epsilon/75%",
    "Donuts/🚫 overrides/Ring/Tertiary/75%",
    "Donuts/🚫 overrides/Ring/Short Term Debt/75%",
    "Donuts/🚫 overrides/Ring/Long Term Debt/75%",
    "Donuts/🚫 overrides/Ring/Delta/70%",
    "Donuts/🚫 overrides/Ring/Delta/62%",
    "Donuts/🚫 overrides/Ring/Tertiary/62%",
    "Donuts/🚫 overrides/Ring/Gamma/55%",
    "Donuts/🚫 overrides/Ring/Tertiary/55%",
    "Donuts/__Primary/Score/01 Alpha",
    "Donuts/__Primary/Score/Theta",
    "Donuts/🚫 overrides/Core/Primary/Score",
    "Donuts/__Primary/Countdown",
    "Donuts/__Primary/Offers/Cards",
    "Donuts/🚫 overrides/Core/Primary/Offer",
    "Donuts/__Primary/Offers/Loans",
    "Donuts/__Primary/Offers/Car Finance",
    "Donuts/__Primary/Change/Up",
    "Donuts/🚫 overrides/Core/Primary/Change",
    "Donuts/__Primary/Change/Down",
    "Donuts/__Primary/Change/Stable",
    "Donuts/__Primary/Short Term Debt/Down",
    "Donuts/🚫 overrides/Core/Primary/Short-term debt",
    "Donuts/__Primary/Long Term Debt/Down",
    "Donuts/🚫 overrides/Core/Primary/Long-term debt",
    "Donuts/__Primary/Short Term Debt/Up",
    "Donuts/__Primary/Short Term Debt/Stable",
    "Donuts/__Primary/Long Term Debt/Up",
    "Donuts/__Primary/Long Term Debt/Stable",
    "Donuts/__Primary/Score/02 Beta",
    "Donuts/__Primary/Score/03 Gamma",
    "Donuts/__Primary/Score/04 Delta",
    "Donuts/__Primary/Score/05 Epsilon",
    "Donuts/_Secondary/Default",
    "Donuts/_Secondary/Number",
    "Donuts/_Simple/Large/_Light/01 Alpha",
    "Donuts/_Simple/Large/__Dark/05 Epsilon",
    "Donuts/_Simple/Large/__Dark/04 Delta",
    "Donuts/_Simple/Large/__Dark/03 Gamma",
    "Donuts/_Simple/Large/__Dark/02 Beta",
    "Donuts/_Simple/Large/__Dark/01 Alpha",
    "Donuts/_Simple/Large/__Dark/00 Theta",
    "Donuts/_Simple/Small/_Light/01 Alpha",
    "Donuts/_Simple/Large/_Light/00 Theta",
    "Donuts/🚫 overrides/Core/Simple/_Light/Small",
    "Donuts/🚫 overrides/Core/Simple/__Dark/Small",
    "Donuts/_Simple/Small/_Light/00 Theta",
    "Donuts/_Simple/Large/_Light/02 Beta",
    "Donuts/_Simple/Small/_Light/02 Beta",
    "Donuts/_Simple/Large/_Light/03 Gamma",
    "Donuts/_Simple/Small/_Light/03 Gamma",
    "Donuts/_Simple/Large/_Light/04 Delta",
    "Donuts/_Simple/Small/_Light/04 Delta",
    "Donuts/_Simple/Large/_Light/05 Epsilon",
    "Donuts/_Simple/Small/_Light/05 Epsilon",
    "Donuts/_Simple/Small/__Dark/05 Epsilon",
    "Donuts/_Simple/Small/__Dark/04 Delta",
    "Donuts/_Simple/Small/__Dark/03 Gamma",
    "Donuts/_Simple/Small/__Dark/02 Beta",
    "Donuts/_Simple/Small/__Dark/01 Alpha",
    "Donuts/_Simple/Small/__Dark/00 Theta",
    "Donuts/🚫 overrides/Core/Simple/Tiny/On Dark",
    "Donuts/🚫 overrides/Core/Simple/Tiny/On Light",
    "Donuts/_Simple/Comparison [Report]",
    "Donuts/🚫 overrides/Center Text/Secondary",
    "Donuts/🚫 overrides/Center Text/Tertiary",
    "Forms/Ω _overrides/_Dark/Filter options/03 Scroll/02 On Dark",
    "Forms/Ω _overrides/__Light/Filter options/03 Scroll/01 On Light",
    "Forms/Ω _overrides/_Dark/Filter options/02 Hover/02 On Dark",
    "Forms/Ω _overrides/__Light/Filter options/02 Hover/01 On Light",
    "Forms/Ω _overrides/_Dark/Filter options/01 Default/02 On Dark",
    "Forms/Ω _overrides/__Light/Filter options/01 Default/01 On Light",
    "Forms/Ω _overrides/_Dark/Icons/Loading/02 On Dark",
    "Forms/Ω _overrides/__Light/Icons/Loading/01 On Light",
    "Forms/Ω _overrides/_Dark/Icons/Filter/02 On Dark",
    "Forms/Ω _overrides/__Light/Icons/Filter/01 On Light",
    "Forms/Ω _overrides/_Dark/Container/Disabled",
    "Forms/Ω _overrides/_Dark/Container/Error",
    "Forms/Ω _overrides/_Dark/Container/Success",
    "Forms/Ω _overrides/_Dark/Container/Warning",
    "Forms/Ω _overrides/_Dark/Container/Dirty",
    "Forms/Ω _overrides/_Dark/Container/Active",
    "Forms/Ω _overrides/_Dark/Container/Default",
    "Forms/Ω _overrides/__Light/Container/Disabled",
    "Forms/Ω _overrides/__Light/Container/Error",
    "Forms/Ω _overrides/__Light/Container/Success",
    "Forms/Ω _overrides/__Light/Container/Warning",
    "Forms/Ω _overrides/__Light/Container/Dirty",
    "Forms/Ω _overrides/__Light/Container/Active",
    "Forms/Ω _overrides/__Light/Container/Default",
    "Forms/Ω _overrides/__Light/Text Area Drag",
    "Forms/Ω _overrides/_Dark/Text Area Drag",

    "Forms/Ω _overrides/_Dark/Criteria/Error/On Dark",
    "Forms/Ω _overrides/__Light/Criteria/Error/",
    "Forms/Ω _overrides/_Dark/Criteria/Warning/On Dark",
    "Forms/Ω _overrides/__Light/Criteria/Warning/",

    "Navigation/Ω _overrides/_Dark/Secondary Item/Active",
    "Navigation/Ω _overrides/__Light/Secondary Item/Active",
    "Navigation/Ω _overrides/_Dark/Secondary Item/Default",
    "Navigation/Ω _overrides/__Light/Secondary Item/Default",

    "Navigation/Ω _overrides/__Light/Modal description",
    "Navigation/Ω _overrides/__Light/Modal title",
    "Navigation/Ω _overrides/_Dark/Modal description",
    "Navigation/Ω _overrides/_Dark/Modal title",
    "Navigation/Ω _overrides/_Dark/Right Accessory/Close",
    "Navigation/Ω _overrides/__Light/Right Accessory/Close",
    "Navigation/Ω _overrides/_Dark/Right Accessory/Label",
    "Navigation/Ω _overrides/__Light/Right Accessory/Label",
    "Navigation/Ω _overrides/_Dark/Right Accessory/My Account",
    "Navigation/Ω _overrides/__Light/Right Accessory/My Account",
    "Navigation/Ω _overrides/__Light/Tab/Timeline/Default",
    "Navigation/Ω _overrides/__Light/Tab/Timeline/Active",
    "Navigation/Ω _overrides/__Light/Tab/Report/Default",
    "Navigation/Ω _overrides/__Light/Tab/Report/Active",
    "Navigation/Ω _overrides/__Light/Tab/Offers/Default",
    "Navigation/Ω _overrides/__Light/Tab/Protect/Default",
    "Navigation/Ω _overrides/__Light/Tab/Offers/Active",
    "Navigation/Ω _overrides/__Light/Tab/Protect/Active",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/05 Epsilon/Default",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/04 Delta/Default",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/03 Gamma/Default",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/02 Beta/Default",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/01 Alpha/Default",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/05 Epsilon/Active",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/04 Delta/Active",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/03 Gamma/Active",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/02 Beta/Active",
    "Navigation/Ω _overrides/__Light/Tab/Dashboard/01 Alpha/Active",
    "Navigation/Ω _overrides/__Light/Tab/Coaching/Default",
    "Navigation/Ω _overrides/__Light/Tab/More/Default",
    "Navigation/Ω _overrides/__Light/Tab/Coaching/Active",
    "Navigation/Ω _overrides/__Light/Tab/More/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Timeline/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Timeline/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Report/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Report/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Offers",
    "Navigation/Ω _overrides/_Dark/Tab/Offers/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/05 Epsilon/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/04 Delta/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/03 Gamma/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/02 Beta/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/01 Alpha/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/05 Epsilon/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/04 Delta/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/03 Gamma/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/02 Beta/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/01 Alpha/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Coaching/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Protect/Default",
    "Navigation/Ω _overrides/_Dark/Tab/Coaching/Active",
    "Navigation/Ω _overrides/_Dark/Tab/Protect/Active",
    "Navigation/Ω _overrides/_Dark/Tab/More/Default",
    "Navigation/Ω _overrides/_Dark/Tab/More/Active",
    "Navigation/Ω _overrides/__Light/Timeline month/Changes",
    "Navigation/Ω _overrides/_Dark/Timeline month/Changes",
    "Navigation/Ω _overrides/__Light/Timeline month/No changes",
    "Navigation/Ω _overrides/_Dark/Timeline month/No changes",
    "Navigation/__Light/Timeline",
    "Navigation/_Dark/Timeline",
    "Navigation/Ω _overrides/_Dark/Product detail/Credit Card",
    "Navigation/Ω _overrides/__Light/Product detail/Credit Card",
    "Navigation/Ω _overrides/_Dark/Product detail/Logo",
    "Navigation/Ω _overrides/__Light/Product detail/Logo",

    "Navigation/Ω _overrides/_Core/Overlay",
    "Navigation/Ω _overrides/_Core/Light",
    "Navigation/Ω _overrides/_Core/Dark",
    "Navigation/Ω _overrides/_Dark/Secondary pill",
    "Navigation/Ω _overrides/__Light/Secondary pill",


    "Text/_Dark/Label + Value/Center",
    "Text/_Dark/Label + Value/Left",
    "Text/_Dark/Label + Value/Right",
    "Text/_Dark/Label + Small value/Center",
    "Text/_Dark/Label + Small value/Left",
    "Text/_Dark/Label + Small value/Right",
    "Text/__Light/Label + Small value/Center",
    "Text/__Light/Label + Small value/Left",
    "Text/__Light/Label + Small value/Right",
    "Text/__Light/Label + Value/Center",
    "Text/__Light/Label + Value/Left",
    "Text/__Light/Label + Value/Right",

    "Widgets/Ω _overrides/__Light/Calendar/Payment",
    "Widgets/Ω _overrides/_Dark/Calendar/Payment",
    "Widgets/Ω _overrides/__Light/Calendar/Missed",
    "Widgets/Ω _overrides/_Dark/Calendar/Missed",
    "Widgets/Ω _overrides/__Light/Calendar/No data",
    "Widgets/Ω _overrides/_Dark/Calendar/No data",
    "Widgets/Ω _overrides/__Light/Missed payment/Dotted Month",
    "Widgets/Ω _overrides/_Dark/Missed payment/Dotted Month",
    "Widgets/Ω _overrides/__Light/Missed payment/Year/Active",
    "Widgets/Ω _overrides/_Dark/Missed payment/Year/Active",
    "Widgets/Ω _overrides/__Light/Missed payment/Year/inactive",
    "Widgets/Ω _overrides/_Dark/Missed payment/Year/inactive",
    "Widgets/Ω _overrides/Score label",
    "Widgets/Ω _overrides/Score change/Up",
    "Widgets/Ω _overrides/Score change/Down",
];
