const CSAndroid_TO_ADD = [
    "Donuts/Primary/Offers/Cards",
    "Donuts/Primary/Countdown",
    "Donuts/Primary/Short Term Debt/Up",
    "Donuts/Primary/Long Term Debt/Down",
    "Donuts/Primary/Change/Down",
    "Donuts/Primary/Change/Up",
    "Donuts/Primary/Score/05 Epsilon",
    "Donuts/Primary/Score/04 Delta",
    "Donuts/Primary/Score/03 Gamma",
    "Donuts/Primary/Score/02 Beta",
    "Donuts/Primary/Score/01 Alpha",
    "Donuts/Primary/Score/Theta",
    "Text/Full-width title/__Light/Without Description/01 XL",
    "Donuts/Secondary/Default",
    "Donuts/Secondary/Number",
    "Donuts/Tertiary/Start",
    "Donuts/Tertiary/Continue",
    "Donuts/Tertiary/Tasks",
    "Donuts/Simple/Large/01 Alpha",
    "Donuts/Simple/Large/02 Beta",
    "Donuts/Simple/Large/03 Gamma",
    "Donuts/Simple/Large/04 Delta",
    "Donuts/Simple/Large/Theta",
    "Donuts/Simple/Large/05 Epsilon",
    "Donuts/Simple/Small/Dark/02 Beta",
    "Donuts/Simple/Small/Dark/03 Gamma",
    "Donuts/Simple/Small/Dark/04 Delta",
    "Donuts/Simple/Small/Dark/05 Epsilon",
    "Donuts/Simple/Small/Dark/00 Theta",
    "Donuts/Simple/Small/Dark/01 Alpha",
    "Donuts/Simple/Small/Dark/02 Beta",
    "Donuts/Simple/Small/Dark/03 Gamma",
    "Donuts/Simple/Small/Dark/04 Delta",
    "Donuts/Simple/Small/Dark/05 Epsilon",
    "Donuts/Simple/Small/Light/00 Theta",
    "Donuts/Simple/Small/Dark/01 Alpha",
    "Form/_field/Text Area/_On Light/Warning",
    "Form/_field/Text Area/_On Light/Success",
    "Form/_field/Text Area/_On Light/Error",
    "Form/_field/Text Area/_On Light/Disabled",
    "Form/_field/Text Area/_On Light/Dirty",
    "Form/_field/Text Area/_On Light/Active",
    "Form/_field/Text Area/_On Light/_Default",
    "Form/_field/Input Filter/_On Light/Warning",
    "Form/_field/Input Filter/_On Light/Success",
    "Form/_field/Input Filter/_On Light/Error",
    "Form/_field/Input Filter/_On Light/Disabled",
    "Form/_field/Input Filter/_On Light/Dirty",
    "Form/_field/Input Filter/_On Light/Loading",
    "Form/_field/Input Filter/_On Light/Active",
    "Form/_field/Input Filter/_On Light/_Default",
    "Form/_field/Input + Prefix + Suffix/_On Light/Warning",
    "Form/_field/Input + Prefix + Suffix/_On Light/Success",
    "Form/_field/Input + Prefix + Suffix/_On Light/Error",
    "Form/_field/Input + Prefix + Suffix/_On Light/Disabled",
    "Form/_field/Input + Prefix + Suffix/_On Light/Dirty",
    "Form/_field/Input + Prefix + Suffix/_On Light/Active",
    "Form/_field/Input + Prefix + Suffix/_On Light/_Default",
    "Form/_field/Input + Suffix/_On Light/Warning",
    "Form/_field/Input + Suffix/_On Light/Success",
    "Form/_field/Input + Suffix/_On Light/Error",
    "Form/_field/Input + Suffix/_On Light/Disabled",
    "Form/_field/Input + Suffix/_On Light/Dirty",
    "Form/_field/Input + Suffix/_On Light/Active",
    "Form/_field/Input + Suffix/_On Light/_Default",
    "Form/_field/Input + Prefix/_On Light/Warning",
    "Form/_field/Input + Prefix/_On Light/Success",
    "Form/_field/Input + Prefix/_On Light/Error",
    "Form/_field/Input + Prefix/_On Light/Disabled",
    "Form/_field/Input + Prefix/_On Light/Dirty",
    "Form/_field/Input + Prefix/_On Light/Active",
    "Form/_field/Input + Prefix/_On Light/_Default",
    "Form/_field/Dropdown/_On Light/Warning",
    "Form/_field/Dropdown/_On Light/Success",
    "Form/_field/Dropdown/_On Light/Error",
    "Form/_field/Dropdown/_On Light/Disabled",
    "Form/_field/Dropdown/_On Light/Dirty",
    "Form/_field/Dropdown/_On Light/Active",
    "Form/_field/Dropdown/_On Light/_Default",
    "Form/_field/Input/_On Light/Warning",
    "Form/_field/Input/_On Light/Success",
    "Form/_field/Input/_On Light/Error",
    "Form/_field/Input/_On Light/Disabled",
    "Form/_field/Input/_On Light/Dirty",
    "Form/_field/Input/_On Light/Active",
    "Form/_field/Input/_On Light/_Default",
    "Forms/_Dark/☞ Field/Text Area/Warning",
    "Forms/_Dark/☞ Field/Text Area/Success",
    "Forms/_Dark/☞ Field/Text Area/Error",
    "Forms/_Dark/☞ Field/Text Area/Disabled",
    "Forms/_Dark/☞ Field/Text Area/Dirty",
    "Forms/_Dark/☞ Field/Text Area/Active",
    "Forms/_Dark/☞ Field/Text Area/_Default",
    "Forms/_Dark/☞ Field/Input Filter/Warning",
    "Forms/_Dark/☞ Field/Input Filter/Success",
    "Forms/_Dark/☞ Field/Input Filter/Error",
    "Forms/_Dark/☞ Field/Input Filter/Dirty",
    "Forms/_Dark/☞ Field/Input Filter/Loading",
    "Forms/_Dark/☞ Field/Input Filter/Active",
    "Forms/_Dark/☞ Field/Input Filter/_Default",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Warning",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Success",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Error",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Disabled",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/_Default",
    "Forms/_Dark/☞ Field/Input + Suffix/Warning",
    "Forms/_Dark/☞ Field/Input + Suffix/Success",
    "Forms/_Dark/☞ Field/Input + Suffix/Error",
    "Forms/_Dark/☞ Field/Input + Suffix/Disabled",
    "Forms/_Dark/☞ Field/Input + Suffix/Active",
    "Forms/_Dark/☞ Field/Input + Suffix/_Default",
    "Forms/_Dark/☞ Field/Input + Prefix/Warning",
    "Forms/_Dark/☞ Field/Input + Prefix/Error",
    "Forms/_Dark/☞ Field/Input + Prefix/Dirty",
    "Forms/_Dark/☞ Field/Input + Prefix/_Default",
    "Forms/_Dark/☞ Field/Dropdown/Warning",
    "Forms/_Dark/☞ Field/Dropdown/Success",
    "Forms/_Dark/☞ Field/Dropdown/Error",
    "Forms/_Dark/☞ Field/Dropdown/Disabled",
    "Forms/_Dark/☞ Field/Dropdown/Dirty",
    "Forms/_Dark/☞ Field/Dropdown/Active",
    "Forms/_Dark/☞ Field/Dropdown/_Default",
    "Forms/_Dark/☞ Field/Input/Warning",
    "Forms/_Dark/☞ Field/Input/Success",
    "Forms/_Dark/☞ Field/Input/Error",
    "Forms/_Dark/☞ Field/Input/Disabled",
    "Forms/_Dark/☞ Field/Input/Dirty",
    "Forms/_Dark/☞ Field/Input/Active",
    "Forms/_Dark/☞ Field/Input/_Default",
    "Form/Label + Field/_On Light/Simple Disabled",
    "Form/Label + Field/_On Light/Simple Criteria",
    "Form/Label + Field/_On Light/Simple",
    "Form/Label + Field/_On Light/Disabled",
    "Form/Label + Field/_On Light/Criteria",
    "Form/Label + Field/_On Light/_Default",
    "Forms/_Dark/Simple Disabled",
    "Forms/_Dark/Simple Criteria",
    "Forms/_Dark/Simple",
    "Forms/_Dark/Disabled",
    "Forms/_Dark/Criteria",
    "Forms/_Dark/_Default",
    "Button/__Light/03 Tertiary/Loading",
    "Button/__Light/03 Tertiary/Loading [Smart]",
    "Button/__Light/03 Tertiary/Loading [Tight]",
    "Button/__Light/03 Tertiary/Disabled",
    "Button/__Light/03 Tertiary/Disabled [Smart]",
    "Button/__Light/03 Tertiary/Disabled [Tight]",
    "Button/__Light/03 Tertiary/Pressed",
    "Button/__Light/03 Tertiary/Pressed [Smart]",
    "Button/__Light/03 Tertiary/Pressed [Tight]",
    "Button/__Light/03 Tertiary/_Default",
    "Button/__Light/03 Tertiary/_Default [Smart]",
    "Button/__Light/03 Tertiary/_Default [Tight]",
    "Button/__Light/02 Secondary/Loading",
    "Button/__Light/02 Secondary/Loading [Smart]",
    "Button/__Light/02 Secondary/Loading [Tight]",
    "Button/__Light/02 Secondary/Disabled",
    "Button/__Light/02 Secondary/Disabled [Smart]",
    "Button/__Light/02 Secondary/Disabled [Tight]",
    "Button/__Light/02 Secondary/Pressed",
    "Button/__Light/02 Secondary/Pressed [Smart]",
    "Button/__Light/02 Secondary/Pressed [Tight]",
    "Button/__Light/02 Secondary/_Default",
    "Button/__Light/02 Secondary/_Default [Smart]",
    "Button/__Light/02 Secondary/_Default [Tight]",
    "Button/__Light/01 Primary/Loading",
    "Button/__Light/01 Primary/Loading [Smart]",
    "Button/__Light/01 Primary/Loading [Tight]",
    "Button/__Light/01 Primary/Disabled",
    "Button/__Light/01 Primary/Disabled [Smart]",
    "Button/__Light/01 Primary/Disabled [Tight]",
    "Button/__Light/01 Primary/Pressed",
    "Button/__Light/01 Primary/Pressed [Smart]",
    "Button/__Light/01 Primary/Pressed [Tight]",
    "Button/__Light/01 Primary/_Default",
    "Button/__Light/01 Primary/_Default [Smart]",
    "Button/__Light/01 Primary/_Default [Tight]",
    "Forms/__Light/Multi Select/Active",
    "Forms/__Light/Multi Select/_Default",
    "Button/_Dark/03 Tertiary/Loading",
    "Button/_Dark/03 Tertiary/Loading [Smart]",
    "Button/_Dark/03 Tertiary/Loading [Tight]",
    "Button/_Dark/03 Tertiary/Disabled",
    "Button/_Dark/03 Tertiary/Disabled [Smart]",
    "Button/_Dark/03 Tertiary/Disabled [Tight]",
    "Button/_Dark/03 Tertiary/Pressed",
    "Button/_Dark/03 Tertiary/Pressed [Smart]",
    "Button/_Dark/03 Tertiary/Pressed [Tight]",
    "Button/_Dark/03 Tertiary/_Default",
    "Button/_Dark/03 Tertiary/_Default [Smart]",
    "Button/_Dark/03 Tertiary/_Default [Tight]",
    "Button/_Dark/02 Secondary/Loading",
    "Button/_Dark/02 Secondary/Loading [Smart]",
    "Button/_Dark/02 Secondary/Loading [Tight]",
    "Button/_Dark/02 Secondary/Disabled",
    "Button/_Dark/02 Secondary/Disabled [Smart]",
    "Button/_Dark/02 Secondary/Disabled [Tight]",
    "Button/_Dark/02 Secondary/Pressed",
    "Button/_Dark/02 Secondary/Pressed [Tight]",
    "Button/_Dark/02 Secondary/_Default",
    "Button/_Dark/02 Secondary/_Default [Smart]",
    "Button/_Dark/02 Secondary/_Default [Tight]",
    "Button/_Dark/01 Primary/Loading",
    "Button/_Dark/01 Primary/Loading [Smart]",
    "Button/_Dark/01 Primary/Loading [Tight]",
    "Button/_Dark/01 Primary/Disabled",
    "Button/_Dark/01 Primary/Disabled [Smart]",
    "Button/_Dark/01 Primary/Disabled [Tight]",
    "Button/_Dark/01 Primary/Pressed",
    "Button/_Dark/01 Primary/Pressed [Smart]",
    "Button/_Dark/01 Primary/Pressed [Tight]",
    "Button/_Dark/01 Primary/_Default",
    "Button/_Dark/01 Primary/_Default [Smart]",
    "Button/_Dark/01 Primary/_Default [Tight]",
    "Forms/_Dark/Multi Select/Active",
    "Forms/_Dark/Multi Select/_Default",
    "Cells/__Light/Text only/Title + Description",
    "Cells/__Light/Text only/Title",
    "Cells/__Light/Action/Radio [Disabled]",
    "Cells/__Light/Action/Radio",
    "Cells/__Light/Action/Switch [Disabled]",
    "Cells/__Light/Action/Switch",
    "Cells/__Light/Button/Center/Loading",
    "Cells/__Light/Button/Center/Disabled",
    "Cells/__Light/Button/Center/Destructive",
    "Cells/__Light/Button/Center/Active",
    "Cells/__Light/Button/Left/Loading",
    "Cells/__Light/Button/Left/Disabled",
    "Cells/__Light/Button/Left/Destructive",
    "Cells/__Light/Button/Left/Active",
    "Cells/__Light/Button/Left/_Default",
    "Cells/__Light/Product",
    "Cells/__Light/Action/Dropdown",
    "Cells/__Light/Action/To-do",
    "Cells/__Light/With icon/With CTA",
    "Cells/__Light/With icon/Description + Title",
    "Cells/__Light/With icon/Title + Description",
    "Cells/__Light/With icon/Title",
    "Cells/__Light/Text only/List",
    "Cells/__Light/Text only/Label + Value + Description",
    "Cells/__Light/Text only/Label + Value",
    "Cells/__Light/Text only/Value",
    "Cells/__Light/Text only/Description + Title",
    "Cells/__Light/Heading/Overline + Header",
    "Cells/__Light/Heading/Header",
    "Cells/__Light/Heading/Large Header",
    "Cells/__Light/_Base/_Default",
    "Cells/_Dark/Text only/Title + Description",
    "Cells/_Dark/Text only/Title",
    "Cells/_Dark/Action/Radio [Disabled]",
    "Cells/_Dark/Action/Radio",
    "Cells/_Dark/Action/Switch [Disabled]",
    "Cells/_Dark/Action/Switch",
    "Cells/_Dark/Button/Center/Loading",
    "Cells/_Dark/Button/Center/Disabled",
    "Cells/_Dark/Button/Center/Destructive",
    "Cells/_Dark/Button/Center/Active",
    "Cells/_Dark/Button/Center/_Default",
    "Cells/_Dark/Button/Left/Loading",
    "Cells/_Dark/Button/Left/Disabled",
    "Cells/_Dark/Button/Left/Destructive",
    "Cells/_Dark/Button/Left/Active",
    "Cells/_Dark/Button/Left/_Default",
    "Cells/_Dark/Product",
    "Cells/_Dark/Action/Dropdown",
    "Cells/_Dark/Action/To-do",
    "Cells/_Dark/With icon/With CTA",
    "Cells/_Dark/With icon/Description + Title",
    "Cells/_Dark/With icon/Title + Description",
    "Cells/_Dark/With icon/Title",
    "Cells/_Dark/Text only/List",
    "Cells/_Dark/Text only/Label + Value + Description",
    "Cells/_Dark/Text only/Label + Value",
    "Cells/_Dark/Text only/Value",
    "Cells/_Dark/Text only/Description + Title",
    "Cells/_Dark/Heading/Overline + Header",
    "Cells/_Dark/Heading/Header",
    "Cells/_Dark/Heading/Large Header",
    "Cells/_Dark/_Base/_Default",
    "Navigation/__Light/Secondary/Center",
    "Navigation/__Light/Secondary/Right",
    "Navigation/__Light/Secondary/Left",
    "Navigation/__Light/Timeline",
    "Navigation/__Light/Tab bar/Coaching",
    "Navigation/__Light/Tab bar/Timeline/_On Dark",
    "Navigation/__Light/Tab bar/Offers",
    "Navigation/__Light/Tab bar/Report",
    "Navigation/__Light/Tab bar/Dashboard",
    "Navigation/_Dark/Product Detail",
    "Navigation/__Light/Product Detail",
    "Navigation/__Light/Navigation bar/_Default",
    "Navigation/__Light/Navigation bar/Modal",
    "Navigation/__Light/Navigation bar/Overlay",
    "Navigation/__Light/Navigation bar/With icon",
    "Navigation/_Dark/Secondary/Center",
    "Navigation/_Dark/Secondary/Right",
    "Navigation/_Dark/Secondary/Left",
    "Navigation/_Dark/Timeline",
    "Navigation/_Dark/Tab bar/Coaching",
    "Navigation/_Dark/Tab bar/Timeline/_On Dark",
    "Navigation/_Dark/Tab bar/Offers",
    "Navigation/_Dark/Tab bar/Dashboard",
    "Navigation/_Dark/Navigation bar/_Default",
    "Navigation/_Dark/Navigation bar/Modal",
    "Navigation/_Dark/Navigation bar/Overlay",
    "Navigation/_Dark/Navigation bar/With icon",
    "Cards/__Light/Title + Description",
    "Cards/__Light/Overline + Value",
    "Cards/__Light/Title + Description + CTA",
    "Cards/__Light/Callout",
    "Cards/__Light/Icon + Title + Description",
    "Cards/__Light/Icon + Description",
    "Cards/__Light/Icon + Title + Progress",
    "Cards/__Light/Image + Title",
    "Cards/__Light/Label + Title + Description + Label",
    "Cards/_Account",
    "Cards/__Light/_Base",
    "Cards/_Dark/Title + Description",
    "Cards/_Dark/Overline + Value",
    "Cards/_Dark/Title + Description + CTA",
    "Cards/_Dark/Callout",
    "Cards/_Dark/Icon + Title + Description",
    "Cards/_Dark/Icon + Description",
    "Cards/_Dark/Icon + Title + Progress",
    "Cards/_Dark/Image + Title",
    "Cards/_Dark/Label + Title + Description + Label",
    "Cards/_Dark/_Base"
];
