const CSAndroid_TO_ADD = [

    "_global/__Light/Trend/Up",
    "_global/_Dark/Trend/Up",
    "_global/__Light/Trend/Down",
    "_global/_Dark/Trend/Down",
    "_global/__Light/Notification Dot",
    "_global/_Dark/Notification Dot",
    // OVERRIDE:    "_global/Ω _overrides/__Light/Alert/Title",
    // OVERRIDE:    "_global/Ω _overrides/_Dark/Alert/Title",
    // OVERRIDE:    "_global/Ω _overrides/__Light/Alert/Description",
    // OVERRIDE:    "_global/Ω _overrides/_Dark/Alert/Description",
    // OVERRIDE:    "_global/Ω _overrides/__Light/Alert/CTAs",
    // OVERRIDE:    "_global/Ω _overrides/_Dark/Alert/CTAs",
    "_global/__Light/Page help",
    "_global/_Dark/Page help",
    "_global/_Dark/Page help Overlay",
    "_global/Logo header",
    "_global/Icon mask",

    // OVERRIDE:    "Button/Ω _overrides/Loader/White",
    // OVERRIDE:    "Button/Ω _overrides/Loader/Midnight",
    // OVERRIDE:    "Button/Ω _overrides/Loader/Chill",
    // OVERRIDE:    "Button/Ω _overrides/Ripple/On Light",
    // OVERRIDE:    "Button/Ω _overrides/Shadow/__Light",
    // OVERRIDE:    "Button/Ω _overrides/Shadow/_Dark",
    // OVERRIDE:    "Button/Ω _overrides/Ripple/On Dark",

    "SegmentedControl/_Light/2 Buttons",
    "SegmentedControl/Dark/2 Buttons",
    "SegmentedControl/_Light/3 Buttons",
    "SegmentedControl/Dark/3 Buttons",
    "SegmentedControl/_Light/4 Buttons",
    "SegmentedControl/Dark/4 Buttons",
    // OVERRIDE:    "SegmentedControl/Ω _overrides/Option/_Light/Active",
    // OVERRIDE:    "SegmentedControl/Ω _overrides/Option/Dark/Active",
    // OVERRIDE:    "SegmentedControl/Ω _overrides/Option/_Light/Default",
    // OVERRIDE:    "SegmentedControl/Ω _overrides/Option/Dark/Default",
    // OVERRIDE:    "SegmentedControl/Ω _overrides/Core/_Light",
    // OVERRIDE:    "SegmentedControl/Ω _overrides/Core/Dark",

    // OVERRIDE:    "Cards/Ω _overrides/Header/_Dark/Icon",
    // OVERRIDE:    "Cards/Ω _overrides/Header/_Dark/Tags",
    // OVERRIDE:    "Cards/Ω _overrides/Header/__Light/Icon",
    // OVERRIDE:    "Cards/Ω _overrides/Header/__Light/Tags",
    // OVERRIDE:    "Cards/Ω _overrides/Card footer/__Light",
    // OVERRIDE:    "Cards/Ω _overrides/Card footer/_Dark",

    // OVERRIDE:    "Cells/Ω _overrides/List item/__Light",
    // OVERRIDE:    "Cells/Ω _overrides/List item/_Dark",
    // OVERRIDE:    "Cells/Ω _overrides/Tag/__Light/Read",
    // OVERRIDE:    "Cells/Ω _overrides/Tag/_Dark/Read",
    // OVERRIDE:    "Cells/Ω _overrides/Tag/__Light/Watch",
    // OVERRIDE:    "Cells/Ω _overrides/Tag/_Dark/Watch",
    // OVERRIDE:    "Cells/Ω _overrides/Tag/__Light/Time",
    // OVERRIDE:    "Cells/Ω _overrides/Tag/_Dark/Time",
    // OVERRIDE:    "Cells/Ω _overrides/Tag/Icon",
    // OVERRIDE:    "Cells/Ω _overrides/#/__Light/Notification",
    // OVERRIDE:    "Cells/Ω _overrides/#/_Dark/Notification",
    // OVERRIDE:    "Cells/Ω _overrides/#/__Light/Negative",
    // OVERRIDE:    "Cells/Ω _overrides/#/_Dark/Negative",
    // OVERRIDE:    "Cells/Ω _overrides/#/__Light/Positive",
    // OVERRIDE:    "Cells/Ω _overrides/#/_Dark/Positive",
    // OVERRIDE:    "Cells/Ω _overrides/#/__Light/Default",
    // OVERRIDE:    "Cells/Ω _overrides/#/_Dark/Default",
    // OVERRIDE:    "Cells/Ω _overrides/Icon/__Light/Coaching [multiple]",
    // OVERRIDE:    "Cells/Ω _overrides/Icon/_Dark/Coaching [multiple]",
    // OVERRIDE:    "Cells/Ω _overrides/Icon/__Light/Coaching",
    // OVERRIDE:    "Cells/Ω _overrides/Icon/_Dark/Coaching",
    // OVERRIDE:    "Cells/Ω _overrides/Checkbox/__Light/Checked",
    // OVERRIDE:    "Cells/Ω _overrides/Checkbox/_Dark/Checked",
    // OVERRIDE:    "Cells/Ω _overrides/Checkbox/__Light/_Default",
    // OVERRIDE:    "Cells/Ω _overrides/Checkbox/_Dark/_Default",
    // OVERRIDE:    "Cells/Ω _overrides/Icon/__Light/_Default",
    // OVERRIDE:    "Cells/Ω _overrides/Icon/_Dark/_Default",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/__Light/Tag",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/_Dark/Tag",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/__Light/Detail",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/_Dark/Detail",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/__Light/Stack",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/_Dark/Stack",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/__Light/Notification",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/_Dark/Notification",
    // OVERRIDE:    "Cells/Ω _overrides/Border/__Light/64pt indent",
    // OVERRIDE:    "Cells/Ω _overrides/Border/_Dark/68pt indent",
    // OVERRIDE:    "Cells/Ω _overrides/Border/__Light/16pt Indent",
    // OVERRIDE:    "Cells/Ω _overrides/Border/__Light/52pt Indent",
    // OVERRIDE:    "Cells/Ω _overrides/Border/_Dark/16pt Indent",
    // OVERRIDE:    "Cells/Ω _overrides/Border/_Dark/52pt Indent",
    // OVERRIDE:    "Cells/Ω _overrides/Border/__Light/Full width",
    // OVERRIDE:    "Cells/Ω _overrides/Border/_Dark/Full width",

    "Cells/__Light/_Base/Button",
    "Cells/_Dark/_Base/Button",
    // OVERRIDE:    "Cells/Ω _overrides/Radio/__Light/_Default",
    // OVERRIDE:    "Cells/Ω _overrides/Radio/__Light/_Default [Disabled]",
    // OVERRIDE:    "Cells/Ω _overrides/Radio/_Dark/_Default",
    // OVERRIDE:    "Cells/Ω _overrides/Radio/_Dark/_Default [Disabled]",
    // OVERRIDE:    "Cells/Ω _overrides/Radio/__Light/Checked",
    // OVERRIDE:    "Cells/Ω _overrides/Radio/__Light/Checked [Disabled]",
    // OVERRIDE:    "Cells/Ω _overrides/Radio/_Dark/Checked",
    // OVERRIDE:    "Cells/Ω _overrides/Radio/_Dark/Checked [Disabled]",
    // OVERRIDE:    "Cells/Ω _overrides/Switch/Knob",
    // OVERRIDE:    "Cells/Ω _overrides/Switch/Rail",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/__Light/Dropdown closed",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/_Dark/Dropdown closed",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/__Light/Dropdown open",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/_Dark/Dropdown open",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/__Light/CTA",
    // OVERRIDE:    "Cells/Ω _overrides/Right Accessory/_Dark/CTA",
    // OVERRIDE:    "Cells/Ω _overrides/Header accessory/__Light/Number",
    // OVERRIDE:    "Cells/Ω _overrides/Header accessory/_Dark/Number",
    // OVERRIDE:    "Cells/Ω _overrides/Header accessory/__Light/Help",
    // OVERRIDE:    "Cells/Ω _overrides/Header accessory/_Dark/Help",
    // OVERRIDE:    "Cells/Ω _overrides/Product/__Light/Guaranteed APR",
    // OVERRIDE:    "Cells/Ω _overrides/Product/_Dark/Guaranteed APR",
    // OVERRIDE:    "Cells/Ω _overrides/Product/__Light/Detail",
    // OVERRIDE:    "Cells/Ω _overrides/Product/_Dark/Detail",
    // OVERRIDE:    "Cells/Ω _overrides/Product/Image",

    // OVERRIDE:    "Cells/Ω _overrides/Header accessory/__Light/CTA",
    // OVERRIDE:    "Cells/Ω _overrides/Header accessory/_Dark/CTA",

    // OVERRIDE:    "Chat/Ω _overrides/__Light/Incoming",
    // OVERRIDE:    "Chat/Ω _overrides/_Dark/Incoming",
    // OVERRIDE:    "Chat/Ω _overrides/__Light/Outgoing",
    // OVERRIDE:    "Chat/Ω _overrides/_Dark/Outgoing",
    // OVERRIDE:    "Chat/Ω _overrides/__Light/Not sent",
    // OVERRIDE:    "Chat/Ω _overrides/_Dark/Not sent",

    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Alpha/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Beta/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Gamma/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Delta/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Epsilon/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Epsilon/100%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/100%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Short Term Debt/100%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Long Term Debt/100%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Alpha/30%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/30%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Alpha/25%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/25%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Short Term Debt/25%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Long Term Debt/25%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Alpha/15%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Alpha/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Beta/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Gamma/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Delta/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Epsilon/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Alpha/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Beta/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Gamma/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Delta/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Epsilon/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/15%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Beta/35%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/35%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Gamma/50%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/50%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Short Term Debt/50%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Long Term Debt/50%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Beta/40%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/40%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Epsilon/85%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/85%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Epsilon/75%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/75%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Short Term Debt/75%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Long Term Debt/75%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Delta/70%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Delta/62%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/62%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Gamma/55%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Tertiary/55%",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Primary/Score",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Primary/Offer",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Primary/Change",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Primary/Short-term debt",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Primary/Long-term debt",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Simple/_Light/Small",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Simple/__Dark/Small",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Simple/Tiny/On Dark",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Simple/Tiny/On Light",
    // OVERRIDE:    "Donuts/🚫 overrides/Center Text/Secondary",
    // OVERRIDE:    "Donuts/🚫 overrides/Center Text/Tertiary",

    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Filter options/03 Scroll/02 On Dark",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Filter options/03 Scroll/01 On Light",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Filter options/02 Hover/02 On Dark",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Filter options/02 Hover/01 On Light",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Filter options/01 Default/02 On Dark",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Filter options/01 Default/01 On Light",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Icons/Loading/02 On Dark",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Icons/Loading/01 On Light",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Icons/Filter/02 On Dark",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Icons/Filter/01 On Light",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Container/Disabled",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Container/Error",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Container/Success",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Container/Warning",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Container/Dirty",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Container/Active",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Container/Default",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Container/Disabled",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Container/Error",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Container/Success",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Container/Warning",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Container/Dirty",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Container/Active",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Container/Default",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Text Area Drag",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Text Area Drag",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Criteria/Error/On Dark",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Criteria/Error/",
    // OVERRIDE:    "Forms/Ω _overrides/_Dark/Criteria/Warning/On Dark",
    // OVERRIDE:    "Forms/Ω _overrides/__Light/Criteria/Warning/",

    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tags",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tags",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Secondary Item/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Secondary Item/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Secondary Item/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Secondary Item/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Modal description",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Modal title",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Modal description",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Modal title",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Right Accessory/Close",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Right Accessory/Close",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Right Accessory/Label",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Right Accessory/Label",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Right Accessory/Icons",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Right Accessory/Icons",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Timeline/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Timeline/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Report/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Report/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Offers/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Protect/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Offers/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Protect/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/05 Epsilon/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/04 Delta/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/03 Gamma/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/02 Beta/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/01 Alpha/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/05 Epsilon/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/04 Delta/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/03 Gamma/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/02 Beta/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Dashboard/01 Alpha/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Coaching/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/More/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/Coaching/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Tab/More/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Timeline/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Timeline/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Report/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Report/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Offers",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Offers/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/05 Epsilon/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/04 Delta/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/03 Gamma/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/02 Beta/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/01 Alpha/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/05 Epsilon/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/04 Delta/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/03 Gamma/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/02 Beta/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Dashboard/01 Alpha/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Coaching/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Protect/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Coaching/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/Protect/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/More/Default",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Tab/More/Active",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Timeline month/Changes",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Timeline month/Changes",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Timeline month/No changes",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Timeline month/No changes",
    "Navigation/__Light/Timeline",
    "Navigation/_Dark/Timeline",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Product detail/Credit Card",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Product detail/Credit Card",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Product detail/Logo",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Product detail/Logo",
    // OVERRIDE:    "Navigation/Ω _overrides/_Core/Overlay",
    // OVERRIDE:    "Navigation/Ω _overrides/_Core/Light",
    // OVERRIDE:    "Navigation/Ω _overrides/_Core/Dark",
    // OVERRIDE:    "Navigation/Ω _overrides/_Dark/Secondary pill",
    // OVERRIDE:    "Navigation/Ω _overrides/__Light/Secondary pill",

    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Rating #/#",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Rating #/#",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Rating #/Rating",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Rating #/Rating",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Rating #/Center",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Rating #/Center",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Title",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Description",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Binary rating",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Title",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Description",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Binary rating",
    "Ratings/__Light/Hero + Lender",
    "Ratings/_Dark/Hero",

    // OVERRIDE:    "Text/🚫 overrides/__Light/Title + Description/Description",
    // OVERRIDE:    "Text/🚫 overrides/__Light/Title + Description/Title",
    // OVERRIDE:    "Text/🚫 overrides/_Dark/Title + Description/Description",
    // OVERRIDE:    "Text/🚫 overrides/_Dark/Title + Description/Title",
    // OVERRIDE:    "Text/🚫 overrides/__Light/Title + Description/CTA",
    // OVERRIDE:    "Text/🚫 overrides/_Dark/Title + Description/CTA",

    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Calendar/Payment",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Calendar/Payment",
    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Calendar/Missed",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Calendar/Missed",
    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Calendar/No data",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Calendar/No data",
    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Missed payment/Dotted Month",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Missed payment/Dotted Month",
    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Missed payment/Year/Active",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Missed payment/Year/Active",
    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Missed payment/Year/inactive",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Missed payment/Year/inactive",
    // OVERRIDE:    "Widgets/Ω _overrides/Score label",
    // OVERRIDE:    "Widgets/Ω _overrides/Score change/Up",
    // OVERRIDE:    "Widgets/Ω _overrides/Score change/Down",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Report changes/Description",
    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Report changes/Description",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Report changes/Status",
    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Report changes/Status",
    // OVERRIDE:    "Widgets/Ω _overrides/_Dark/Report changes/Header",
    // OVERRIDE:    "Widgets/Ω _overrides/__Light/Report changes/Header",
];
