const symbols = [
    {
        componentName: 'CSInputField',
        names: [
            "Forms/_Dark/☞ Field/Text Area/Disabled",
            "Forms/_Dark/☞ Field/Text Area/Error",
            "Forms/_Dark/☞ Field/Text Area/Warning",
            "Forms/_Dark/☞ Field/Text Area/Success",
            "Forms/_Dark/☞ Field/Text Area/Dirty",
            "Forms/_Dark/☞ Field/Text Area/Active",
            "Forms/_Dark/☞ Field/Text Area/_Default",
            "Forms/__Light/☞ Field/Text Area/Disabled",
            "Forms/__Light/☞ Field/Text Area/Error",
            "Forms/__Light/☞ Field/Text Area/Warning",
            "Forms/__Light/☞ Field/Text Area/Success",
            "Forms/__Light/☞ Field/Text Area/Dirty",
            "Forms/__Light/☞ Field/Text Area/Active",
            "Forms/__Light/☞ Field/Text Area/_Default",
            "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Disabled",
            "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Error",
            "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Warning",
            "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Success",
            "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Dirty",
            "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Active",
            "Forms/_Dark/☞ Field/Input + Prefix + Suffix/_Default",
            "Forms/__Light/☞ Field/Input + Prefix + Suffix/Disabled",
            "Forms/_Dark/☞ Field/Input + Suffix/Disabled",
            "Forms/_Dark/☞ Field/Input + Suffix/Error",
            "Forms/_Dark/☞ Field/Input + Suffix/Warning",
            "Forms/_Dark/☞ Field/Input + Suffix/Success",
            "Forms/_Dark/☞ Field/Input + Suffix/Dirty",
            "Forms/_Dark/☞ Field/Input + Suffix/Active",
            "Forms/_Dark/☞ Field/Input + Suffix/_Default",
            "Forms/__Light/☞ Field/Input + Suffix/Disabled",
            "Forms/_Dark/☞ Field/Input + Prefix/Disabled",
            "Forms/_Dark/☞ Field/Input + Prefix/Error",
            "Forms/_Dark/☞ Field/Input + Prefix/Warning",
            "Forms/_Dark/☞ Field/Input + Prefix/Success",
            "Forms/_Dark/☞ Field/Input + Prefix/Dirty",
            "Forms/_Dark/☞ Field/Input + Prefix/Active",
            "Forms/_Dark/☞ Field/Input + Prefix/_Default",
            "Forms/__Light/☞ Field/Input + Prefix/Disabled",
            "Forms/_Dark/☞ Field/Input/Disabled",
            "Forms/_Dark/☞ Field/Input/Error",
            "Forms/_Dark/☞ Field/Input/Warning",
            "Forms/_Dark/☞ Field/Input/Success",
            "Forms/_Dark/☞ Field/Input/Dirty",
            "Forms/_Dark/☞ Field/Input/Active",
            "Forms/_Dark/☞ Field/Input/_Default",
            "Forms/_Dark/☞ Field/Input Filter/Disabled",
            "Forms/__Light/☞ Field/Input/Disabled",
            "Forms/__Light/☞ Field/Input Filter/Loading",
            "Forms/__Light/☞ Field/Input Filter/Disabled",
            "Forms/__Light/☞ Field/Input Filter/Error",
            "Forms/__Light/☞ Field/Input Filter/Warning",
            "Forms/__Light/☞ Field/Input Filter/Success",
            "Forms/__Light/☞ Field/Input Filter/Dirty",
            "Forms/__Light/☞ Field/Input Filter/Active",
            "Forms/__Light/☞ Field/Input Filter/_Default",
            "Forms/__Light/☞ Field/Input + Prefix + Suffix/Error",
            "Forms/__Light/☞ Field/Input + Prefix + Suffix/Warning",
            "Forms/__Light/☞ Field/Input + Suffix/Error",
            "Forms/__Light/☞ Field/Input + Suffix/Warning",
            "Forms/__Light/☞ Field/Input + Prefix/Error",
            "Forms/__Light/☞ Field/Input + Prefix/Warning",
            "Forms/__Light/☞ Field/Input/Error",
            "Forms/__Light/☞ Field/Input/Warning",
            "Forms/__Light/☞ Field/Input + Prefix + Suffix/Success",
            "Forms/__Light/☞ Field/Input + Prefix + Suffix/Dirty",
            "Forms/__Light/☞ Field/Input + Prefix + Suffix/Active",
            "Forms/__Light/☞ Field/Input + Prefix + Suffix/_Default",
            "Forms/__Light/☞ Field/Input + Suffix/Success",
            "Forms/__Light/☞ Field/Input + Suffix/Dirty",
            "Forms/__Light/☞ Field/Input + Suffix/Active",
            "Forms/__Light/☞ Field/Input + Suffix/_Default",
            "Forms/__Light/☞ Field/Input + Prefix/Success",
            "Forms/__Light/☞ Field/Input + Prefix/Dirty",
            "Forms/__Light/☞ Field/Input + Prefix/Active",
            "Forms/__Light/☞ Field/Input + Prefix/_Default",
            "Forms/__Light/☞ Field/Input/Success",
            "Forms/__Light/☞ Field/Input/Dirty",
            "Forms/__Light/☞ Field/Input/Active",
            "Forms/__Light/☞ Field/Input/_Default",
        ],
    },
    {
        componentName: "CSPrimaryButton",
        names: [
            "Button/__Light/01 Primary/Loading",
            "Button/__Light/01 Primary/Disabled",
            "Button/__Light/01 Primary/Disabled [Smart]",
            "Button/__Light/01 Primary/Disabled [Tight]",
            "Button/__Light/01 Primary/Pressed",
            "Button/__Light/01 Primary/Pressed [Smart]",
            "Button/__Light/01 Primary/Pressed [Tight]",
            "Button/__Light/01 Primary/_Default",
            "Button/__Light/01 Primary/_Default [Smart]",
            "Button/__Light/01 Primary/Loading [Smart]",
            "Button/__Light/01 Primary/_Default [Tight]",
            "Button/__Light/01 Primary/Loading [Tight]",
            "Button/_Dark/01 Primary/Loading",
            "Button/_Dark/01 Primary/Disabled",
            "Button/_Dark/01 Primary/Disabled [Smart]",
            "Button/_Dark/01 Primary/Disabled [Tight]",
            "Button/_Dark/01 Primary/Pressed",
            "Button/_Dark/01 Primary/Pressed [Smart]",
            "Button/_Dark/01 Primary/Pressed [Tight]",
            "Button/_Dark/01 Primary/_Default",
            "Button/_Dark/01 Primary/_Default [Smart]",
            "Button/_Dark/01 Primary/Loading [Smart]",
            "Button/_Dark/01 Primary/_Default [Tight]",
            "Button/_Dark/01 Primary/Loading [Tight]",
        ]
    },
    {
        componentName: "CSSecondaryButton",
        names: [
            "Button/__Light/02 Secondary/Loading",
            "Button/__Light/02 Secondary/Disabled",
            "Button/__Light/02 Secondary/Disabled [Smart]",
            "Button/__Light/02 Secondary/Disabled [Tight]",
            "Button/__Light/02 Secondary/Pressed",
            "Button/__Light/02 Secondary/Pressed [Smart]",
            "Button/__Light/02 Secondary/Pressed [Tight]",
            "Button/__Light/02 Secondary/_Default",
            "Button/__Light/02 Secondary/_Default [Smart]",
            "Button/__Light/02 Secondary/Loading [Smart]",
            "Button/__Light/02 Secondary/_Default [Tight]",
            "Button/__Light/02 Secondary/Loading [Tight]",
            "Button/_Dark/02 Secondary/Loading",
            "Button/_Dark/02 Secondary/Disabled",
            "Button/_Dark/02 Secondary/Disabled [Smart]",
            "Button/_Dark/02 Secondary/Disabled [Tight]",
            "Button/_Dark/02 Secondary/Pressed",
            "Button/_Dark/02 Secondary/Pressed [Smart]",
            "Button/_Dark/02 Secondary/Pressed [Tight]",
            "Button/_Dark/02 Secondary/_Default",
            "Button/_Dark/02 Secondary/_Default [Smart]",
            "Button/_Dark/02 Secondary/Loading [Smart]",
            "Button/_Dark/02 Secondary/_Default [Tight]",
            "Button/_Dark/02 Secondary/Loading [Tight]",
        ]
    },
    {
        componentName: "CSTertiaryButton",
        names: [
            "Button/__Light/03 Tertiary/Loading",
            "Button/__Light/03 Tertiary/Disabled",
            "Button/__Light/03 Tertiary/Disabled [Smart]",
            "Button/__Light/03 Tertiary/Disabled [Tight]",
            "Button/__Light/03 Tertiary/Pressed",
            "Button/__Light/03 Tertiary/Pressed [Smart]",
            "Button/__Light/03 Tertiary/Pressed [Tight]",
            "Button/__Light/03 Tertiary/_Default",
            "Button/__Light/03 Tertiary/_Default [Smart]",
            "Button/__Light/03 Tertiary/Loading [Smart]",
            "Button/__Light/03 Tertiary/_Default [Tight]",
            "Button/__Light/03 Tertiary/Loading [Tight]",
            "Button/_Dark/03 Tertiary/Loading",
            "Button/_Dark/03 Tertiary/Disabled",
            "Button/_Dark/03 Tertiary/Disabled [Smart]",
            "Button/_Dark/03 Tertiary/Disabled [Tight]",
            "Button/_Dark/03 Tertiary/Pressed",
            "Button/_Dark/03 Tertiary/Pressed [Smart]",
            "Button/_Dark/03 Tertiary/Pressed [Tight]",
            "Button/_Dark/03 Tertiary/_Default",
            "Button/_Dark/03 Tertiary/_Default [Smart]",
            "Button/_Dark/03 Tertiary/Loading [Smart]",
            "Button/_Dark/03 Tertiary/_Default [Tight]",
            "Button/_Dark/03 Tertiary/Loading [Tight]",
        ]
    },
    {
        componentName: "CSCellTitleDescription",
        names: [
            "Cells/__Light/With icon/Title + Description",
            "Cells/__Light/With icon/Title",
            "Cells/__Light/Text only/Title + Description",
            "Cells/__Light/Text only/Title",
            "Cells/_Dark/Text only/Title + Description",
            "Cells/_Dark/Text only/Title",
            "Cells/_Dark/With icon/Title + Description",
            "Cells/_Dark/With icon/Title",
        ]
    },
    {
        componentName: "CSCellTitleSwitch",
        names: [
            "Cells/_Dark/Action/Switch [Disabled]",
            "Cells/_Dark/Action/Switch",
            "Cells/__Light/Action/Switch [Disabled]",
            "Cells/__Light/Action/Switch",
        ]
    },
    {
        componentName: "CSCellRadioTitle",
        names: [
            "Cells/_Dark/Action/Radio [Disabled]",
            "Cells/_Dark/Action/Radio",
            "Cells/__Light/Action/Radio [Disabled]",
            "Cells/__Light/Action/Radio",
        ]
    },
    {
        componentName: "CSCellHeader",
        names: [
            "Cells/__Light/Heading/Header",
            "Cells/_Dark/Heading/Header",
        ]
    },
    {
        componentName: "CSCellLargeHeader",
        names: [
            "Cells/__Light/Heading/Large Header",
            "Cells/_Dark/Heading/Large Header",
        ]
    },
    {
        componentName: "CSProgressGroup",
        names: [

        ]
    },
    {
        componentName: "CSSwitch",
        names: [
            "Cells/Ω _overrides/Right Accessory/__Light/Switch",
            "Cells/Ω _overrides/Right Accessory/_Dark/Switch",
            "Cells/Ω _overrides/Switch/__Light/_Default",
            "Cells/Ω _overrides/Switch/__Light/_Default [Disabled]",
            "Cells/Ω _overrides/Switch/_Dark/_Default",
            "Cells/Ω _overrides/Switch/_Dark/_Default [Disabled]",
            "Cells/Ω _overrides/Switch/__Light/Checked",
            "Cells/Ω _overrides/Switch/__Light/Checked [Disabled]",
            "Cells/Ω _overrides/Switch/_Dark/Checked",
            "Cells/Ω _overrides/Switch/_Dark/Checked [Disabled]",
        ]
    }
]

export default symbols