const CSiOS_TO_ADD = [
    "Widgets/__Light/Debt overview",
    "Widgets/_Dark/Debt overview",
    "Widgets/__Light/Missed payment",
    "Widgets/_Dark/Missed payment",
    "Widgets/__Light/Report changes",
    "Widgets/_Dark/Report changes",
    "Widgets/🚫 overrides/Calendar/__Light/Payment",
    "Widgets/🚫 overrides/Calendar/_Dark/Payment",
    "Widgets/🚫 overrides/Calendar/__Light/Missed",
    "Widgets/🚫 overrides/Calendar/_Dark/Missed",
    "Widgets/🚫 overrides/Calendar/__Light/No data",
    "Widgets/🚫 overrides/Calendar/_Dark/No data",
    "Widgets/🚫 overrides/Missed payment/Dotted Month/__Light",
    "Widgets/🚫 overrides/Missed payment/Dotted Month/_Dark",
    "Widgets/🚫 overrides/Missed payment/Year/__Light/Active",
    "Widgets/🚫 overrides/Missed payment/Year/_Dark/Active",
    "Widgets/🚫 overrides/Missed payment/Year/__Light/Inactive",
    "Widgets/🚫 overrides/Missed payment/Year/_Dark/Inactive",
    "Widgets/__Light/iPhone 8-/Report Hero/_Default",
    "Widgets/_Dark/iPhone 8-/Report Hero/_Default",
    "Widgets/__Light/iPhone 8-/Report Hero/minimised",
    "Widgets/_Dark/iPhone 8-/Report Hero/minimised",
    "Widgets/__Light/iPhone X+/Report Hero/_Default",
    "Widgets/_Dark/iPhone X+/Report Hero/_Default",
    "Widgets/__Light/iPhone X+/Report Hero/minimised",
    "Widgets/_Dark/iPhone X+/Report Hero/minimised",
    "Widgets/🚫 overrides/Score label",
    "Widgets/🚫 overrides/Score change/Up",
    "Widgets/🚫 overrides/Score change/Down",
    "Text/__Light/Bullet/Primary",
    "Text/_Dark/Bullet/Primary",
    "Text/_Dark/Label + Value/Center",
    "Text/_Dark/Label + Value/Left",
    "Text/_Dark/Label + Value/Right",
    "Text/_Dark/Label + Small value/Center",
    "Text/_Dark/Label + Small value/Left",
    "Text/_Dark/Label + Small value/Right",
    "Text/__Light/Label + Small value/Center",
    "Text/__Light/Label + Small value/Left",
    "Text/__Light/Label + Small value/Right",
    "Text/__Light/Label + Value/Center",
    "Text/__Light/Label + Value/Left",
    "Text/__Light/Label + Value/Right",
    "Text/_Dark/Bullet/Secondary",
    "Text/_Dark/Bullet/Primary Emphasis",
    "Text/__Light/Bullet/Positive Emphasis",
    "Text/_Dark/Bullet/Positive Emphasis",
    "Text/__Light/Bullet/Primary Emphasis",
    "Text/__Light/Bullet/Secondary",
    "Navigation/_Dark/Navigation Bar/_iPhone 8-/_Default",
    "Navigation/__Light/Navigation Bar/_iPhone 8-/_Default",
    "Navigation/_Dark/Navigation Bar/_iPhone 8-/Overlay",
    "Navigation/__Light/Navigation Bar/_iPhone 8-/Overlay",
    "Navigation/_Dark/Navigation Bar/_iPhone X+/_Default",
    "Navigation/__Light/Navigation Bar/_iPhone X+/_Default",
    "Navigation/__Light/Navigation Bar/_iPhone X+/Modal Page",
    "Navigation/_Dark/Navigation Bar/_iPhone X+/Modal Page",
    "Navigation/__Light/Navigation Bar/_iPhone 8-/Modal Page",
    "Navigation/_Dark/Navigation Bar/_iPhone 8-/Modal Page",
    "Navigation/_Dark/Navigation Bar/_iPhone X+/Overlay",
    "Navigation/__Light/Navigation Bar/_iPhone X+/Overlay",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Left Accessory/Back",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Left Accessory/Label",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Left Accessory/Back",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Left Accessory/Label",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Close",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Close",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Label",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Label",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/My Account",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/My Account",
    "Navigation/_Dark/Simple Scrubber/Months",
    "Navigation/__Light/Simple Scrubber/Months",
    "Navigation/_Dark/Simple Scrubber/_Default",
    "Navigation/__Light/Simple Scrubber/_Default",
    "Navigation/__Light/Secondary/Right",
    "Navigation/_Dark/Secondary/Right",
    "Navigation/__Light/Secondary/Left",
    "Navigation/_Dark/Secondary/Left",
    "Navigation/__Light/Secondary/Center",
    "Navigation/_Dark/Secondary/Center",
    "Navigation/🚫 overrides/Secondary/__Light/Active",
    "Navigation/🚫 overrides/Secondary/_Dark/Active",
    "Navigation/🚫 overrides/Secondary/__Light/Default",
    "Navigation/🚫 overrides/Secondary/_Dark/Default",
    "Navigation/__Light/Tab Bar/Dashboard",
    "Navigation/_Dark/Tab Bar/Dashboard",
    "Navigation/__Light/Tab Bar/Timeline",
    "Navigation/_Dark/Tab Bar/Timeline",
    "Navigation/_Dark/Tab Bar/Report",
    "Navigation/_Dark/Tab Bar/Offers",
    "Navigation/_Dark/Tab Bar/Coaching",
    "Navigation/__Light/Tab Bar/Report",
    "Navigation/__Light/Tab Bar/Offers",
    "Navigation/__Light/Tab Bar/Coaching",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Coaching/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/More/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Coaching/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/More/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Coaching/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/More/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Coaching/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/More/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/01 Alpha/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/01 Alpha/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/02 Beta/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/02 Beta/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/03 Gamma/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/03 Gamma/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/04 Delta/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/04 Delta/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/05 Epsilon/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/05 Epsilon/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/01 Alpha/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/01 Alpha/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/02 Beta/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/02 Beta/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/03 Gamma/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/03 Gamma/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/04 Delta/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/04 Delta/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/05 Epsilon/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/05 Epsilon/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Offers/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Protect/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Offers/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Protect/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Offers/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Protect/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Offers/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Protect/Default",
    "Navigation/🚫 overrides/Core/Overlay",
    "Navigation/🚫 overrides/Core/Light",
    "Navigation/🚫 overrides/Core/Dark",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Report/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Report/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Report/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Report/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Timeline/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Timeline/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Timeline/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Timeline/Default",
    "Navigation/__Light/Timeline",
    "Navigation/_Dark/Timeline",
    "Navigation/🚫 overrides/Timeline/__Light/Active",
    "Navigation/🚫 overrides/Timeline/_Dark/Active",
    "Navigation/🚫 overrides/Timeline/__Light/Inactive",
    "Navigation/🚫 overrides/Timeline/_Dark/Inactive",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Description",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Title",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Description",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Title",
    "Navigation/__Light/Navigation Bar/_iPhone X+/Modal Navigation",
    "Navigation/_Dark/Navigation Bar/_iPhone X+/Modal Navigation",
    "Navigation/__Light/Navigation Bar/_iPhone 8-/Modal Navigation",
    "Navigation/_Dark/Navigation Bar/_iPhone 8-/Modal Navigation",
    "Navigation/_Dark/Product Detail/_iPhone X+",
    "Navigation/_Dark/Product Detail/_iPhone 8-",
    "Navigation/__Light/Product Detail/_iPhone X+",
    "Navigation/__Light/Product Detail/_iPhone 8-",
    "Navigation/🚫 overrides/Product Detail/_Dark/Credit Card",
    "Navigation/🚫 overrides/Product Detail/__Light/Credit Card",
    "Navigation/🚫 overrides/Product Detail/_Dark/Logo",
    "Navigation/🚫 overrides/Product Detail/__Light/Logo",
    "Navigation/🚫 overrides/Secondary/__Light/Notification dot",
    "Navigation/🚫 overrides/Secondary/_Dark/Notification dot",
    "Forms/🚫 overrides/Filter options/02 On Dark/03 Scroll",
    "Forms/🚫 overrides/Filter options/01 On Light/03 Scroll",
    "Forms/🚫 overrides/Filter options/02 On Dark/02 Hover",
    "Forms/🚫 overrides/Filter options/01 On Light/02 Hover",
    "Forms/🚫 overrides/Filter options/02 On Dark/01 Default",
    "Forms/🚫 overrides/Filter options/01 On Light/01 Default",
    "Forms/🚫 overrides/Icons/Loading/02 On Dark",
    "Forms/🚫 overrides/Icons/Loading/01 On Light",
    "Forms/🚫 overrides/Icons/Filter/02 On Dark",
    "Forms/🚫 overrides/Icons/Filter/01 On Light",
    "Forms/_Dark/Simple Criteria",
    "Forms/_Dark/Criteria",
    "Forms/_Dark/Simple Disabled",
    "Forms/_Dark/Disabled",
    "Forms/_Dark/Simple",
    "Forms/_Dark/_Default",
    "Forms/__Light/Simple Criteria",
    "Forms/__Light/Criteria",
    "Forms/__Light/Simple Disabled",
    "Forms/__Light/Disabled",
    "Forms/__Light/Simple",
    "Forms/__Light/_Default",
    "Forms/_Dark/☞ Field/Text Area/Disabled",
    "Forms/__Light/☞ Field/Text Area/Disabled",
    "Forms/_Dark/☞ Field/Text Area/Error",
    "Forms/_Dark/☞ Field/Text Area/Warning",
    "Forms/__Light/☞ Field/Text Area/Error",
    "Forms/__Light/☞ Field/Text Area/Warning",
    "Forms/_Dark/☞ Field/Text Area/Success",
    "Forms/_Dark/☞ Field/Text Area/Dirty",
    "Forms/_Dark/☞ Field/Text Area/Active",
    "Forms/_Dark/☞ Field/Text Area/_Default",
    "Forms/__Light/☞ Field/Text Area/Success",
    "Forms/__Light/☞ Field/Text Area/Dirty",
    "Forms/__Light/☞ Field/Text Area/Active",
    "Forms/__Light/☞ Field/Text Area/_Default",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Disabled",
    "Forms/__Light/☞ Field/Input + Prefix + Suffix/Disabled",
    "Forms/_Dark/☞ Field/Input + Suffix/Disabled",
    "Forms/__Light/☞ Field/Input + Suffix/Disabled",
    "Forms/_Dark/☞ Field/Input + Prefix/Disabled",
    "Forms/__Light/☞ Field/Input + Prefix/Disabled",
    "Forms/_Dark/☞ Field/Dropdown/Disabled",
    "Forms/__Light/☞ Field/Dropdown/Disabled",
    "Forms/_Dark/☞ Field/Input/Disabled",
    "Forms/_Dark/☞ Field/Input Filter/Disabled",
    "Forms/__Light/☞ Field/Input/Disabled",
    "Forms/_Dark/☞ Field/Input Filter/Disabled",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Error",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Warning",
    "Forms/__Light/☞ Field/Input + Prefix + Suffix/Error",
    "Forms/__Light/☞ Field/Input + Prefix + Suffix/Warning",
    "Forms/_Dark/☞ Field/Input + Suffix/Error",
    "Forms/_Dark/☞ Field/Input + Suffix/Warning",
    "Forms/__Light/☞ Field/Input + Suffix/Error",
    "Forms/__Light/☞ Field/Input + Suffix/Warning",
    "Forms/_Dark/☞ Field/Input + Prefix/Error",
    "Forms/_Dark/☞ Field/Input + Prefix/Warning",
    "Forms/__Light/☞ Field/Input + Prefix/Error",
    "Forms/__Light/☞ Field/Input + Prefix/Warning",
    "Forms/_Dark/☞ Field/Dropdown/Error",
    "Forms/_Dark/☞ Field/Dropdown/Warning",
    "Forms/__Light/☞ Field/Dropdown/Error",
    "Forms/__Light/☞ Field/Dropdown/Warning",
    "Forms/_Dark/☞ Field/Input/Error",
    "Forms/_Dark/☞ Field/Input Filter/Error",
    "Forms/_Dark/☞ Field/Input/Warning",
    "Forms/_Dark/☞ Field/Input Filter/Warning",
    "Forms/__Light/☞ Field/Input/Error",
    "Forms/_Dark/☞ Field/Input Filter/Error",
    "Forms/__Light/☞ Field/Input/Warning",
    "Forms/_Dark/☞ Field/Input Filter/Warning",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Success",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Dirty",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/Active",
    "Forms/_Dark/☞ Field/Input + Prefix + Suffix/_Default",
    "Forms/__Light/☞ Field/Input + Prefix + Suffix/Success",
    "Forms/__Light/☞ Field/Input + Prefix + Suffix/Dirty",
    "Forms/__Light/☞ Field/Input + Prefix + Suffix/Active",
    "Forms/__Light/☞ Field/Input + Prefix + Suffix/_Default",
    "Forms/_Dark/☞ Field/Input + Suffix/Success",
    "Forms/_Dark/☞ Field/Input + Suffix/Dirty",
    "Forms/_Dark/☞ Field/Input + Suffix/Active",
    "Forms/_Dark/☞ Field/Input + Suffix/_Default",
    "Forms/__Light/☞ Field/Input + Suffix/Success",
    "Forms/__Light/☞ Field/Input + Suffix/Dirty",
    "Forms/__Light/☞ Field/Input + Suffix/Active",
    "Forms/__Light/☞ Field/Input + Suffix/_Default",
    "Forms/_Dark/☞ Field/Input + Prefix/Success",
    "Forms/_Dark/☞ Field/Input + Prefix/Dirty",
    "Forms/_Dark/☞ Field/Input + Prefix/Active",
    "Forms/_Dark/☞ Field/Input + Prefix/_Default",
    "Forms/__Light/☞ Field/Input + Prefix/Success",
    "Forms/__Light/☞ Field/Input + Prefix/Dirty",
    "Forms/__Light/☞ Field/Input + Prefix/Active",
    "Forms/__Light/☞ Field/Input + Prefix/_Default",
    "Forms/_Dark/☞ Field/Dropdown/Success",
    "Forms/_Dark/☞ Field/Dropdown/Dirty",
    "Forms/_Dark/☞ Field/Dropdown/Active",
    "Forms/_Dark/☞ Field/Dropdown/_Default",
    "Forms/__Light/☞ Field/Dropdown/Success",
    "Forms/__Light/☞ Field/Dropdown/Dirty",
    "Forms/__Light/☞ Field/Dropdown/Active",
    "Forms/__Light/☞ Field/Dropdown/_Default",
    "Forms/_Dark/☞ Field/Input/Success",
    "Forms/_Dark/☞ Field/Input Filter/Success",
    "Forms/_Dark/☞ Field/Input/Dirty",
    "Forms/_Dark/☞ Field/Input Filter/Dirty",
    "Forms/_Dark/☞ Field/Input/Active",
    "Forms/_Dark/☞ Field/Input Filter/Active",
    "Forms/_Dark/☞ Field/Input Filter/Loading",
    "Forms/_Dark/☞ Field/Input/_Default",
    "Forms/_Dark/☞ Field/Input Filter/_Default",
    "Forms/__Light/☞ Field/Input/Success",
    "Forms/_Dark/☞ Field/Input Filter/Success",
    "Forms/__Light/☞ Field/Input/Dirty",
    "Forms/_Dark/☞ Field/Input Filter/Dirty",
    "Forms/__Light/☞ Field/Input/Active",
    "Forms/_Dark/☞ Field/Input Filter/Active",
    "Forms/_Dark/☞ Field/Input Filter/Loading",
    "Forms/__Light/☞ Field/Input/_Default",
    "Forms/_Dark/☞ Field/Input Filter/_Default",
    "Forms/🚫 overrides/Criteria/Error/On Dark",
    "Forms/🚫 overrides/Criteria/Error/_On Light",
    "Forms/🚫 overrides/Criteria/Warning/On Dark",
    "Forms/🚫 overrides/Criteria/Warning/_On Light",
    "Forms/🚫 overrides/Container/On Dark/Disabled",
    "Forms/🚫 overrides/Container/On Dark/Error",
    "Forms/🚫 overrides/Container/On Dark/Success",
    "Forms/🚫 overrides/Container/On Dark/Warning",
    "Forms/🚫 overrides/Container/On Dark/Dirty",
    "Forms/🚫 overrides/Container/On Dark/Active",
    "Forms/🚫 overrides/Container/On Dark/Default",
    "Forms/🚫 overrides/Container/_On Light/Disabled",
    "Forms/🚫 overrides/Container/_On Light/Error",
    "Forms/🚫 overrides/Container/_On Light/Success",
    "Forms/🚫 overrides/Container/_On Light/Warning",
    "Forms/🚫 overrides/Container/_On Light/Dirty",
    "Forms/🚫 overrides/Container/_On Light/Active",
    "Forms/🚫 overrides/Container/_On Light/Default",
    "Forms/🚫 overrides/Text Area Drag",
    "Forms/_Label/__Light/Default Disabled",
    "Forms/_Label/_Dark/Default Disabled",
    "Forms/_Label/__Light/Simple Disabled",
    "Forms/_Label/_Dark/Simple Disabled",
    "Forms/_Label/__Light/_Default",
    "Forms/_Label/_Dark/_Default",
    "Forms/_Label/__Light/Simple",
    "Forms/_Label/_Dark/Simple",
    "Forms/__Light/Multi Select/_Default",
    "Forms/_Dark/Multi Select/_Default",
    "Forms/__Light/Multi Select/Active",
    "Forms/_Dark/Multi Select/Active",
    "Donuts/_Tertiary/Start",
    "Donuts/_Tertiary/Continue",
    "Donuts/_Tertiary/Tasks",
    "Donuts/🚫 overrides/Ring/05 Epsilon/101%",
    "Donuts/🚫 overrides/Ring/Small/100%",
    "Donuts/🚫 overrides/Ring/Short Term Debt/100%",
    "Donuts/🚫 overrides/Ring/Long Term Debt/100%",
    "Donuts/🚫 overrides/Ring/01 Alpha/30%",
    "Donuts/🚫 overrides/Ring/Small/30%",
    "Donuts/🚫 overrides/Ring/01 Alpha/25%",
    "Donuts/🚫 overrides/Ring/Small/25%",
    "Donuts/🚫 overrides/Ring/Short Term Debt/25%",
    "Donuts/🚫 overrides/Ring/Long Term Debt/25%",
    "Donuts/🚫 overrides/Ring/01 Alpha/15%",
    "Donuts/🚫 overrides/Ring/Change/Alpha/Up",
    "Donuts/🚫 overrides/Ring/Change/Beta/Up",
    "Donuts/🚫 overrides/Ring/Change/Gamma/Up",
    "Donuts/🚫 overrides/Ring/Change/Delta/Up",
    "Donuts/🚫 overrides/Ring/Change/Epsilon/Up",
    "Donuts/🚫 overrides/Ring/Change/Alpha/Down",
    "Donuts/🚫 overrides/Ring/Change/Alpha/Stable",
    "Donuts/🚫 overrides/Ring/Change/Beta/Down",
    "Donuts/🚫 overrides/Ring/Change/Beta/Stable",
    "Donuts/🚫 overrides/Ring/Change/Gamma/Down",
    "Donuts/🚫 overrides/Ring/Change/Gamma/Stable",
    "Donuts/🚫 overrides/Ring/Change/Delta/Down",
    "Donuts/🚫 overrides/Ring/Change/Delta/Stable",
    "Donuts/🚫 overrides/Ring/Change/Epsilon/Down",
    "Donuts/🚫 overrides/Ring/Change/Epsilon/Stable",
    "Donuts/🚫 overrides/Ring/Small/15%",
    "Donuts/🚫 overrides/Ring/02 Beta/35%",
    "Donuts/🚫 overrides/Ring/Small/35%",
    "Donuts/🚫 overrides/Ring/03 Gamma/50%",
    "Donuts/🚫 overrides/Ring/Small/50%",
    "Donuts/🚫 overrides/Ring/Short Term Debt/50%",
    "Donuts/🚫 overrides/Ring/Long Term Debt/50%",
    "Donuts/🚫 overrides/Ring/02 Beta/40%",
    "Donuts/🚫 overrides/Ring/Small/40%",
    "Donuts/🚫 overrides/Ring/05 Epsilon/85%",
    "Donuts/🚫 overrides/Ring/Small/85%",
    "Donuts/🚫 overrides/Ring/05 Epsilon/75%",
    "Donuts/🚫 overrides/Ring/Small/75%",
    "Donuts/🚫 overrides/Ring/Short Term Debt/75%",
    "Donuts/🚫 overrides/Ring/Long Term Debt/75%",
    "Donuts/🚫 overrides/Ring/04 Delta/70%",
    "Donuts/🚫 overrides/Ring/04 Delta/62%",
    "Donuts/🚫 overrides/Ring/Small/62%",
    "Donuts/🚫 overrides/Ring/03 Gamma/55%",
    "Donuts/🚫 overrides/Ring/Small/55%",
    "Donuts/__Primary/Score/05 Epsilon",
    "Donuts/__Primary/Score/04 Delta",
    "Donuts/__Primary/Score/03 Gamma",
    "Donuts/__Primary/Score/02 Beta",
    "Donuts/__Primary/Score/01 Alpha",
    "Donuts/__Primary/Score/Theta",
    "Donuts/🚫 overrides/Core/_Primary/Score",
    "Donuts/__Primary/Countdown",
    "Donuts/__Primary/Offers/Car Finance",
    "Donuts/__Primary/Offers/Loans",
    "Donuts/__Primary/Offers/Cards",
    "Donuts/🚫 overrides/Core/_Primary/Offers",
    "Donuts/__Primary/Change/Stable",
    "Donuts/__Primary/Change/Down",
    "Donuts/__Primary/Change/Up",
    "Donuts/🚫 overrides/Core/_Primary/Change",
    "Donuts/__Primary/Short Term Debt/Stable",
    "Donuts/__Primary/Short Term Debt/Up",
    "Donuts/__Primary/Short Term Debt/Down",
    "Donuts/🚫 overrides/Core/_Primary/Short Term Debt",
    "Donuts/__Primary/Long Term Debt/Stable",
    "Donuts/__Primary/Long Term Debt/Up",
    "Donuts/__Primary/Long Term Debt/Down",
    "Donuts/🚫 overrides/Core/_Primary/Long Term Debt",
    "Donuts/_Secondary/Default",
    "Donuts/_Secondary/Number",
    "Donuts/_Simple/__Light/Large/01 Alpha",
    "Donuts/_Simple/_Dark/Large/01 Alpha",
    "Donuts/_Simple/__Light/Small/01 Alpha",
    "Donuts/_Simple/__Light/Large/00 Theta",
    "Donuts/_Simple/_Dark/Large/00 Theta",
    "Donuts/_Simple/__Light/Small/00 Theta",
    "Donuts/_Simple/__Light/Large/02 Beta",
    "Donuts/_Simple/_Dark/Large/02 Beta",
    "Donuts/_Simple/__Light/Small/02 Beta",
    "Donuts/_Simple/__Light/Large/03 Gamma",
    "Donuts/_Simple/_Dark/Large/03 Gamma",
    "Donuts/_Simple/__Light/Small/03 Gamma",
    "Donuts/_Simple/__Light/Large/04 Delta",
    "Donuts/_Simple/_Dark/Large/04 Delta",
    "Donuts/_Simple/__Light/Small/04 Delta",
    "Donuts/_Simple/__Light/Large/05 Epsilon",
    "Donuts/_Simple/_Dark/Large/05 Epsilon",
    "Donuts/_Simple/__Light/Small/05 Epsilon",
    "Donuts/_Simple/_Dark/Small/05 Epsilon",
    "Donuts/_Simple/_Dark/Small/04 Delta",
    "Donuts/_Simple/_Dark/Small/03 Gamma",
    "Donuts/_Simple/_Dark/Small/02 Beta",
    "Donuts/_Simple/_Dark/Small/01 Alpha",
    "Donuts/_Simple/_Dark/Small/00 Theta",
    "Donuts/🚫 overrides/Core/Simple/__Light/Small",
    "Donuts/🚫 overrides/Core/Simple/_Dark/Small",
    "Donuts/🚫 overrides/Core/Simple/_Dark/Tiny",
    "Donuts/🚫 overrides/Core/Simple/__Light/Tiny",
    "Donuts/_Simple/Comparison",
    "Donuts/🚫 overrides/Center Text/Secondary",
    "Donuts/🚫 overrides/Center Text/Tertiary",
    "Chat/__Light/Incoming",
    "Chat/_Dark/Incoming",
    "Chat/__Light/Image",
    "Chat/_Dark/Image",
    "Chat/__Light/Writing",
    "Chat/_Dark/Writing",
    "Chat/__Light/Outgoing",
    "Chat/_Dark/Outgoing",
    "Chat/__Light/Not sent",
    "Chat/_Dark/Not sent",
    "Chat/🚫 overrides/__Light/Incoming",
    "Chat/🚫 overrides/_Dark/Incoming",
    "Chat/🚫 overrides/__Light/Outgoing",
    "Chat/🚫 overrides/_Dark/Outgoing",
    "Chat/🚫 overrides/__Light/Not sent",
    "Chat/🚫 overrides/_Dark/Not sent",
    "Cells/🚫 Deprecated/Account/Detail",
    "Cells/🚫 Deprecated/Account/Simple",
    "Cells/_Dark/Button/Center/Destructive",
    "Cells/_Dark/Button/Center/Loading",
    "Cells/_Dark/Button/Center/Disabled",
    "Cells/_Dark/Button/Center/Active",
    "Cells/_Dark/Button/Center/_Default",
    "Cells/__Light/Button/Center/Destructive",
    "Cells/__Light/Button/Center/Loading",
    "Cells/__Light/Button/Center/Disabled",
    "Cells/__Light/Button/Center/Active",
    "Cells/__Light/Button/Center/_Default",
    "Cells/_Dark/Button/Left/Destructive",
    "Cells/_Dark/Button/Left/Loading",
    "Cells/_Dark/Button/Left/Disabled",
    "Cells/_Dark/Button/Left/Active",
    "Cells/_Dark/Button/Left/_Default",
    "Cells/__Light/Button/Left/Destructive",
    "Cells/__Light/Button/Left/Loading",
    "Cells/__Light/Button/Left/Disabled",
    "Cells/__Light/Button/Left/Active",
    "Cells/__Light/Button/Left/_Default",
    "Cells/_Dark/_Base/Button",
    "Cells/__Light/_Base/Button",
    "Cells/🚫 Deprecated/0Heading/Large Header",
    "Cells/__Light/Heading/Large Header",
    "Cells/_Dark/Heading/Large Header",
    "Cells/🚫 Deprecated/Heading/ Header + Overline",
    "Cells/__Light/Heading/Overline + Header",
    "Cells/_Dark/Heading/Overline + Header",
    "Cells/__Light/Heading/Header",
    "Cells/_Dark/Heading/Header",
    "Cells/__Light/With icon/Text + CTA",
    "Cells/_Dark/With icon/Text + CTA",
    "Cells/🚫 Deprecated/Icon + Label + Small Value",
    "Cells/🚫 Deprecated/Icon + Title + Description",
    "Cells/__Light/With icon/Title + Description",
    "Cells/_Dark/With icon/Title + Description",
    "Cells/__Light/With icon/Description + Title",
    "Cells/_Dark/With icon/Description + Title",
    "Cells/__Light/With icon/Title",
    "Cells/_Dark/With icon/Title",
    "Cells/__Light/Text only/Title",
    "Cells/_Dark/Text only/Title",
    "Cells/__Light/Text only/Description + Title",
    "Cells/_Dark/Text only/Description + Title",
    "Cells/__Light/Text only/Title + Description",
    "Cells/_Dark/Text only/Title + Description",
    "Cells/__Light/Action/To-do",
    "Cells/_Dark/Action/To-do",
    "Cells/🚫 Deprecated/Icon + Label + Value",
    "Cells/__Light/With icon/Label + Large Value + Balance",
    "Cells/_Dark/With icon/Label + Large Value + Balance",
    "Cells/🚫 Deprecated/Image + Large Value",
    "Cells/🚫 Deprecated/Label + Big Value",
    "Cells/🚫 Deprecated/Label + Donut",
    "Cells/🚫 Deprecated/Label + Long Value",
    "Cells/__Light/Text only/Label +  Value",
    "Cells/_Dark/Text only/Label +  Value",
    "Cells/🚫 Deprecated/Large Header + Description",
    "Cells/🚫 Deprecated/Large Header + Description + Link",
    "Cells/🚫 Deprecated/New + Icon + Label + Value",
    "Cells/__Light/With icon/Label + Large Value + Balance [New]",
    "Cells/_Dark/With icon/Label + Large Value + Balance [New]",
    "Cells/🚫 Deprecated/New + Label + Big Value",
    "Cells/🚫 Deprecated/New + Label + Long Value",
    "Cells/__Light/Text only/ Value",
    "Cells/_Dark/Text only/ Value",
    "Cells/__Light/Text only/Caption",
    "Cells/_Dark/Text only/Caption",
    "Cells/🚫 Deprecated/_overrides/Account Usage/000",
    "Cells/🚫 Deprecated/_overrides/Account Usage/008",
    "Cells/🚫 Deprecated/_overrides/Account Usage/016",
    "Cells/🚫 Deprecated/_overrides/Account Usage/032",
    "Cells/🚫 Deprecated/_overrides/Account Usage/064",
    "Cells/🚫 Deprecated/_overrides/Account Usage/096",
    "Cells/🚫 Deprecated/_overrides/Account Usage/100",
    "Cells/🚫 overrides/Border/__Light/24pt indent",
    "Cells/🚫 overrides/Border/_Dark/24pt indent",
    "Cells/🚫 overrides/Border/__Light/52pt indent",
    "Cells/🚫 overrides/Border/_Dark/52pt indent",
    "Cells/🚫 overrides/Border/__Light/72pt indent",
    "Cells/🚫 overrides/Border/_Dark/76pt indent",
    "Cells/🚫 overrides/Border/__Light/Full width",
    "Cells/🚫 overrides/Border/_Dark/Full width",
    "Cells/🚫 overrides/Icon/__Light/_Default",
    "Cells/🚫 overrides/Icon/_Dark/_Default",
    "Cells/🚫 overrides/Icon/__Light/Coaching",
    "Cells/🚫 overrides/Icon/_Dark/Coaching",
    "Cells/🚫 overrides/Icon/__Light/Coaching [multiple]",
    "Cells/🚫 overrides/Icon/_Dark/Coaching [multiple]",
    "Cells/🚫 overrides/Checkbox/__Light/Default",
    "Cells/🚫 overrides/Checkbox/_Dark/Default",
    "Cells/🚫 overrides/Checkbox/__Light/Checked",
    "Cells/🚫 overrides/Checkbox/_Dark/Checked",
    "Cells/🚫 overrides/Right Accessory/__Light/Detail",
    "Cells/🚫 overrides/Right Accessory/_Dark/Detail",
    "Cells/🚫 overrides/Right Accessory/__Light/CTA",
    "Cells/🚫 overrides/Right Accessory/_Dark/CTA",
    "Cells/🚫 overrides/Right Accessory/__Light/Tag",
    "Cells/🚫 overrides/Right Accessory/_Dark/Tag",
    "Cells/🚫 overrides/Right Accessory/__Light/Disclosure",
    "Cells/🚫 overrides/Right Accessory/_Dark/Disclosure",
    "Cells/🚫 overrides/Right Accessory/__Light/Disclosure + Detail",
    "Cells/🚫 overrides/Right Accessory/_Dark/Disclosure + Detail",
    "Cells/🚫 overrides/Pill/__Light/Default",
    "Cells/🚫 overrides/Pill/_Dark/Default",
    "Cells/🚫 overrides/Pill/__Light/Negative",
    "Cells/🚫 overrides/Pill/_Dark/Negative",
    "Cells/🚫 overrides/Pill/__Light/Notification",
    "Cells/🚫 overrides/Pill/_Dark/Notification",
    "Cells/🚫 overrides/Pill/__Light/Positive",
    "Cells/🚫 overrides/Pill/_Dark/Positive",
    "Cells/🚫 Deprecated/Label + Value + Description",
    "Cells/__Light/Text only/Label +  Value + Description",
    "Cells/_Dark/Text only/Label +  Value + Description",
    "Cells/__Light/Text only/List",
    "Cells/_Dark/Text only/List",
    "Cells/🚫 overrides/Right Accessory/__Light/Stack",
    "Cells/🚫 overrides/Right Accessory/_Dark/Stack",
    "Cells/__Light/_Base/_Default",
    "Cells/__Light/_Base/Active",
    "Cells/_Dark/_Base/_Default",
    "Cells/_Dark/_Base/Active",
    "Cells/🚫 overrides/List item/_Light",
    "Cells/🚫 overrides/List item/Dark",
    "Cells/🚫 overrides/Tag/__Light/Time",
    "Cells/🚫 overrides/Tag/_Dark/Time",
    "Cells/🚫 overrides/Tag/__Light/Watch",
    "Cells/🚫 overrides/Tag/_Dark/Watch",
    "Cells/🚫 overrides/Tag/__Light/Read",
    "Cells/🚫 overrides/Tag/_Dark/Read",
    "Cells/🚫 overrides/Tag/__Light/_icon",
    "Cells/🚫 overrides/Tag/_Dark/_icon",
    "Cells/🚫 overrides/Right Accessory/__Light/Switch",
    "Cells/🚫 overrides/Right Accessory/_Dark/Switch",
    "Cells/🚫 overrides/Right Accessory/__Light/Radio",
    "Cells/🚫 overrides/Right Accessory/_Dark/Radio",
    "Cells/🚫 overrides/Right Accessory/__Light/Dropdown/Closed",
    "Cells/🚫 overrides/Right Accessory/_Dark/Dropdown/Closed",
    "Cells/🚫 overrides/Right Accessory/__Light/Dropdown/Open",
    "Cells/🚫 overrides/Right Accessory/_Dark/Dropdown/Open",
    "Cells/__Light/Product",
    "Cells/_Dark/Product",
    "Cells/🚫 overrides/Product/__Light/Guaranteed APR",
    "Cells/🚫 overrides/Product/_Dark/Guaranteed APR",
    "Cells/🚫 overrides/Product/__Light/Detail",
    "Cells/🚫 overrides/Product/_Dark/Detail",
    "Cells/__Light/Action/Dropdown",
    "Cells/_Dark/Action/Dropdown",
    "Cells/🚫 overrides/Product/Image",
    "Cells/🚫 overrides/Header accessory/__Light/Number",
    "Cells/🚫 overrides/Header accessory/_Dark/Number",
    "Cells/🚫 overrides/Header accessory/__Light/Help",
    "Cells/🚫 overrides/Header accessory/_Dark/Help",
    "Cells/_Dark/Action/Switch",
    "Cells/_Dark/Action/Radio",
    "Cells/_Dark/Action/Switch [Disabled]",
    "Cells/_Dark/Action/Radio [Disabled]",
    "Forms/🚫 Deprecated/_Field/Switch/On Dark/Warning",
    "Forms/🚫 Deprecated/_Field/Radio/On Dark/Warning",
    "Forms/🚫 Deprecated/_Field/Switch/On Dark/Error",
    "Forms/🚫 Deprecated/_Field/Radio/On Dark/Error",
    "Forms/🚫 Deprecated/_Field/Switch/On Dark/Active",
    "Forms/🚫 Deprecated/_Field/Radio/On Dark/Active",
    "Cells/__Light/Action/Switch",
    "Cells/__Light/Action/Radio",
    "Cells/__Light/Action/Switch [Disabled]",
    "Cells/__Light/Action/Radio [Disabled]",
    "Forms/🚫 Deprecated/_Field/Switch/_On Light/Warning",
    "Forms/🚫 Deprecated/_Field/Radio/_On Light/Warning",
    "Forms/🚫 Deprecated/_Field/Switch/_On Light/Error",
    "Forms/🚫 Deprecated/_Field/Radio/_On Light/Error",
    "Forms/🚫 Deprecated/_Field/Switch/_On Light/Active",
    "Forms/🚫 Deprecated/_Field/Radio/_On Light/Active",
    "Cells/🚫 overrides/Switch/_On Light/_Default",
    "Cells/🚫 overrides/Switch/_On Light/Disabled",
    "Cells/🚫 overrides/Radio/_On Light/_Default",
    "Cells/🚫 overrides/Radio/_On Light/Disabled",
    "Cells/🚫 overrides/Switch/On Dark/_Default",
    "Cells/🚫 overrides/Switch/On Dark/Disabled",
    "Cells/🚫 overrides/Radio/On Dark/_Default",
    "Cells/🚫 overrides/Radio/On Dark/Disabled",
    "Cells/🚫 overrides/Switch/_On Light/Checked",
    "Cells/🚫 overrides/Switch/_On Light/Disabled Checked",
    "Cells/🚫 overrides/Radio/_On Light/Checked",
    "Cells/🚫 overrides/Radio/_On Light/Disabled Checked",
    "Cells/🚫 overrides/Switch/On Dark/Checked",
    "Cells/🚫 overrides/Switch/On Dark/Disabled Checked",
    "Cells/🚫 overrides/Radio/On Dark/Checked",
    "Cells/🚫 overrides/Radio/On Dark/Disabled Checked",
    "Button/_Dark/__Primary/_Default",
    "Button/_Dark/__Primary/_Default [Smart]",
    "Button/_Dark/__Primary/Loading [Smart]",
    "Button/_Dark/__Primary/_Default [Tight]",
    "Button/_Dark/__Primary/Loading [Tight]",
    "Button/_Dark/_Tertiary/_Default",
    "Button/_Dark/_Sticky/_Default",
    "Button/_Dark/_Tertiary/_Default [Smart]",
    "Button/_Dark/_Tertiary/Loading [Smart]",
    "Button/_Dark/_Tertiary/_Default [Tight]",
    "Button/_Dark/_Tertiary/Loading [Tight]",
    "Button/_Dark/__Primary/Active",
    "Button/_Dark/__Primary/Active [Smart]",
    "Button/_Dark/__Primary/Active [Tight]",
    "Button/_Dark/_Tertiary/Active",
    "Button/_Dark/_Sticky/Active",
    "Button/_Dark/_Tertiary/Active [Smart]",
    "Button/_Dark/_Tertiary/Active [Tight]",
    "Button/_Dark/__Primary/Disabled",
    "Button/_Dark/__Primary/Disabled [Smart]",
    "Button/_Dark/__Primary/Disabled [Tight]",
    "Button/_Dark/_Tertiary/Disabled",
    "Button/_Dark/_Sticky/Disabled",
    "Button/_Dark/_Tertiary/Disabled [Smart]",
    "Button/_Dark/_Tertiary/Disabled [Tight]",
    "Button/_Dark/_Secondary/_Default",
    "Button/_Dark/_Secondary/_Default [Smart]",
    "Button/_Dark/_Secondary/Loading [Smart]",
    "Button/_Dark/_Secondary/_Default [Tight]",
    "Button/_Dark/_Secondary/Loading [Tight]",
    "Button/_Dark/_Secondary/Active",
    "Button/_Dark/_Secondary/Active [Smart]",
    "Button/_Dark/_Secondary/Active [Tight]",
    "Button/_Dark/_Secondary/Disabled",
    "Button/_Dark/_Secondary/Disabled [Smart]",
    "Button/_Dark/_Secondary/Disabled [Tight]",
    "Button/__Light/__Primary/_Default",
    "Button/__Light/__Primary/_Default [Smart]",
    "Button/__Light/__Primary/Loading [Smart]",
    "Button/__Light/__Primary/_Default [Tight]",
    "Button/__Light/__Primary/Loading [Tight]",
    "Button/__Light/_Tertiary/_Default",
    "Button/__Light/_Sticky/_Default",
    "Button/__Light/_Tertiary/_Default [Smart]",
    "Button/__Light/_Tertiary/Loading [Smart]",
    "Button/__Light/_Tertiary/_Default [Tight]",
    "Button/__Light/_Tertiary/Loading [Tight]",
    "Button/__Light/__Primary/Active",
    "Button/__Light/__Primary/Active [Smart]",
    "Button/__Light/__Primary/Active [Tight]",
    "Button/🚫 overrides/Loading/Midnight",
    "Button/🚫 overrides/Loading/Chill",
    "Button/🚫 overrides/Loading/White",
    "Button/__Light/_Tertiary/Active",
    "Button/__Light/_Sticky/Active",
    "Button/__Light/_Tertiary/Active [Smart]",
    "Button/__Light/_Tertiary/Active [Tight]",
    "Button/_Dark/__Primary/Loading",
    "Button/_Dark/_Tertiary/Loading",
    "Button/_Dark/_Sticky/Loading",
    "Button/__Light/__Primary/Loading",
    "Button/__Light/_Tertiary/Loading",
    "Button/__Light/_Sticky/Loading",
    "Button/__Light/__Primary/Disabled",
    "Button/__Light/__Primary/Disabled [Smart]",
    "Button/__Light/__Primary/Disabled [Tight]",
    "Button/__Light/_Tertiary/Disabled",
    "Button/__Light/_Sticky/Disabled",
    "Button/__Light/_Tertiary/Disabled [Smart]",
    "Button/__Light/_Tertiary/Disabled [Tight]",
    "Button/__Light/_Secondary/_Default",
    "Button/__Light/_Secondary/_Default [Smart]",
    "Button/__Light/_Secondary/Loading [Smart]",
    "Button/__Light/_Secondary/_Default [Tight]",
    "Button/__Light/_Secondary/Loading [Tight]",
    "Button/__Light/_Secondary/Active",
    "Button/__Light/_Secondary/Active [Smart]",
    "Button/__Light/_Secondary/Active [Tight]",
    "Button/_Dark/_Secondary/Loading",
    "Button/__Light/_Secondary/Loading",
    "Button/__Light/_Secondary/Disabled",
    "Button/__Light/_Secondary/Disabled [Smart]",
    "Button/__Light/_Secondary/Disabled [Tight]",
    "Button/🚫 overrides/Shadow/__Light",
    "Button/🚫 overrides/Shadow/_Dark",
    "_global/__Light/Tag/Outline",
    "_global/_Dark/Tag/Outline",
    "_global/_Dark/Pager/03/03",
    "_global/_Dark/Pager/03/02",
    "_global/_Dark/Pager/03/01",
    "_global/_Dark/Pager/04/04",
    "_global/_Dark/Pager/04/03",
    "_global/_Dark/Pager/04/02",
    "_global/_Dark/Pager/04/01",
    "_global/_Dark/Pager/05/05",
    "_global/_Dark/Pager/05/04",
    "_global/_Dark/Pager/05/03",
    "_global/_Dark/Pager/05/02",
    "_global/_Dark/Pager/05/01",
    "_global/_Dark/Pager/06/06",
    "_global/_Dark/Pager/06/05",
    "_global/_Dark/Pager/06/04",
    "_global/_Dark/Pager/06/03",
    "_global/_Dark/Pager/06/02",
    "_global/_Dark/Pager/06/01",
    "_global/__Light/Pager/03/03",
    "_global/__Light/Pager/03/02",
    "_global/__Light/Pager/03/01",
    "_global/__Light/Pager/04/04",
    "_global/__Light/Pager/04/03",
    "_global/__Light/Pager/04/02",
    "_global/__Light/Pager/04/01",
    "_global/__Light/Pager/05/05",
    "_global/__Light/Pager/05/04",
    "_global/__Light/Pager/05/03",
    "_global/__Light/Pager/05/02",
    "_global/__Light/Pager/05/01",
    "_global/__Light/Pager/06/06",
    "_global/__Light/Pager/06/05",
    "_global/__Light/Pager/06/04",
    "_global/__Light/Pager/06/03",
    "_global/__Light/Pager/06/02",
    "_global/__Light/Pager/06/01",
    "_global/__Light/Notification Dot/__Light",
    "_global/_Dark/Notification Dot/_Dark",
    "_global/__Light/Tag/Smart",
    "_global/_Dark/Tag/Smart",
    "_global/__Light/Pill/Small [Smart]",
    "_global/__Light/Pill/Small [Fixed]",
    "_global/_Dark/Pill/Dark/Small [Smart]",
    "_global/_Dark/Pill/Dark/Small [Fixed]",
    "_global/__Light/Pill/Large [Smart]",
    "_global/__Light/Pill/Large [Fixed]",
    "_global/_Dark/Pill/Dark/Large [Smart]",
    "_global/_Dark/Pill/Dark/Large [Fixed]",
    "_global/__Light/Progress bar/00%",
    "_global/_Dark/Progress bar/00%",
    "_global/__Light/Progress bar/10%",
    "_global/_Dark/Progress bar/10%",
    "_global/__Light/Progress bar/20%",
    "_global/_Dark/Progress bar/20%",
    "_global/__Light/Progress bar/25%",
    "_global/_Dark/Progress bar/25%",
    "_global/__Light/Progress bar/40%",
    "_global/_Dark/Progress bar/40%",
    "_global/__Light/Progress bar/50%",
    "_global/_Dark/Progress bar/50%",
    "_global/__Light/Progress bar/60%",
    "_global/_Dark/Progress bar/60%",
    "_global/__Light/Progress bar/75%",
    "_global/_Dark/Progress bar/75%",
    "_global/__Light/Progress bar/80%",
    "_global/_Dark/Progress bar/80%",
    "_global/__Light/Progress bar/90%",
    "_global/_Dark/Progress bar/90%",
    "_global/__Light/Progress bar/100%",
    "_global/_Dark/Progress bar/100%",
    "_global/__Light/Tag/Fixed",
    "_global/_Dark/Tag/Fixed",
    "_global/__Light/Mega Spinner",
    "_global/_Dark/Mega Spinner",
    "_global/🚫 overrides/Stars/5",
    "_global/🚫 overrides/Stars/4.5",
    "_global/🚫 overrides/Stars/4",
    "_global/🚫 overrides/Stars/3.5",
    "_global/🚫 overrides/Stars/3",
    "_global/🚫 overrides/Stars/2.5",
    "_global/🚫 overrides/Stars/2",
    "_global/🚫 overrides/Stars/1.5",
    "_global/🚫 overrides/Stars/1",
    "_global/🚫 overrides/Stars/0.5",
    "_global/🚫 overrides/Stars/0",
    "_global/__Light/Rating/Stacked",
    "_global/_Dark/Rating/Stacked",
    "_global/__Light/Rating/Inline",
    "_global/_Dark/Rating/Inline",
    "_global/__Light/Approval/Pre-approved",
    "_global/_Dark/Approval/Pre-approved",
    "_global/__Light/Approval/High",
    "_global/_Dark/Approval/High",
    "_global/__Light/Approval/Low",
    "_global/_Dark/Approval/Low",
    "_global/🚫 overrides/Rating #/__Light",
    "_global/🚫 overrides/Rating #/_Dark",
    "Cards/_Account",
    "Cards/__Light/Overline + Value",
    "Cards/_Dark/Overline + Value",
    "Cards/__Light/Label + Title + Description + Label",
    "Cards/_Dark/Label + Title + Description + Label",
    "Cards/🚫 overrides/Status/White",
    "Cards/🚫 overrides/Status/Darken",
    "Cards/🚫 overrides/Status/Lighten",
    "Cards/🚫 overrides/Tags/Off Track",
    "Cards/🚫 overrides/Tags/On Track",
    "Cards/__Light/_Base",
    "Cards/_Dark/_Base",
    "Cards/__Light/Callout",
    "Cards/_Dark/Callout",
    "Cards/__Light/Title + Description",
    "Cards/_Dark/Title + Information",
    "Cards/__Light/Title + Description + CTA",
    "Cards/_Dark/Title + Information + CTA",
    "Cards/__Light/Icon + Title + Progress",
    "Cards/_Dark/Icon + Title + Progress",
    "Cards/__Light/Image + Title",
    "Cards/_Dark/Image + Title",
    "Cards/__Light/Icon + Description",
    "Cards/_Dark/Icon + Description",
    "Cards/__Light/Icon + Title + Description",
    "Cards/_Dark/Icon + Title + Description",
];
