const CSiOS_TO_ADD = [

    "_global/__Light/Notification Dot/__Light",
    "_global/_Dark/Notification Dot/_Dark",
    "_global/__Light/Progress bar/00%",
    "_global/_Dark/Progress bar/00%",
    "_global/__Light/Progress bar/10%",
    "_global/_Dark/Progress bar/10%",
    "_global/__Light/Progress bar/20%",
    "_global/_Dark/Progress bar/20%",
    "_global/__Light/Progress bar/25%",
    "_global/_Dark/Progress bar/25%",
    "_global/__Light/Progress bar/40%",
    "_global/_Dark/Progress bar/40%",
    "_global/__Light/Progress bar/50%",
    "_global/_Dark/Progress bar/50%",
    "_global/__Light/Progress bar/60%",
    "_global/_Dark/Progress bar/60%",
    "_global/__Light/Progress bar/75%",
    "_global/_Dark/Progress bar/75%",
    "_global/__Light/Progress bar/80%",
    "_global/_Dark/Progress bar/80%",
    "_global/__Light/Progress bar/90%",
    "_global/_Dark/Progress bar/90%",
    "_global/__Light/Progress bar/100%",
    "_global/_Dark/Progress bar/100%",
    "_global/__Light/Page help",
    "_global/_Dark/Page help",
    "_global/_Dark/Page help Overlay",
    "_global/Logo header",
    "_global/Icon mask",

    "Button/_Dark/_Sticky/_Default",
    "Button/_Dark/_Sticky/Active",
    "Button/_Dark/_Sticky/Disabled",

    "Button/__Light/_Sticky/_Default",
    "Button/🚫 overrides/Loading/Midnight",
    "Button/🚫 overrides/Loading/Chill",
    "Button/🚫 overrides/Loading/White",
    "Button/__Light/_Sticky/Active",
    "Button/_Dark/_Sticky/Loading",
    "Button/__Light/_Sticky/Loading",
    "Button/__Light/_Sticky/Disabled",
    "Button/🚫 overrides/Shadow/__Light",
    "Button/🚫 overrides/Shadow/_Dark",

    "Cards/Ω _overrides/__Light/Footer",
    "Cards/Ω _overrides/_Dark/Footer",

    "Cards/__Light/Icon + Title + Progress",
    "Cards/_Dark/Icon + Title + Progress",
    "Cards/__Light/Image + Title",
    "Cards/_Dark/Image + Title",
    "Cards/__Light/Icon + Description",
    "Cards/_Dark/Icon + Description",

    "Cards/Ω _overrides/__Light/Account utilisation/Logo",
    "Cards/Ω _overrides/_Dark/Account utilisation/Logo",
    "Cards/Ω _overrides/__Light/Account utilisation/Disclosure",
    "Cards/Ω _overrides/_Dark/Account utilisation/Disclosure",
    "Cards/Ω _overrides/_Dark/Tip message",
    "Cards/Ω _overrides/__Light/Tip message",

    "Cells/_Dark/_Base/Button",
    "Cells/__Light/_Base/Button",

    "Cells/🚫 overrides/Border/__Light/24pt indent",
    "Cells/🚫 overrides/Border/_Dark/24pt indent",
    "Cells/🚫 overrides/Border/__Light/52pt indent",
    "Cells/🚫 overrides/Border/_Dark/52pt indent",
    "Cells/🚫 overrides/Border/__Light/72pt indent",
    "Cells/🚫 overrides/Border/_Dark/76pt indent",
    "Cells/🚫 overrides/Border/__Light/Full width",
    "Cells/🚫 overrides/Border/_Dark/Full width",
    "Cells/🚫 overrides/Icon/__Light/_Default",
    "Cells/🚫 overrides/Icon/_Dark/_Default",
    "Cells/🚫 overrides/Icon/__Light/Coaching",
    "Cells/🚫 overrides/Icon/_Dark/Coaching",
    "Cells/🚫 overrides/Icon/__Light/Coaching [multiple]",
    "Cells/🚫 overrides/Icon/_Dark/Coaching [multiple]",
    "Cells/🚫 overrides/Checkbox/__Light/Default",
    "Cells/🚫 overrides/Checkbox/_Dark/Default",
    "Cells/🚫 overrides/Checkbox/__Light/Checked",
    "Cells/🚫 overrides/Checkbox/_Dark/Checked",
    "Cells/🚫 overrides/Right Accessory/__Light/Detail",
    "Cells/🚫 overrides/Right Accessory/_Dark/Detail",
    "Cells/🚫 overrides/Right Accessory/__Light/CTA",
    "Cells/🚫 overrides/Right Accessory/_Dark/CTA",
    "Cells/🚫 overrides/Right Accessory/__Light/Tag",
    "Cells/🚫 overrides/Right Accessory/_Dark/Tag",
    "Cells/🚫 overrides/Right Accessory/__Light/Disclosure",
    "Cells/🚫 overrides/Right Accessory/_Dark/Disclosure",
    "Cells/🚫 overrides/Right Accessory/__Light/Disclosure + Detail",
    "Cells/🚫 overrides/Right Accessory/_Dark/Disclosure + Detail",
    "Cells/🚫 overrides/Pill/__Light/Default",
    "Cells/🚫 overrides/Pill/_Dark/Default",
    "Cells/🚫 overrides/Pill/__Light/Negative",
    "Cells/🚫 overrides/Pill/_Dark/Negative",
    "Cells/🚫 overrides/Pill/__Light/Notification",
    "Cells/🚫 overrides/Pill/_Dark/Notification",
    "Cells/🚫 overrides/Pill/__Light/Positive",
    "Cells/🚫 overrides/Pill/_Dark/Positive",
    "Cells/🚫 overrides/Right Accessory/__Light/Icon",
    "Cells/🚫 overrides/Right Accessory/_Dark/Icon",
    "Cells/🚫 overrides/List item/_Light",
    "Cells/🚫 overrides/List item/Dark",
    "Cells/🚫 overrides/Tag/__Light/Time",
    "Cells/🚫 overrides/Tag/_Dark/Time",
    "Cells/🚫 overrides/Tag/__Light/Watch",
    "Cells/🚫 overrides/Tag/_Dark/Watch",
    "Cells/🚫 overrides/Tag/__Light/Read",
    "Cells/🚫 overrides/Tag/_Dark/Read",
    "Cells/🚫 overrides/Tag/__Light/_icon",
    "Cells/🚫 overrides/Tag/_Dark/_icon",
    "Cells/🚫 overrides/Right Accessory/__Light/Switch",
    "Cells/🚫 overrides/Right Accessory/_Dark/Switch",
    "Cells/🚫 overrides/Right Accessory/__Light/Radio",
    "Cells/🚫 overrides/Right Accessory/_Dark/Radio",
    "Cells/🚫 overrides/Right Accessory/__Light/Dropdown/Closed",
    "Cells/🚫 overrides/Right Accessory/_Dark/Dropdown/Closed",
    "Cells/🚫 overrides/Right Accessory/__Light/Dropdown/Open",
    "Cells/🚫 overrides/Right Accessory/_Dark/Dropdown/Open",
    "Cells/🚫 overrides/Product/__Light/Guaranteed APR",
    "Cells/🚫 overrides/Product/_Dark/Guaranteed APR",
    "Cells/🚫 overrides/Product/__Light/Detail",
    "Cells/🚫 overrides/Product/_Dark/Detail",
    "Cells/🚫 overrides/Product/Image",
    "Cells/🚫 overrides/Header accessory/__Light/CTA",
    "Cells/🚫 overrides/Header accessory/_Dark/CTA",
    "Cells/🚫 overrides/Switch/_On Light/_Default",
    "Cells/🚫 overrides/Switch/_On Light/Disabled",
    "Cells/🚫 overrides/Radio/_On Light/_Default",
    "Cells/🚫 overrides/Radio/_On Light/Disabled",
    "Cells/🚫 overrides/Switch/On Dark/_Default",
    "Cells/🚫 overrides/Switch/On Dark/Disabled",
    "Cells/🚫 overrides/Radio/On Dark/_Default",
    "Cells/🚫 overrides/Radio/On Dark/Disabled",
    "Cells/🚫 overrides/Switch/_On Light/Checked",
    "Cells/🚫 overrides/Switch/_On Light/Disabled Checked",
    "Cells/🚫 overrides/Radio/_On Light/Checked",
    "Cells/🚫 overrides/Radio/_On Light/Disabled Checked",
    "Cells/🚫 overrides/Switch/On Dark/Checked",
    "Cells/🚫 overrides/Switch/On Dark/Disabled Checked",
    "Cells/🚫 overrides/Radio/On Dark/Checked",
    "Cells/🚫 overrides/Radio/On Dark/Disabled Checked",

    "Forms/🚫 overrides/Filter options/02 On Dark/03 Scroll",
    "Forms/🚫 overrides/Filter options/01 On Light/03 Scroll",
    "Forms/🚫 overrides/Filter options/02 On Dark/02 Hover",
    "Forms/🚫 overrides/Filter options/01 On Light/02 Hover",
    "Forms/🚫 overrides/Filter options/02 On Dark/01 Default",
    "Forms/🚫 overrides/Filter options/01 On Light/01 Default",
    "Forms/🚫 overrides/Icons/Loading/02 On Dark",
    "Forms/🚫 overrides/Icons/Loading/01 On Light",
    "Forms/🚫 overrides/Icons/Filter/02 On Dark",
    "Forms/🚫 overrides/Icons/Filter/01 On Light",


    "Forms/🚫 overrides/Container/On Dark/Disabled",
    "Forms/🚫 overrides/Container/On Dark/Error",
    "Forms/🚫 overrides/Container/On Dark/Success",
    "Forms/🚫 overrides/Container/On Dark/Warning",
    "Forms/🚫 overrides/Container/On Dark/Dirty",
    "Forms/🚫 overrides/Container/On Dark/Active",
    "Forms/🚫 overrides/Container/On Dark/Default",
    "Forms/🚫 overrides/Container/_On Light/Disabled",
    "Forms/🚫 overrides/Container/_On Light/Error",
    "Forms/🚫 overrides/Container/_On Light/Success",
    "Forms/🚫 overrides/Container/_On Light/Warning",
    "Forms/🚫 overrides/Container/_On Light/Dirty",
    "Forms/🚫 overrides/Container/_On Light/Active",
    "Forms/🚫 overrides/Container/_On Light/Default",
    "Forms/🚫 overrides/Text Area Drag",

    "Navigation/🚫 overrides/Navigation Bar/__Light/Left Accessory/Back",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Left Accessory/Label",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Left Accessory/Back",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Left Accessory/Label",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Close",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Close",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Label",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Label",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/My Account",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/My Account",
    "Navigation/🚫 overrides/Secondary/__Light/Active",
    "Navigation/🚫 overrides/Secondary/_Dark/Active",
    "Navigation/🚫 overrides/Secondary/__Light/Default",
    "Navigation/🚫 overrides/Secondary/_Dark/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Coaching/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/More/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Coaching/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/More/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Coaching/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/More/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Coaching/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/More/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/01 Alpha/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/01 Alpha/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/02 Beta/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/02 Beta/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/03 Gamma/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/03 Gamma/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/04 Delta/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/04 Delta/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/05 Epsilon/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/05 Epsilon/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/01 Alpha/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/01 Alpha/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/02 Beta/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/02 Beta/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/03 Gamma/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/03 Gamma/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/04 Delta/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/04 Delta/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/05 Epsilon/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/05 Epsilon/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Offers/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Protect/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Offers/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Protect/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Offers/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Protect/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Offers/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Protect/Default",
    "Navigation/🚫 overrides/Core/Overlay",
    "Navigation/🚫 overrides/Core/Light",
    "Navigation/🚫 overrides/Core/Dark",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Report/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Report/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Report/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Report/Default",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Timeline/Active",
    "Navigation/🚫 overrides/Tab Bar/_Dark/Timeline/Default",
    "Navigation/🚫 overrides/Tab Bar/__Light/Timeline/Active",
    "Navigation/🚫 overrides/Tab Bar/__Light/Timeline/Default",
    "Navigation/__Light/Timeline",
    "Navigation/_Dark/Timeline",
    "Navigation/🚫 overrides/Timeline/__Light/Active",
    "Navigation/🚫 overrides/Timeline/_Dark/Active",
    "Navigation/🚫 overrides/Timeline/__Light/Inactive",
    "Navigation/🚫 overrides/Timeline/_Dark/Inactive",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Description",
    "Navigation/🚫 overrides/Navigation Bar/__Light/Title",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Description",
    "Navigation/🚫 overrides/Navigation Bar/_Dark/Title",
    "Navigation/🚫 overrides/Product Detail/_Dark/Credit Card",
    "Navigation/🚫 overrides/Product Detail/__Light/Credit Card",
    "Navigation/🚫 overrides/Product Detail/_Dark/Logo",
    "Navigation/🚫 overrides/Product Detail/__Light/Logo",
    "Navigation/🚫 overrides/Secondary/__Light/Notification dot",
    "Navigation/🚫 overrides/Secondary/_Dark/Notification dot",
];
