const CSiOS_TO_ADD = [

    "_global/_Dark/Trend/Up",
    "_global/_Dark/Trend/Down",
    "_global/__Light/Trend/Up",
    "_global/__Light/Trend/Down",
    "_global/__Light/Notification Dot/__Light",
    "_global/_Dark/Notification Dot/_Dark",
    "_global/__Light/Page help",
    "_global/_Dark/Page help",
    "_global/_Dark/Page help Overlay",
    "_global/Logo header",
    "_global/Icon mask",
    "_global/__Light/Patterns/Exclusive background",

    "Button/_Dark/_Sticky/_Default",
    "Button/_Dark/_Sticky/Active",
    "Button/_Dark/_Sticky/Disabled",
    "Button/__Light/_Sticky/_Default",
    // OVERRIDE:    "Button/🚫 overrides/Loading/Midnight",
    // OVERRIDE:    "Button/🚫 overrides/Loading/Chill",
    // OVERRIDE:    "Button/🚫 overrides/Loading/White",
    "Button/__Light/_Sticky/Active",
    "Button/_Dark/_Sticky/Loading",
    "Button/__Light/_Sticky/Loading",
    "Button/__Light/_Sticky/Disabled",
    // OVERRIDE:    "Button/🚫 overrides/Shadow/__Light",
    // OVERRIDE:    "Button/🚫 overrides/Shadow/_Dark",

    // OVERRIDE:    "Cards/Ω _overrides/__Light/Footer",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Footer",

    // OVERRIDE:    "Cards/Ω _overrides/Header/_Dark/Icon",
    // OVERRIDE:    "Cards/Ω _overrides/Header/_Dark/Tags",
    // OVERRIDE:    "Cards/Ω _overrides/Header/__Light/Icon",
    // OVERRIDE:    "Cards/Ω _overrides/Header/__Light/Tags",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/CTA",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/CTA",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/Account utilisation/Logo",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Account utilisation/Logo",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/Account utilisation/Disclosure",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Account utilisation/Disclosure",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/Detail + Image/Title",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/Icon + Information/Title",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/Information/Title",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Icon + Information/Title",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Information/Title",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Detail + Image/Title",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/Detail + Image/Description",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/Icon + Information/Description",
    // OVERRIDE:    "Cards/Ω _overrides/__Light/Information/Description",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Icon + Information/Description",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Information/Description",
    // OVERRIDE:    "Cards/Ω _overrides/_Dark/Detail + Image/Description",

    // OVERRIDE:    "Cells/🚫 overrides/Border/__Light/24pt indent",
    // OVERRIDE:    "Cells/🚫 overrides/Border/_Dark/24pt indent",
    // OVERRIDE:    "Cells/🚫 overrides/Border/__Light/52pt indent",
    // OVERRIDE:    "Cells/🚫 overrides/Border/_Dark/52pt indent",
    // OVERRIDE:    "Cells/🚫 overrides/Border/__Light/72pt indent",
    // OVERRIDE:    "Cells/🚫 overrides/Border/_Dark/76pt indent",
    // OVERRIDE:    "Cells/🚫 overrides/Border/__Light/Full width",
    // OVERRIDE:    "Cells/🚫 overrides/Border/_Dark/Full width",
    // OVERRIDE:    "Cells/🚫 overrides/Icon/__Light/_Default",
    // OVERRIDE:    "Cells/🚫 overrides/Icon/_Dark/_Default",
    // OVERRIDE:    "Cells/🚫 overrides/Icon/__Light/Coaching",
    // OVERRIDE:    "Cells/🚫 overrides/Icon/_Dark/Coaching",
    // OVERRIDE:    "Cells/🚫 overrides/Icon/__Light/Coaching [multiple]",
    // OVERRIDE:    "Cells/🚫 overrides/Icon/_Dark/Coaching [multiple]",
    // OVERRIDE:    "Cells/🚫 overrides/Checkbox/__Light/Default",
    // OVERRIDE:    "Cells/🚫 overrides/Checkbox/_Dark/Default",
    // OVERRIDE:    "Cells/🚫 overrides/Checkbox/__Light/Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Checkbox/_Dark/Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Detail",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Detail",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/CTA",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/CTA",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Tag",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Tag",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Disclosure",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Disclosure",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Disclosure + Detail",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Disclosure + Detail",
    // OVERRIDE:    "Cells/🚫 overrides/Pill/__Light/Default",
    // OVERRIDE:    "Cells/🚫 overrides/Pill/_Dark/Default",
    // OVERRIDE:    "Cells/🚫 overrides/Pill/__Light/Negative",
    // OVERRIDE:    "Cells/🚫 overrides/Pill/_Dark/Negative",
    // OVERRIDE:    "Cells/🚫 overrides/Pill/__Light/Notification",
    // OVERRIDE:    "Cells/🚫 overrides/Pill/_Dark/Notification",
    // OVERRIDE:    "Cells/🚫 overrides/Pill/__Light/Positive",
    // OVERRIDE:    "Cells/🚫 overrides/Pill/_Dark/Positive",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Icon",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Icon",
    // OVERRIDE:    "Cells/🚫 overrides/List item/_Light",
    // OVERRIDE:    "Cells/🚫 overrides/List item/Dark",
    // OVERRIDE:    "Cells/🚫 overrides/Tag/__Light/Time",
    // OVERRIDE:    "Cells/🚫 overrides/Tag/_Dark/Time",
    // OVERRIDE:    "Cells/🚫 overrides/Tag/__Light/Watch",
    // OVERRIDE:    "Cells/🚫 overrides/Tag/_Dark/Watch",
    // OVERRIDE:    "Cells/🚫 overrides/Tag/__Light/Read",
    // OVERRIDE:    "Cells/🚫 overrides/Tag/_Dark/Read",
    // OVERRIDE:    "Cells/🚫 overrides/Tag/__Light/_icon",
    // OVERRIDE:    "Cells/🚫 overrides/Tag/_Dark/_icon",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Switch",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Switch",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Radio",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Radio",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Dropdown/Closed",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Dropdown/Closed",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/__Light/Dropdown/Open",
    // OVERRIDE:    "Cells/🚫 overrides/Right Accessory/_Dark/Dropdown/Open",
    // OVERRIDE:    "Cells/🚫 overrides/Product/__Light/Guaranteed APR",
    // OVERRIDE:    "Cells/🚫 overrides/Product/_Dark/Guaranteed APR",
    // OVERRIDE:    "Cells/🚫 overrides/Product/__Light/Detail",
    // OVERRIDE:    "Cells/🚫 overrides/Product/_Dark/Detail",
    // OVERRIDE:    "Cells/🚫 overrides/Product/Image",
    // OVERRIDE:    "Cells/🚫 overrides/Header accessory/__Light/Number",
    // OVERRIDE:    "Cells/🚫 overrides/Header accessory/_Dark/Number",
    // OVERRIDE:    "Cells/🚫 overrides/Header accessory/__Light/Help",
    // OVERRIDE:    "Cells/🚫 overrides/Header accessory/__Light/CTA",
    // OVERRIDE:    "Cells/🚫 overrides/Header accessory/_Dark/CTA",
    // OVERRIDE:    "Cells/🚫 overrides/Header accessory/_Dark/Help",
    // OVERRIDE:    "Cells/🚫 overrides/Switch/_On Light/_Default",
    // OVERRIDE:    "Cells/🚫 overrides/Switch/_On Light/Disabled",
    // OVERRIDE:    "Cells/🚫 overrides/Radio/_On Light/_Default",
    // OVERRIDE:    "Cells/🚫 overrides/Radio/_On Light/Disabled",
    // OVERRIDE:    "Cells/🚫 overrides/Switch/On Dark/_Default",
    // OVERRIDE:    "Cells/🚫 overrides/Switch/On Dark/Disabled",
    // OVERRIDE:    "Cells/🚫 overrides/Radio/On Dark/_Default",
    // OVERRIDE:    "Cells/🚫 overrides/Radio/On Dark/Disabled",
    // OVERRIDE:    "Cells/🚫 overrides/Switch/_On Light/Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Switch/_On Light/Disabled Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Radio/_On Light/Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Radio/_On Light/Disabled Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Switch/On Dark/Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Switch/On Dark/Disabled Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Radio/On Dark/Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Radio/On Dark/Disabled Checked",
    // OVERRIDE:    "Cells/🚫 overrides/Product/__Light/Content",
    // OVERRIDE:    "Cells/🚫 overrides/Product/__Light/Core Product Content",
    // OVERRIDE:    "Cells/🚫 overrides/Product/_Dark/Content",
    // OVERRIDE:    "Cells/🚫 overrides/Product/_Dark/Core Product Content",

    // OVERRIDE:    "Chat/🚫 overrides/__Light/Incoming",
    // OVERRIDE:    "Chat/🚫 overrides/_Dark/Incoming",
    // OVERRIDE:    "Chat/🚫 overrides/__Light/Outgoing",
    // OVERRIDE:    "Chat/🚫 overrides/_Dark/Outgoing",
    // OVERRIDE:    "Chat/🚫 overrides/__Light/Not sent",
    // OVERRIDE:    "Chat/🚫 overrides/_Dark/Not sent",

    // OVERRIDE:    "Donuts/🚫 overrides/Ring/05 Epsilon/101%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/100%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Short Term Debt/100%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Long Term Debt/100%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/01 Alpha/30%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/30%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/01 Alpha/25%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/25%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Short Term Debt/25%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Long Term Debt/25%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/01 Alpha/15%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Alpha/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Beta/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Gamma/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Delta/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Epsilon/Up",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Alpha/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Alpha/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Beta/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Beta/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Gamma/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Gamma/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Delta/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Delta/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Epsilon/Down",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Change/Epsilon/Stable",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/15%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/02 Beta/35%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/35%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/03 Gamma/50%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/50%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Short Term Debt/50%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Long Term Debt/50%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/02 Beta/40%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/40%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/05 Epsilon/85%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/85%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/05 Epsilon/75%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/75%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Short Term Debt/75%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Long Term Debt/75%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/04 Delta/70%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/04 Delta/62%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/62%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/03 Gamma/55%",
    // OVERRIDE:    "Donuts/🚫 overrides/Ring/Small/55%",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/_Primary/Score",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/_Primary/Offers",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/_Primary/Change",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/_Primary/Short Term Debt",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/_Primary/Long Term Debt",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Simple/__Light/Small",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Simple/_Dark/Small",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Simple/_Dark/Tiny",
    // OVERRIDE:    "Donuts/🚫 overrides/Core/Simple/__Light/Tiny",
    // OVERRIDE:    "Donuts/🚫 overrides/Center Text/Secondary",
    // OVERRIDE:    "Donuts/🚫 overrides/Center Text/Tertiary",

    // OVERRIDE:    "Forms/🚫 overrides/Filter options/02 On Dark/03 Scroll",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/01 On Light/03 Scroll",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/02 On Dark/02 Hover",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/01 On Light/02 Hover",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/02 On Dark/01 Default",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/01 On Light/01 Default",
    // OVERRIDE:    "Forms/🚫 overrides/Icons/Loading/02 On Dark",
    // OVERRIDE:    "Forms/🚫 overrides/Icons/Loading/01 On Light",
    // OVERRIDE:    "Forms/🚫 overrides/Icons/Filter/02 On Dark",
    // OVERRIDE:    "Forms/🚫 overrides/Icons/Filter/01 On Light",


    // OVERRIDE:    "Forms/🚫 overrides/Filter options/02 On Dark/03 Scroll",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/01 On Light/03 Scroll",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/02 On Dark/02 Hover",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/01 On Light/02 Hover",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/02 On Dark/01 Default",
    // OVERRIDE:    "Forms/🚫 overrides/Filter options/01 On Light/01 Default",
    // OVERRIDE:    "Forms/🚫 overrides/Icons/Loading/02 On Dark",
    // OVERRIDE:    "Forms/🚫 overrides/Icons/Loading/01 On Light",
    // OVERRIDE:    "Forms/🚫 overrides/Icons/Filter/02 On Dark",
    // OVERRIDE:    "Forms/🚫 overrides/Icons/Filter/01 On Light",
    // OVERRIDE:    "Forms/🚫 overrides/Criteria/Error/On Dark",
    // OVERRIDE:    "Forms/🚫 overrides/Criteria/Error/_On Light",
    // OVERRIDE:    "Forms/🚫 overrides/Criteria/Warning/On Dark",
    // OVERRIDE:    "Forms/🚫 overrides/Criteria/Warning/_On Light",
    // OVERRIDE:    "Forms/🚫 overrides/Container/On Dark/Disabled",
    // OVERRIDE:    "Forms/🚫 overrides/Container/On Dark/Error",
    // OVERRIDE:    "Forms/🚫 overrides/Container/On Dark/Success",
    // OVERRIDE:    "Forms/🚫 overrides/Container/On Dark/Warning",
    // OVERRIDE:    "Forms/🚫 overrides/Container/On Dark/Dirty",
    // OVERRIDE:    "Forms/🚫 overrides/Container/On Dark/Active",
    // OVERRIDE:    "Forms/🚫 overrides/Container/On Dark/Default",
    // OVERRIDE:    "Forms/🚫 overrides/Container/_On Light/Disabled",
    // OVERRIDE:    "Forms/🚫 overrides/Container/_On Light/Error",
    // OVERRIDE:    "Forms/🚫 overrides/Container/_On Light/Success",
    // OVERRIDE:    "Forms/🚫 overrides/Container/_On Light/Warning",
    // OVERRIDE:    "Forms/🚫 overrides/Container/_On Light/Dirty",
    // OVERRIDE:    "Forms/🚫 overrides/Container/_On Light/Active",
    // OVERRIDE:    "Forms/🚫 overrides/Container/_On Light/Default",
    // OVERRIDE:    "Forms/🚫 overrides/Text Area Drag",

    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Label (disabled)",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Label (disabled)",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Tags",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Tags",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Left Accessory/Back",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Left Accessory/Label",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Close",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Label",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Label with icon",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Right Accessory/Icons",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Left Accessory/Back",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Left Accessory/Label",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Close",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Label",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Label with icons",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Right Accessory/Icons",
    // OVERRIDE:    "Navigation/🚫 overrides/Secondary/__Light/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Secondary/_Dark/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Secondary/__Light/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Secondary/_Dark/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Coaching/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/More/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Coaching/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/More/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Coaching/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/More/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Coaching/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/More/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/01 Alpha/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/01 Alpha/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/02 Beta/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/02 Beta/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/03 Gamma/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/03 Gamma/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/04 Delta/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/04 Delta/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/05 Epsilon/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Dashboard/05 Epsilon/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/01 Alpha/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/01 Alpha/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/02 Beta/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/02 Beta/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/03 Gamma/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/03 Gamma/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/04 Delta/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/04 Delta/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/05 Epsilon/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Dashboard/05 Epsilon/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Offers/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Protect/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Offers/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Protect/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Offers/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Protect/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Offers/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Protect/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Core/Overlay",
    // OVERRIDE:    "Navigation/🚫 overrides/Core/Light",
    // OVERRIDE:    "Navigation/🚫 overrides/Core/Dark",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Report/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Report/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Report/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Report/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Timeline/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/_Dark/Timeline/Default",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Timeline/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Tab Bar/__Light/Timeline/Default",
    "Navigation/__Light/Timeline",
    "Navigation/_Dark/Timeline",
    // OVERRIDE:    "Navigation/🚫 overrides/Timeline/__Light/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Timeline/_Dark/Active",
    // OVERRIDE:    "Navigation/🚫 overrides/Timeline/__Light/Inactive",
    // OVERRIDE:    "Navigation/🚫 overrides/Timeline/_Dark/Inactive",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Description",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/__Light/Title",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Description",
    // OVERRIDE:    "Navigation/🚫 overrides/Navigation Bar/_Dark/Title",
    // OVERRIDE:    "Navigation/🚫 overrides/Product Detail/_Dark/Credit Card",
    // OVERRIDE:    "Navigation/🚫 overrides/Product Detail/__Light/Credit Card",
    // OVERRIDE:    "Navigation/🚫 overrides/Product Detail/_Dark/Logo",
    // OVERRIDE:    "Navigation/🚫 overrides/Product Detail/__Light/Logo",
    // OVERRIDE:    "Navigation/🚫 overrides/Secondary/__Light/Notification dot",
    // OVERRIDE:    "Navigation/🚫 overrides/Secondary/_Dark/Notification dot",
    // OVERRIDE:    "Navigation/🚫 overrides/_Dark/Modal/iPhone 8-",
    // OVERRIDE:    "Navigation/🚫 overrides/__Light/Modal/iPhone 8-",
    // OVERRIDE:    "Navigation/🚫 overrides/_Dark/Modal/iPhone X+",
    // OVERRIDE:    "Navigation/🚫 overrides/__Light/Modal/iPhone X+",

    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Rating #/#",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Rating #/#",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Title",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Description",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Binary rating",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Title",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Description",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Binary rating",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Rating #/Center",
    // OVERRIDE:    "Ratings/🚫 overrides/__Light/Rating #/Rating",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Rating #/Center",
    // OVERRIDE:    "Ratings/🚫 overrides/_Dark/Rating #/Rating",
    "Ratings/__Light/Hero + Lender",
    "Ratings/_Dark/Hero",

    // OVERRIDE:    "Text/🚫 overrides/__Light/Title + Description/Description",
    // OVERRIDE:    "Text/🚫 overrides/__Light/Title + Description/Title",
    // OVERRIDE:    "Text/🚫 overrides/_Dark/Title + Description/Description",
    // OVERRIDE:    "Text/🚫 overrides/_Dark/Title + Description/Title",
    // OVERRIDE:    "Text/🚫 overrides/__Light/Title + Description/CTA",
    // OVERRIDE:    "Text/🚫 overrides/_Dark/Title + Description/CTA",

    // OVERRIDE:    "Widgets/🚫 overrides/Report changes/__Light/Header",
    // OVERRIDE:    "Widgets/🚫 overrides/Report changes/_Dark/Header",
    // OVERRIDE:    "Widgets/🚫 overrides/Report changes/__Light/Status",
    // OVERRIDE:    "Widgets/🚫 overrides/Report changes/_Dark/Status",
    // OVERRIDE:    "Widgets/🚫 overrides/Report changes/__Light/Description",
    // OVERRIDE:    "Widgets/🚫 overrides/Report changes/_Dark/Description",
    // OVERRIDE:    "Widgets/🚫 overrides/Calendar/__Light/Payment",
    // OVERRIDE:    "Widgets/🚫 overrides/Calendar/_Dark/Payment",
    // OVERRIDE:    "Widgets/🚫 overrides/Calendar/__Light/Missed",
    // OVERRIDE:    "Widgets/🚫 overrides/Calendar/_Dark/Missed",
    // OVERRIDE:    "Widgets/🚫 overrides/Calendar/__Light/No data",
    // OVERRIDE:    "Widgets/🚫 overrides/Calendar/_Dark/No data",
    // OVERRIDE:    "Widgets/🚫 overrides/Missed payment/Dotted Month/__Light",
    // OVERRIDE:    "Widgets/🚫 overrides/Missed payment/Dotted Month/_Dark",
    // OVERRIDE:    "Widgets/🚫 overrides/Missed payment/Year/__Light/Active",
    // OVERRIDE:    "Widgets/🚫 overrides/Missed payment/Year/_Dark/Active",
    // OVERRIDE:    "Widgets/🚫 overrides/Missed payment/Year/__Light/Inactive",
    // OVERRIDE:    "Widgets/🚫 overrides/Missed payment/Year/_Dark/Inactive",
    // OVERRIDE:    "Widgets/🚫 overrides/Score label",
    // OVERRIDE:    "Widgets/🚫 overrides/Score change/Up",
    // OVERRIDE:    "Widgets/🚫 overrides/Score change/Down",
];
