const CSWeb_TO_ADD = [
	// _global
	"_global/Trend/__Light/Up",
	"_global/Trend/_Dark/Up",
	"_global/Trend/__Light/Down",
	"_global/Trend/_Dark/Down",
	// OVERRIDE:    "_global/AppDownloadBar/_overrides/Content/_Dark/XS-S",
	// OVERRIDE:    "_global/AppDownloadBar/_overrides/Content/_Dark/M-XL",
	// OVERRIDE:    "_global/AppDownloadBar/_overrides/Content/__Light/XS-S",
	// OVERRIDE:    "_global/AppDownloadBar/_overrides/Content/__Light/M-XL",
	// OVERRIDE:    "_global/AppDownloadBar/_overrides/CSLogo/iOS",
	// OVERRIDE:    "_global/AppDownloadBar/_overrides/CSLogo/Android",
	"_global/Full width CTA/04 XS-S",
	"_global/Full width CTA/03 M",
	"_global/Full width CTA/01 XL",
	"_global/Full width CTA/02 L",
	// OVERRIDE:    "_global/Full width CTA/_overrides/Text/02 XS-S",
	// OVERRIDE:    "_global/Full width CTA/_overrides/Text/01 M-XL",
	"_global/Shadow",
	"_global/FTW Pimple",
	"_global/Secure/Light",
	"_global/Secure/Dark",
	"_global/Outline/06 Bottom Rounded",
	"_global/Outline/05 Top Rounded",
	"_global/Outline/04 Right Rounded",
	"_global/Outline/03 Left Rounded",
	"_global/Outline/02 Square",
	"_global/Outline/01 Rounded",
	// OVERRIDE:    "_global/Full width CTA/_overrides/Image",
	"_global/Notch/M",
	"_global/Notch/XS-S",
	"_global/Notch/L",
	"_global/Notch/XL",
	"_global/_Default Image/Logos/Square/Natwest",
	"_global/Tip message/Attention",
	"_global/Tag/Overlay/Lighten [Fixed]",
	"_global/Tag/Overlay/White [Fixed]",
	"_global/Tag/Overlay/Lighten [Smart]",
	"_global/Tag/Overlay/White [Smart]",
	"_global/Tag/Overlay/Darken [Fixed]",
	"_global/Tag/Overlay/Darken [Smart]",
	"_global/Notification Dot/__Light",
	"_global/Notification Dot/_Dark",
	// Accordion
	// OVERRIDE:    "Accordion/🚫 overrides/Theme/_Primary",
	// OVERRIDE:    "Accordion/🚫 overrides/Theme/Secondary",
	// OVERRIDE:    "Accordion/🚫 overrides/Position/_Default [P-XL]",
	// OVERRIDE:    "Accordion/🚫 overrides/Position/_Default [XS-S]",
	// OVERRIDE:    "Accordion/🚫 overrides/Position/Top [P-XL]",
	// OVERRIDE:    "Accordion/🚫 overrides/Position/Top [XS-S]",
	// OVERRIDE:    "Accordion/🚫 overrides/Position/Bottom [P-XL]",
	// OVERRIDE:    "Accordion/🚫 overrides/Position/Bottom [XS-S]",
	// OVERRIDE:    "Accordion/🚫 overrides/Position/Center [P-XL]",
	// OVERRIDE:    "Accordion/🚫 overrides/Position/Center [XS-S]",
	// OVERRIDE:    "Accordion/🚫 overrides/Header type/Closed",
	// OVERRIDE:    "Accordion/🚫 overrides/Header type/Open",
	// OVERRIDE:    "Accordion/🚫 overrides/Layout/Small",
	// OVERRIDE:    "Accordion/🚫 overrides/Layout/Medium",
	// OVERRIDE:    "Accordion/🚫 overrides/Row/Details/Medium",
	// OVERRIDE:    "Accordion/🚫 overrides/Row/Details/Small",
	// OVERRIDE:    "Accordion/🚫 overrides/Row/Information/Medium",
	// OVERRIDE:    "Accordion/🚫 overrides/Row/Information/Small",
	// OVERRIDE:    "Accordion/🚫 overrides/Layout/Large",
	// OVERRIDE:    "Accordion/🚫 overrides/Row/Details/Large",
	// OVERRIDE:    "Accordion/🚫 overrides/Row/Information/Large",
	// OVERRIDE:    "Accordion/🚫 overrides/Icon type/_Default",
	// OVERRIDE:    "Accordion/🚫 overrides/Icon type/Logo",

	// Button
	// OVERRIDE:    "Button/🚫 overrides/02 Loading/04 Dark",
	// OVERRIDE:    "Button/🚫 overrides/02 Loading/02 Link",
	// OVERRIDE:    "Button/🚫 overrides/02 Loading/01 Default",
	// OVERRIDE:    "Button/🚫 overrides/Shadow/01 On Light",
	// OVERRIDE:    "Button/🚫 overrides/Shadow/02 On Dark",

	// Cards
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Info button",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/Info button",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Flag/04 Coming Soon",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Flag/03 Complete",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Flag/02 Active",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Flag/01 Recommended",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Notification",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Notify CTA",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/Footer/XS-S/Tag",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/Header/Icon",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/Footer/M-XL/Button",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/Footer/XS-S/Button",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/Header/Tag",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/Footer/M-XL/Tag",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/Header/Multiple tags",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Footer/XS-S/Tag",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Header/Icon",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Notification",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Flag/04 Coming Soon",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Flag/03 Complete",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Flag/02 Active",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Flag/01 Recommended",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Notify CTA",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Footer/M-XL/Button",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/New",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Header/Tag",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Footer/M-XL/Tag",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Header/Multiple tags",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Footer/XS-S/Button",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Detail/New",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Detail/Footer/Icon action/External link",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/XS-S/🚫 Content/Title",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/XS-S/🚫 Content/Title",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/M-XL/🚫 Content/Title",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/M-XL/🚫 Content/Title",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/XS-S/🚫 Content/Description",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/XS-S/🚫 Content/Description",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/M-XL/🚫 Content/Description",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/M-XL/🚫 Content/Description",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/XS-S/🚫 Content/Link",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/XS-S/🚫 Content/Link",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/M-XL/🚫 Content/Link",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/M-XL/🚫 Content/Link",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/XS-S/_Default",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/XS-S/_Default",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/M-XL/_Default",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/M-XL/Stacked",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/M-XL/_Default",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/M-XL/Stacked",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/M-XL/No icon",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/M-XL/No-icon",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/XS-S/Stacked",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/XS-S/Stacked",
	// OVERRIDE:    "Card/🚫 overrides/__Light/Cross-sell content/XS-S/No icon",
	// OVERRIDE:    "Card/🚫 overrides/_Dark/Cross-sell content/XS-S/No-icon",
	// OVERRIDE:    "Card/🚫 overrides/Image showcase/Landscape/Description",
	// OVERRIDE:    "Card/🚫 overrides/Image showcase/Landscape/Title",
	// OVERRIDE:    "Card/🚫 overrides/Image showcase/Overline",
	// OVERRIDE:    "Card/🚫 overrides/Image showcase/Portrait/Description",
	// OVERRIDE:    "Card/🚫 overrides/Image showcase/Portrait/CTA ",
	// OVERRIDE:    "Card/🚫 overrides/Image showcase/Portrait/Title",

	// Cells
	// OVERRIDE:    "Cell/_overrides/__Light/Right accessory/Accordion/Open",
	// OVERRIDE:    "Cell/_overrides/__Light/Right accessory/Accordion/_default",
	// OVERRIDE:    "Cell/_overrides/__Light/Right accessory/Accordion",
	// OVERRIDE:    "Cell/_overrides/_Dark/Right accessory/Accordion/Open",
	// OVERRIDE:    "Cell/_overrides/_Dark/Right accessory/Accordion/_default",
	// OVERRIDE:    "Cell/_overrides/_Dark/Right accessory/Accordion",
	// OVERRIDE:    "Cell/_overrides/_Dark/Border/Text indent",
	// OVERRIDE:    "Cell/_overrides/_Dark/Border/Full width",
	// OVERRIDE:    "Cell/_overrides/_Dark/Border/Icon indent",
	// OVERRIDE:    "Cell/_overrides/_Dark/Right accessory/Link",
	// OVERRIDE:    "Cell/_overrides/_Dark/Right accessory/Switch",
	// OVERRIDE:    "Cell/_overrides/__Light/Border/Text indent",
	// OVERRIDE:    "Cell/_overrides/__Light/Border/Full width",
	// OVERRIDE:    "Cell/_overrides/__Light/Border/Icon indent",
	// OVERRIDE:    "Cell/_overrides/__Light/Right accessory/Link",
	// OVERRIDE:    "Cell/_overrides/__Light/Right accessory/Switch",

	// Chat

	// OVERRIDE:    "Chat/_overrides/04 Special",
	// OVERRIDE:    "Chat/_overrides/05 Image",
	// OVERRIDE:    "Chat/_overrides/02 Right",
	// OVERRIDE:    "Chat/_overrides/01 Left",

	// Donuts
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/XS-S/Score",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/XS-S/_Default",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/M-XL/Score",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/M-XL/_Default",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/XS-S/Offer",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/M-XL/Offer",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/XS-S/Change",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/M-XL/Change",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/XS-S/Short term debt",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/M-XL/Short-term debt",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/XS-S/Long term debt",
	// OVERRIDE:    "Donuts/_overrides/Core/Primary/M-XL/Long-term debt",
	// OVERRIDE:    "Donuts/_overrides/Core/Secondary/01 XS-S",
	// OVERRIDE:    "Donuts/_overrides/Core/Secondary/02 M-XL",
	// OVERRIDE:    "Donuts/_overrides/Core/Simple/Tiny/On Dark",
	// OVERRIDE:    "Donuts/_overrides/Core/Simple/Tiny/On Light",
	// OVERRIDE:    "Donuts/_overrides/Core/Simple/Medium",
	// OVERRIDE:    "Donuts/_overrides/Core/Simple/Small",
	// OVERRIDE:    "Donuts/_overrides/Core/Simple/Large",

	// Footer
	// OVERRIDE:    "Footer/_overrides/Legal line",
	// OVERRIDE:    "Footer/_overrides/Data Provider",
	// OVERRIDE:    "Footer/_overrides/Data Provider/Equifax",
	// OVERRIDE:    "Footer/_overrides/Data Provider/Experian",
	// OVERRIDE:    "Footer/_overrides/Data Provider/TransUnion",

	// Forms
	// OVERRIDE:    "Form/🚫 overrides/__Light/_ProgressHeader/Description",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/_ProgressHeader/Description",
	// OVERRIDE:    "Form/🚫 overrides/__Light/_ProgressHeader/Title/XS-S",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/_ProgressHeader/Title/XS-S",
	// OVERRIDE:    "Form/🚫 overrides/__Light/_ProgressHeader/Title/M-XL",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/_ProgressHeader/Title/M-XL",
	// OVERRIDE:    "Form/🚫 overrides/__Light/_ProgressHeader/Step",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/_ProgressHeader/Step",
	// ARCHIVED:    "Form/__Light/🚫 Archived/Progress/Steps/XL",
	// ARCHIVED:    "Form/__Light/🚫 Archived/Progress/Steps/L",
	// ARCHIVED:    "Form/__Light/🚫 Archived/Progress/Steps/M",
	// ARCHIVED:    "Form/__Light/🚫 Archived/Progress/Steps/XS-S",
	// OVERRIDE:    "Navigation/🚫 overrides/_Progress/06",
	// OVERRIDE:    "Navigation/🚫 overrides/_Progress/05",
	// OVERRIDE:    "Navigation/🚫 overrides/_Progress/04",
	// OVERRIDE:    "Navigation/🚫 overrides/_Progress/03",
	// OVERRIDE:    "Navigation/🚫 overrides/_Progress/02",
	// ARCHIVED:    "Form/_Dark/🚫 Archived/Progress/Steps/XL",
	// ARCHIVED:    "Form/_Dark/🚫 Archived/Progress/Steps/L",
	// ARCHIVED:    "Form/_Dark/🚫 Archived/Progress/Steps/M",
	// ARCHIVED:    "Form/_Dark/🚫 Archived/Progress/Steps/XS-S",
	// OVERRIDE:    "Navigation/🚫 overrides/_Progress/Step/Complete",
	// OVERRIDE:    "Navigation/🚫 overrides/_Progress/Step/Active",
	// OVERRIDE:    "Navigation/🚫 overrides/_Progress/Step/_default",
	// ARCHIVED:    "Form/🚫 Archived/Slider/_default",

	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Disabled/Center",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Disabled/Right",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Disabled/Left",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Disabled/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Active/Center",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Active/Right",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Active/Left",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Active/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/_Default/Center",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Hover\Focus/Center",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/_Default/Right",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Hover\Focus/Right",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/_Default/Left",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Hover\Focus/Left",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/_Default/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Hover\Focus/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Checkbox/Mobile/_Default",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Checkbox/Mobile/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Checkbox/Mobile/Checked",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Checkbox/Mobile/Checked",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Icons/Warning",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Criteria/Error",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Criteria/Password",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Criteria/Error",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Criteria/Password",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Criteria/Warning",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Criteria/Warning",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/_Default/Disabled",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/_Default/Error",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/_Default/Success",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/_Default/Warning",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/_Default/Dirty",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/_Default/Active",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/__Default/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/_Default/Disabled",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/_Default/Error",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/_Default/Success",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/_Default/Warning",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/_Default/Dirty",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/_Default/Active",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/__Default/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Text Area Drag",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Radio/Desktop/Checked",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Radio/Desktop/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Radio/Desktop/Checked",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Radio/Desktop/_Default",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Checkbox/Desktop/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Checkbox/Desktop/_Default",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Checkbox/Desktop/Checked",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Checkbox/Desktop/Checked",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Filter options/_Options",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Filter options/_Options",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Icons/Cross",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Icons/Loading",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Icons/On Light/Cross",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Icons/On Light/Loading",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Icons/Error",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Icons/Success",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Criteria/Success",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Criteria/Success",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Disabled/Top Left",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Disabled/Top Right",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Active/Top Left",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Active/Top Right",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/_Default/Top Left",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Hover\Focus/Top Left",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/_Default/Top Right",
	// OVERRIDE:    "Form/🚫 overrides/__Light/SegCtrl Position/Hover\Focus/Top Right",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Bottom/Disabled",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Bottom/Disabled",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Top/Disabled",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Top/Disabled",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Center/Disabled",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Center/Disabled",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Bottom/Error",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Bottom/Error",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Top/Error",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Top/Error",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Center/Error",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Center/Error",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Bottom/Success",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Bottom/Success",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Top/Success",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Top/Success",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Center/Success",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Center/Success",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Bottom/Warning",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Bottom/Warning",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Top/Warning",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Top/Warning",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Center/Warning",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Center/Warning",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Bottom/Dirty",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Bottom/Dirty",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Top/Dirty",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Top/Dirty",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Center/Dirty",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Center/Dirty",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Bottom/Active",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Bottom/Active",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Top/Active",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Top/Active",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Center/Active",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Center/Active",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Bottom/_Default",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Bottom/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Top/_Default",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Top/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Container/Center/_Default",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Container/Center/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Filter options/Option/_Default",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Filter options/Option/_Default",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Filter options/Option/Active\Hover",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Filter options/Option/Active\Hover",
	// OVERRIDE:    "Form/🚫 overrides/__Light/Filter options/Scrollbar",
	// OVERRIDE:    "Form/🚫 overrides/_Dark/Filter options/Scrollbar",


	// Navigation

	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/Core/Overlay",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/Core/Light",
	// OVERRIDE:    "Navigation/🚫 overrides/__TabNav/_Template",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/Dashboard/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/Offers/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/Report/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/Protect/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/More/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/Dashboard/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/Offers/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/Report/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/Protect/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Overlay/More/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/Report/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/Protect/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/More/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/Dashboard/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/Offers/_Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/Report/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/Protect/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/More/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/Dashboard/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryTabBar/TabItem/Light/Offers/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/_SecondaryNav/Options/Back",
	// OVERRIDE:    "Navigation/🚫 overrides/_SecondaryNav/Options/Right",
	// OVERRIDE:    "Navigation/🚫 overrides/_SecondaryNav/Options/Center",
	// OVERRIDE:    "Navigation/🚫 overrides/_SecondaryNav/Options/_Left",
	// OVERRIDE:    "Navigation/🚫 overrides/_SecondaryNav/MenuItem/Active",
	// OVERRIDE:    "Navigation/🚫 overrides/_SecondaryNav/MenuItem/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryNav/More/XS-M",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryNav/Options/M-XL",
	// OVERRIDE:    "Navigation/🚫 overrides/Blur Overlay",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryNav/Icon/XS-S",
	// OVERRIDE:    "Navigation/🚫 overrides/_MyAccountMenu/Content",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Build/Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Build/_Default",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Build/Active",
	// OVERRIDE:    "Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Build/_Default",

	// Notifications
	// OVERRIDE:    "Notifications/_overrides/_Dark/Background",
	// OVERRIDE:    "Notifications/_overrides/_Dark/Desktop/With close",
	// OVERRIDE:    "Notifications/_overrides/_Dark/Mobile/With close",
	// OVERRIDE:    "Notifications/_overrides/_Dark/CTA/Text-link [M-XL]",
	// OVERRIDE:    "Notifications/_overrides/_Dark/Icon Left/Success",
	// OVERRIDE:    "Notifications/_overrides/_Dark/Mobile/Text only",
	// OVERRIDE:    "Notifications/_overrides/_Dark/Icon Left/Information",
	// OVERRIDE:    "Notifications/_overrides/_Dark/Close",
	// OVERRIDE:    "Notifications/_overrides/_Dark/CTA/Button + Link[M-XL]",
	// OVERRIDE:    "Notifications/_overrides/_Dark/Icon Left/Attention",
	// OVERRIDE:    "Notifications/_overrides/_Dark/CTA/Button + Link [XS-S]",
	// OVERRIDE:    "Notifications/_overrides/_Dark/CTA/Text-link [XS-S]",
	// OVERRIDE:    "Notifications/_overrides/_Dark/CTA/Text-link left [XS-S]",
	// OVERRIDE:    "Notifications/_overrides/_Dark/Desktop/Text only",
	// OVERRIDE:    "Notifications/_overrides/__Light/Background",
	// OVERRIDE:    "Notifications/_overrides/__Light/Desktop/With close",
	// OVERRIDE:    "Notifications/_overrides/__Light/Mobile/With close",
	// OVERRIDE:    "Notifications/_overrides/__Light/CTA/Text-link [M-XL]",
	// OVERRIDE:    "Notifications/_overrides/__Light/Icon Left/Success",
	// OVERRIDE:    "Notifications/_overrides/__Light/Mobile/Text only",
	// OVERRIDE:    "Notifications/_overrides/__Light/Icon Left/Information",
	// OVERRIDE:    "Notifications/_overrides/__Light/Close",
	// OVERRIDE:    "Notifications/_overrides/__Light/CTA/Button + Link[M-XL]",
	// OVERRIDE:    "Notifications/_overrides/__Light/Icon Left/Attention",
	// OVERRIDE:    "Notifications/_overrides/__Light/CTA/Button + Link [XS-S]",
	// OVERRIDE:    "Notifications/_overrides/__Light/CTA/Text-link [XS-S]",
	// OVERRIDE:    "Notifications/_overrides/__Light/CTA/Text-link left [XS-S]",
	// OVERRIDE:    "Notifications/_overrides/__Light/Desktop/Text only",

	// Product panel
	// OVERRIDE:    "Product/Panel/🚫 overrides/Headers/Credit cards [XS-S]",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Headers/Other [XS-S]",

	// OVERRIDE:    "Product/Panel/🚫 overrides/Labels/Top/XS-S",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Labels/Top/M-XL",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Headers/Credit cards [M]",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Headers/Other [M]",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Headers/Credit cards [L-XL]",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Headers/Other [L-XL]",
	// OVERRIDE:    "Product/Labels/🚫 overrides/Eligibility/Pin/High",
	// OVERRIDE:    "Product/Labels/🚫 overrides/Eligibility/Pin/Low",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Title/M-XL/Inline",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Title/M-XL/Stacked",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Title/XS-S",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Title/Guaranteed/M-XL",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Title/Guaranteed/XS-S",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Title/Title/M-XL",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Title/Title/XS-S",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Rep example",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Properties row/L-XL",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Properties row/M",
	// OVERRIDE:    "Product/Cells/🚫 overrides//Property/Default",
	// OVERRIDE:    "Product/Cells/🚫 overrides//Value/_Default",
	// OVERRIDE:    "Product/Cells/🚫 overrides//Value/Emphasis",
	// OVERRIDE:    "Product/Cells/🚫 overrides//Value/Link",
	// OVERRIDE:    "Product/Cells/🚫 overrides//Property/Emphasis",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Benefits row",
	// OVERRIDE:    "Product/Panel/🚫 overrides/Description",

	// Ratings

	// OVERRIDE:    "Ratings/🚫 overrides/Count/#",
	// OVERRIDE:    "Ratings/🚫 overrides/Count",
	// OVERRIDE:    "Ratings/🚫 overrides/Count/Rating",
	// OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Title",
	// OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Description",
	// OVERRIDE:    "Ratings/🚫 overrides/__Light/Category/Binary rating",
	// OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Title",
	// OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Description",
	// OVERRIDE:    "Ratings/🚫 overrides/_Dark/Category/Binary rating",

	"Ratings/__Light/Hero + Lender/S",
	"Ratings/__Light/Hero + Lender/M-XL",
	"Ratings/_Dark/Hero/S",
	"Ratings/_Dark/Hero/M-XL",

	// Text
	// OVERRIDE:    "Text/SectionTitle/_overrides/_Dark/Description",
	// OVERRIDE:    "Text/SectionTitle/_overrides/_Dark/CTA",

	// OVERRIDE:    "Text/Drawer title/_overrides/_Dark/Description",
	// OVERRIDE:    "Text/Drawer title/_overrides/_Dark/Title/XS-S",
	// OVERRIDE:    "Text/Drawer title/_overrides/_Dark/Title/M-XL",
	// OVERRIDE:    "Text/Drawer title/_overrides/_Dark/Tags",
	// OVERRIDE:    "Text/Drawer title/_overrides/__Light/Description",
	// OVERRIDE:    "Text/Drawer title/_overrides/__Light/Title/XS-S",
	// OVERRIDE:    "Text/Drawer title/_overrides/__Light/Title/M-XL",
	// OVERRIDE:    "Text/Drawer title/_overrides/__Light/Tags",
	"Text/Full-width title/_Dark/Without Description/04 S",
	"Text/Full-width title/_Dark/Without Description/05 XS",
	"Text/Full-width title/_Dark/With Description/04 S",
	"Text/Full-width title/_Dark/With Description/05 XS",
	"Text/List Item with icon/_Dark/01 Default",
	"Text/List Item with icon/_Dark/02 Negative",
	"Text/List Item with icon/_Dark/03 Positive",
	"Text/Puller/02 No CTA/04 XS-S",
	"Text/Puller/02 No CTA/03 M",
	"Text/Puller/02 No CTA/02 L",
	"Text/Puller/02 No CTA/01 XL",
	"Text/Puller/01 With CTA/04 XS-S",
	"Text/Puller/01 With CTA/03 M",
	"Text/Puller/01 With CTA/02 L",
	"Text/Puller/01 With CTA/01 XL",
	"Text/Full-width title/__Light/Without Description/04 S",
	"Text/Full-width title/__Light/Without Description/05 XS",
	"Text/Full-width title/__Light/With Description/04 S",
	"Text/Full-width title/__Light/With Description/05 XS",
	// OVERRIDE:    "Text/Information/_overrides/__Light/Title",
	// OVERRIDE:    "Text/Information/_overrides/_Dark/Title",
	// OVERRIDE:    "Text/Information/_overrides/__Light/Description",
	// OVERRIDE:    "Text/Information/_overrides/_Dark/Description",
	// OVERRIDE:    "Text/Information/_overrides/_Dark/Link",
	// OVERRIDE:    "Text/Information/_overrides/__Light/Link",
	// OVERRIDE:    "Text/SectionTitle/_overrides/__Light/Description",
	// OVERRIDE:    "Text/SectionTitle/_overrides/__Light/CTA",
	// OVERRIDE:    "Text/Value information/_overrides/__Light/Value",
	// OVERRIDE:    "Text/Value information/_overrides/_Dark/Value",
	// OVERRIDE:    "Text/Value information/_overrides/_Dark/Link",
	// OVERRIDE:    "Text/Value information/_overrides/__Light/Link",

	// To-do
	"To-do list/03 Pop-up",
	"To-do list/02 Task-done",
	"To-do list/01 Task/02 XS-S",
	"To-do list/01 Task/01 M-XL",

	// Widgets
	// OVERRIDE:    "Widgets/Payment history/_overrides/No data",
	// OVERRIDE:    "Widgets/Payment history/_overrides/Missed Widgets/Payment",
	// OVERRIDE:    "Widgets/Payment history/_overrides/On time",
	// OVERRIDE:    "Widgets/Payment history/_overrides/Year XS",
	// OVERRIDE:    "Widgets/Payment history/_overrides/Year S",
	// OVERRIDE:    "Widgets/Payment history/_overrides/Year M",
	// OVERRIDE:    "Widgets/Payment history/_overrides/Year L",
	// OVERRIDE:    "Widgets/Payment history/_overrides/Year XL",

	// OVERRIDE:    "Widgets/Time Machine/_overrides/Provider/Experian",
	// OVERRIDE:    "Widgets/Time Machine/_overrides/Provider/Equifax",
	// OVERRIDE:    "Widgets/Time Machine/_overrides/Change/Up",
	// OVERRIDE:    "Widgets/Time Machine/_overrides/Provider/TransUnion",
	// OVERRIDE:    "Widgets/Time Machine/_overrides/Scrubber/XS-S",
	// OVERRIDE:    "Widgets/Time Machine/_overrides/Change/Down",
	// OVERRIDE:    "Widgets/Time Machine/_overrides/Scrubber/M-XL",

];
