const CSWeb_TO_ADD = [
    "_global/Full width CTA/04 XS-S",
    "_global/Full width CTA/03 M",
    "_global/Full width CTA/02 L",
    "_global/Full width CTA/01 XL",
    "_global/Rating/5",
    "_global/Rating/4.5",
    "_global/Rating/4",
    "_global/Rating/3.5",
    "_global/Rating/3",
    "_global/Rating/2.5",
    "_global/Rating/2",
    "_global/Rating/1.5",
    "_global/Rating/1",
    "_global/Rating/0.5",
    "_global/Rating/0",
    "_global/Pager/On Light/03/03",
    "_global/Pager/On Light/03/02",
    "_global/Pager/On Light/03/01",
    "_global/Pager/On Light/04/04",
    "_global/Pager/On Light/04/03",
    "_global/Pager/On Light/04/02",
    "_global/Pager/On Light/04/01",
    "_global/Pager/On Light/05/05",
    "_global/Pager/On Light/05/04",
    "_global/Pager/On Light/05/03",
    "_global/Pager/On Light/05/02",
    "_global/Pager/On Light/05/01",
    "_global/Pager/On Light/06/06",
    "_global/Pager/On Light/06/05",
    "_global/Pager/On Light/06/04",
    "_global/Pager/On Light/06/03",
    "_global/Pager/On Light/06/02",
    "_global/Pager/On Light/06/01",
    "_global/Pager/On Light/07/07",
    "_global/Pager/On Light/07/06",
    "_global/Pager/On Light/07/05",
    "_global/Pager/On Light/07/04",
    "_global/Pager/On Light/07/03",
    "_global/Pager/On Light/07/02",
    "_global/Pager/On Light/07/01",
    "_global/Pager/On Light/08/08",
    "_global/Pager/On Light/08/07",
    "_global/Pager/On Light/08/06",
    "_global/Pager/On Light/08/05",
    "_global/Pager/On Light/08/04",
    "_global/Pager/On Light/08/03",
    "_global/Pager/On Light/08/02",
    "_global/Pager/On Light/08/01",
    "_global/Pager/On Dark/03/03",
    "_global/Pager/On Dark/03/02",
    "_global/Pager/On Dark/03/01",
    "_global/Pager/On Dark/04/04",
    "_global/Pager/On Dark/04/03",
    "_global/Pager/On Dark/04/02",
    "_global/Pager/On Dark/04/01",
    "_global/Pager/On Dark/05/05",
    "_global/Pager/On Dark/05/04",
    "_global/Pager/On Dark/05/03",
    "_global/Pager/On Dark/05/02",
    "_global/Pager/On Dark/05/01",
    "_global/Pager/On Dark/06/06",
    "_global/Pager/On Dark/06/05",
    "_global/Pager/On Dark/06/04",
    "_global/Pager/On Dark/06/03",
    "_global/Pager/On Dark/06/02",
    "_global/Pager/On Dark/06/01",
    "_global/Pager/On Dark/07/07",
    "_global/Pager/On Dark/07/06",
    "_global/Pager/On Dark/07/05",
    "_global/Pager/On Dark/07/04",
    "_global/Pager/On Dark/07/03",
    "_global/Pager/On Dark/07/02",
    "_global/Pager/On Dark/07/01",
    "_global/Pager/On Dark/08/08",
    "_global/Pager/On Dark/08/07",
    "_global/Pager/On Dark/08/06",
    "_global/Pager/On Dark/08/05",
    "_global/Pager/On Dark/08/04",
    "_global/Pager/On Dark/08/03",
    "_global/Pager/On Dark/08/02",
    "_global/Pager/On Dark/08/01",
    "_global/Mega Spinner/Text only",
    "_global/Mega Spinner/With image",
    "Card/__Light/Cross-sell/XS-S",
    "Card/__Light/Cross-sell/M-XL",
    "Card/_Account/XS-S",
    "Card/_Account/M-XL",
    "Card/__Light/Label + Value",
    "Card/__Light/Product Verticals/Large/03 Hover",
    "Card/__Light/Product Verticals/Small/02 Active",
    "Card/__Light/Product Verticals/Small/03 Hover",
    "Card/__Light/Product Verticals/Large/02 Active",
    "Card/__Light/Product Verticals/Small/01 Default",
    "Card/__Light/Product Verticals/Large/01 Default",
    "Card/__Light/Coaching/State 3",
    "Card/__Light/Coaching/State 2",
    "Card/__Light/Coaching/State 1",
    "To-do list/02 Task-done",
    "To-do list/03 Pop-up",
    "To-do list/01 Task/02 XS-S",
    "Icons/06 Coaching/16 Time",
    "Form [deprecated]/Checkbox/_box/Light",
    "Chat/02 Response/3",
    "Chat/01 Message/03 Special",
    "Chat/01 Message/02 User",
    "Chat/01 Message/01 Bot",
    "Form/Multi Select/Hover",
    "Form/Multi Select/Active",
    "Form/Multi Select/_Default",
    "Form/Segmented control/Option/Small/Active",
    "Form/Segmented control/Option/Small/Hover",
    "Form/Segmented control/Option/Small/_default",
    "Form/Segmented control/Option/Large/Active",
    "Form/Segmented control/Option/Large/Hover",
    "Form/Segmented control/Option/Large/_default",
    "Form/Segmented control/Option/Small/Disabled",
    "Form/Segmented control/Option/Large/Disabled",
    "Menu/02 Secondary/04 XS-S/04 No scroll",
    "Menu/02 Secondary/04 XS-S/03 Right aligned",
    "Menu/02 Secondary/04 XS-S/02 Center aligned",
    "Menu/02 Secondary/04 XS-S/01 Left aligned",
    "Menu/02 Secondary/03 M",
    "Menu/02 Secondary/02 L",
    "Menu/02 Secondary/01 XL",
    "Menu/01 Primary/04 XS-S Menu",
    "Menu/01 Primary/04 XS-S Header",
    "Menu/01 Primary/03 M",
    "Menu/01 Primary/02 L",
    "Menu/01 Primary/01 XL",
    "Text/Bullet/__Light/04 With Link",
    "Text/Bullet/__Light/03 Negative",
    "Text/Bullet/__Light/02 Positive",
    "Text/Bullet/__Light/01 Default",
    "Text/List Item with icon/__Light/03 Positive",
    "Text/List Item with icon/__Light/02 Negative",
    "Text/List Item with icon/__Light/01 Default",
    "Text/Popup/_Dark/02 Choice/02 XS-S",
    "Text/Popup/__Light/02 Choice/02 XS-S",
    "Text/Popup/_Dark/02 Choice/01 M-XL",
    "Text/Popup/__Light/02 Choice/01 M-XL",
    "Text/Popup/_Dark/01 Default",
    "Text/Popup/__Light/01 Default",
    "Text/Number/__Light/01 Default",
    "Text/Information/_Dark",
    "Text/Information/__Light",
    "_global/Tag/__Light/_Default [Fixed]",
    "_global/Tag/__Light/Secondary [Fixed]",
    "_global/Tag/__Light/Positive [Fixed]",
    "_global/Tag/__Light/Negative [Fixed]",
    "_global/Tag/Overlay [Darken] [Fixed]",
    "_global/Tag/__Light/_Default [Smart]",
    "_global/Tag/__Light/Secondary [Smart]",
    "_global/Tag/__Light/Positive [Smart]",
    "_global/Tag/__Light/Negative [Smart]",
    "_global/Tag/Overlay [Darken] [Smart]",
    "Text/SectionTitle/XS-S",
    "Text/SectionTitle/M-XL",
    "Text/Puller/01 With CTA/04 XS-S",
    "Text/Puller/01 With CTA/03 M",
    "Text/Puller/01 With CTA/02 L",
    "Text/Puller/01 With CTA/01 XL",
    "Text/Full-width title/__Light/Without Description/04 XS-S/02 Switch",
    "Text/Full-width Title/Without Description/04 XS-S/01 Labels [Deprecated]",
    "Text/Full-width title/__Light/Without Description/03 M",
    "Text/Full-width title/__Light/With Description/03 M",
    "Text/Full-width title/__Light/Without Description/02 L",
    "Text/Full-width title/__Light/With Description/02 L",
    "Text/Full-width title/__Light/Without Description/01 XL",
    "Text/Full-width title/__Light/With Description/01 L-XL",
    "Product Panel/02 M",
    "Product Panel/03 XS-S",
    "Product Panel/06 Car Insurance XS-S",
    "Product Panel/05 Car Insurance M",
    "Product Panel/01 L-XL",
    "Product Panel/09 Mortgages XS-S",
    "Product Panel/08 Mortgages M",
    "Product Panel/07 Mortgages L-XL",
    "Product Panel/04 Car Insurance L-XL",
    "Product Panel/12 Other XS-S",
    "Product Panel/11 Other M",
    "Product Panel/10 Other L-XL",
    "Donuts/Simple/Tiny/Dark/05 Epsilon",
    "Donuts/Simple/Tiny/Light/05 Epsilon",
    "Donuts/Simple/Tiny/Dark/04 Delta",
    "Donuts/Simple/Tiny/Light/04 Delta",
    "Donuts/Simple/Tiny/Dark/03 Gamma",
    "Donuts/Simple/Tiny/Light/03 Gamma",
    "Donuts/Simple/Tiny/Dark/02 Beta",
    "Donuts/Simple/Tiny/Light/02 Beta",
    "Donuts/Simple/Tiny/Dark/01 Alpha",
    "Donuts/Simple/Tiny/Light/01 Alpha",
    "Donuts/Simple/Tiny/Dark/00 Theta",
    "Donuts/Simple/Tiny/Light/00 Theta",
    "Donuts/Simple/Small/05 Epsilon",
    "Donuts/Simple/Small/04 Delta",
    "Donuts/Simple/Small/03 Gamma",
    "Donuts/Simple/Small/02 Beta",
    "Donuts/Simple/Small/01 Alpha",
    "Donuts/Simple/Small/00 Theta",
    "Donuts/Simple/Large/05 Epsilon",
    "Donuts/Simple/Large/04 Delta",
    "Donuts/Simple/Large/03 Gamma",
    "Donuts/Simple/Large/02 Beta",
    "Donuts/Simple/Large/01 Alpha",
    "Donuts/Simple/Large/00 Theta",
    "Donuts/Tertiary/01 XS-S/Tasks",
    "Donuts/Tertiary/02 M-XL/Tasks",
    "Donuts/Tertiary/01 XS-S/Continue",
    "Donuts/Tertiary/02 M-XL/Continue",
    "Donuts/Tertiary/01 XS-S/Start",
    "Donuts/Tertiary/02 M-XL/Start",
    "Donuts/Secondary/01 XS-S/Number",
    "Donuts/Secondary/02 M-XL/Number",
    "Donuts/Secondary/01 XS-S/Default",
    "Donuts/Secondary/02 M-XL/Default",
    "Donuts/Primary/01 XS-S/Countdown",
    "Donuts/Primary/02 M-XL/Countdown",
    "Donuts/Primary/01 XS-S/Offers/Car Finance",
    "Donuts/Primary/02 M-XL/Offers/Car Finance",
    "Donuts/Primary/01 XS-S/Offers/Loans",
    "Donuts/Primary/02 M-XL/Offers/Loans",
    "Donuts/Primary/01 XS-S/Offers/Cards",
    "Donuts/Primary/02 M-XL/Offers/Cards",
    "Donuts/Primary/01 XS-S/Long Term Debt/Down",
    "Donuts/Primary/02 M-XL/Long Term Debt/Down",
    "Donuts/Primary/01 XS-S/Long Term Debt/Up",
    "Donuts/Primary/02 M-XL/Long Term Debt/Up",
    "Donuts/Primary/01 XS-S/Short Term Debt/Down",
    "Donuts/Primary/02 M-XL/Short Term Debt/Down",
    "Donuts/Primary/01 XS-S/Short Term Debt/Up",
    "Donuts/Primary/02 M-XL/Short Term Debt/Up",
    "Donuts/Primary/01 XS-S/Change/Stable",
    "Donuts/Primary/02 M-XL/Change/Stable",
    "Donuts/Primary/01 XS-S/Change/Up",
    "Donuts/Primary/02 M-XL/Change/Up",
    "Donuts/Primary/01 XS-S/Change/Down",
    "Donuts/Primary/02 M-XL/Change/Down",
    "Donuts/Primary/01 XS-S/Score/05 Epsilon",
    "Donuts/Primary/02 M-XL/Score/05 Epsilon",
    "Donuts/Primary/01 XS-S/Score/04 Delta",
    "Donuts/Primary/02 M-XL/Score/04 Delta",
    "Donuts/Primary/01 XS-S/Score/03 Gamma",
    "Donuts/Primary/02 M-XL/Score/03 Gamma",
    "Donuts/Primary/01 XS-S/Score/02 Beta",
    "Donuts/Primary/02 M-XL/Score/02 Beta",
    "Donuts/Primary/01 XS-S/Score/01 Alpha",
    "Donuts/Primary/02 M-XL/Score/01 Alpha",
    "Donuts/Primary/01 XS-S/Score/00 Theta",
    "Donuts/Primary/02 M-XL/Score/00 Theta",
    "Form/Label + Field/_Dark/Simple Password",
    "Form/Label + Field/_Dark/Password",
    "Form/_field/Input/__Light/_Default",
    "Form/Radio Group/01 Mobile/_Dark/Simple",
    "Form/Radio Group/01 Mobile/_Dark/_Default",
    "Form/Radio Group/02 Desktop/_Dark/Simple",
    "Form/Radio Group/02 Desktop/_Dark/_Default",
    "Form/Checkbox Group/01 Mobile/_Dark/Simple",
    "Form/Checkbox Group/01 Mobile/_Dark/_Default",
    "Form/Checkbox Group/02 Desktop/_Dark/Simple",
    "Form/Checkbox Group/02 Desktop/_Dark/_Default",
    "Form/Radio/01 Mobile/_Dark/Compact",
    "Form/Radio/01 Mobile/_Dark/With Description",
    "Form/Radio/01 Mobile/_Dark/_Default",
    "Form/Radio/02 Desktop/_Dark/With Description",
    "Form/Radio/02 Desktop/_Dark/_Default",
    "Form/Checkbox/Switch/_Dark/Compact",
    "Form/Checkbox/Switch/_Dark/With Description",
    "Form/Checkbox/Switch/_Dark/_Default",
    "Form/Checkbox/_Default/_Dark/With Description",
    "Form/Checkbox/_Default/_Dark/_Default",
    "Form/_field/Text Area/_Dark/Warning",
    "Form/_field/Text Area/_Dark/Success",
    "Form/_field/Text Area/_Dark/Error",
    "Form/_field/Text Area/_Dark/Disabled",
    "Form/_field/Text Area/_Dark/Dirty",
    "Form/_field/Text Area/_Dark/Active",
    "Form/_field/Text Area/_Dark/_Default",
    "Form/_field/Input + Prefix + Suffix/_Dark/Warning",
    "Form/_field/Input + Prefix + Suffix/_Dark/Success",
    "Form/_field/Input + Prefix + Suffix/_Dark/Error",
    "Form/_field/Input + Prefix + Suffix/_Dark/Disabled",
    "Form/_field/Input + Prefix + Suffix/_Dark/Dirty",
    "Form/_field/Input + Prefix + Suffix/_Dark/Active",
    "Form/_field/Input + Prefix + Suffix/_Dark/_Default",
    "Form/_field/Input + Suffix/_Dark/Warning",
    "Form/_field/Input + Suffix/_Dark/Success",
    "Form/_field/Input + Suffix/_Dark/Error",
    "Form/_field/Input + Suffix/_Dark/Disabled",
    "Form/_field/Input + Suffix/_Dark/Dirty",
    "Form/_field/Input + Suffix/_Dark/Active",
    "Form/_field/Input + Suffix/_Dark/_Default",
    "Form/_field/Input + Prefix/_Dark/Warning",
    "Form/_field/Input + Prefix/_Dark/Success",
    "Form/_field/Input + Prefix/_Dark/Error",
    "Form/_field/Input + Prefix/_Dark/Disabled",
    "Form/_field/Input + Prefix/_Dark/Dirty",
    "Form/_field/Input + Prefix/_Dark/Active",
    "Form/_field/Input + Prefix/_Dark/_Default",
    "Form/_field/Dropdown/_Dark/Warning",
    "Form/_field/Dropdown/_Dark/Success",
    "Form/_field/Dropdown/_Dark/Error",
    "Form/_field/Dropdown/_Dark/Disabled",
    "Form/_field/Dropdown/_Dark/Dirty",
    "Form/_field/Dropdown/_Dark/Active",
    "Form/_field/Dropdown/_Dark/_Default",
    "Form/_field/Input/_Dark/Warning",
    "Form/_field/Input/_Dark/Success",
    "Form/_field/Input/_Dark/Error",
    "Form/_field/Input/_Dark/Disabled",
    "Form/_field/Input/_Dark/Dirty",
    "Form/_field/Input/_Dark/Active",
    "Form/_field/Input/_Dark/_Default",
    "Form/Label/_Dark/Simple Disabled",
    "Form/Label/_Dark/Default Disabled",
    "Form/Label/_Dark/Simple",
    "Form/Label/_Dark/_Default",
    "Form/Label + Field/_Dark/Simple Criteria",
    "Form/Label + Field/_Dark/Criteria",
    "Form/Label + Field/_Dark/Simple Disabled",
    "Form/Label + Field/_Dark/Disabled",
    "Form/Label + Field/_Dark/Simple",
    "Form/Label + Field/_Dark/_Default",
    "Form/Label + Field/__Light/Simple Password",
    "Form/Label + Field/__Light/Password",
    "Form/Radio Group/01 Mobile/__Light/Simple",
    "Form/Radio Group/01 Mobile/__Light/_Default",
    "Form/Radio Group/02 Desktop/__Light/Simple",
    "Form/Radio Group/02 Desktop/__Light/_Default",
    "Form/Checkbox Group/01 Mobile/__Light/Simple",
    "Form/Checkbox Group/01 Mobile/__Light/_Default",
    "Form/Checkbox Group/02 Desktop/__Light/Simple",
    "Form/Checkbox Group/02 Desktop/__Light/_Default",
    "Form/Radio/01 Mobile/__Light/Compact",
    "Form/Radio/01 Mobile/__Light/With Description",
    "Form/Radio/01 Mobile/__Light/_Default",
    "Form/Radio/02 Desktop/__Light/With Description",
    "Form/Radio/02 Desktop/__Light/_Default",
    "Form/Checkbox/Switch/__Light/Compact",
    "Form/Checkbox/Switch/__Light/With Description",
    "Form/Checkbox/Switch/__Light/_Default",
    "Form/Checkbox/_Default/__Light/With Description",
    "Form/Checkbox/_Default/__Light/_Default",
    "Form/_field/Text Area/__Light/Warning",
    "Form/_field/Text Area/__Light/Success",
    "Form/_field/Text Area/__Light/Error",
    "Form/_field/Text Area/__Light/Disabled",
    "Form/_field/Text Area/__Light/Dirty",
    "Form/_field/Text Area/__Light/Active",
    "Form/_field/Text Area/__Light/_Default",
    "Form/_field/Input + Prefix + Suffix/__Light/Warning",
    "Form/_field/Input + Prefix + Suffix/__Light/Success",
    "Form/_field/Input + Prefix + Suffix/__Light/Error",
    "Form/_field/Input + Prefix + Suffix/__Light/Disabled",
    "Form/_field/Input + Prefix + Suffix/__Light/Dirty",
    "Form/_field/Input + Prefix + Suffix/__Light/Active",
    "Form/_field/Input + Prefix + Suffix/__Light/_Default",
    "Form/_field/Input + Suffix/__Light/Warning",
    "Form/_field/Input + Suffix/__Light/Success",
    "Form/_field/Input + Suffix/__Light/Error",
    "Form/_field/Input + Suffix/__Light/Disabled",
    "Form/_field/Input + Suffix/__Light/Dirty",
    "Form/_field/Input + Suffix/__Light/Active",
    "Form/_field/Input + Suffix/__Light/_Default",
    "Form/_field/Input + Prefix/__Light/Warning",
    "Form/_field/Input + Prefix/__Light/Success",
    "Form/_field/Input + Prefix/__Light/Error",
    "Form/_field/Input + Prefix/__Light/Disabled",
    "Form/_field/Input + Prefix/__Light/Dirty",
    "Form/_field/Input + Prefix/__Light/Active",
    "Form/_field/Input + Prefix/__Light/_Default",
    "Form/_field/Dropdown/__Light/Warning",
    "Form/_field/Dropdown/__Light/Success",
    "Form/_field/Dropdown/__Light/Error",
    "Form/_field/Dropdown/__Light/Disabled",
    "Form/_field/Dropdown/__Light/Dirty",
    "Form/_field/Dropdown/__Light/Active",
    "Form/_field/Dropdown/__Light/_Default",
    "Form/_field/Input/__Light/Warning",
    "Form/_field/Input/__Light/Success",
    "Form/_field/Input/__Light/Error",
    "Form/_field/Input/__Light/Disabled",
    "Form/_field/Input/__Light/Dirty",
    "Form/_field/Input/__Light/Active",
    "Form/Label/__Light/Simple Disabled",
    "Form/Label/__Light/Default Disabled",
    "Form/Label/__Light/Simple",
    "Form/Label/__Light/_Default",
    "Form/Label + Field/__Light/Simple Criteria",
    "Form/Label + Field/__Light/Criteria",
    "Form/Label + Field/__Light/Simple Disabled",
    "Form/Label + Field/__Light/Disabled",
    "Form/Label + Field/__Light/Simple",
    "Form/Label + Field/__Light/_Default",
    "Prompt/__Light/02 M",
    "Prompt/__Light/01 XS-S",
    "Prompt/__Light/03 L",
    "Prompt/__Light/04 XL",
    "Notifications/__Light/XS-S",
    "Notifications/__Light/M-XL",
    "Cell/02 With Icon/03 Description + Title",
    "Cell/02 With Icon/02 Title + Description",
    "Cell/02 With Icon/01 Title",
    "Cell/01 Text only/03 Description + Title",
    "Cell/01 Text only/02 Title + Description",
    "Cell/01 Text only/01 Title"
];
