const symbols = [
	{
		componentName: "⚠️ ProgressHeader",
		names: [
			"Form/__Light/_ProgressHeader/S",
			"Form/_Dark/_ProgressHeader/S",
			"Form/__Light/_ProgressHeader/XS",
			"Form/_Dark/_ProgressHeader/XS",
			"Form/__Light/_ProgressHeader/M",
			"Form/_Dark/_ProgressHeader/M",
			"Form/__Light/_ProgressHeader/L",
			"Form/_Dark/_ProgressHeader/L",
			"Form/__Light/_ProgressHeader/XL",
			"Form/_Dark/_ProgressHeader/XL",
		]
	},
	{
		componentName: "⚠️ TipMessage",
		names: [
			"_global/Tip message/Important",
			"_global/Tip message/_Default",
		]
	},
	{
		componentName: "🌈 Drawer",
		names: [
			"_global/Drawer/_XS-S",
			"_global/Drawer/_Right [M]",
			"_global/Drawer/_Right [L-XL]",
			"_global/Drawer/Bottom [M-XL]",
		]
	},
	{
		componentName: "🌈 MegaLoader",
		names: [
			"_global/Mega Loader/Text only",
			"_global/Mega Loader/With image",
		]
	},
	{
		componentName: "🌈 Accordion",
		names: [
			"Accordion/Header/Text only/Title",
			"Accordion/Header/Text only/Title + Description",
			"Accordion/Header/Text only/Title + Link",
			"Accordion/Header/With icon/Title",
			"Accordion/Header/With icon/Title + Description",
			"Accordion/Header/With icon/Title + Link",
		]
	},
	{
		componentName: "🌈 Accordion.Content",
		names: [
			"Accordion/Content/Small/Details",
			"Accordion/Content/Small/_Layout",
			"Accordion/Content/Medium/Details",
			"Accordion/Content/Medium/_Layout",
			"Accordion/Content/Large/Details",
			"Accordion/Content/Large/_Layout",
			"Accordion/Content/Medium/Information",
			"Accordion/Content/Large/Information",
			"Accordion/Content/Small/Information",
		]
	},
	{
		componentName: "🌈 Autosuggest",
		names: [
			"Form/__Light/☞ Field/Filter options/Active",
			"Form/__Light/☞ Field/Filter options/Dirty",
			"Form/__Light/☞ Field/Filter options/Loading",
			"Form/_Dark/☞ Field/Filter options/Active",
			"Form/_Dark/☞ Field/Filter options/Dirty",
			"Form/_Dark/☞ Field/Filter options/Loading",
		]
	},
	{
		componentName: "🌈 Button: Primary",
		names: [
			"Button/__Primary/Tiny/_Dark/Hover – Active [Smart]",
			"Button/__Primary/Tiny/__Light/Hover – Active [Smart]",
			"Button/__Primary/Tiny/_Dark/Disabled [Smart]",
			"Button/__Primary/Tiny/__Light/Disabled [Smart]",
			"Button/__Primary/Tiny/_Dark/_Default [Smart]",
			"Button/__Primary/Tiny/__Light/_Default [Smart]",
			"Button/__Primary/Small/_Dark/Hover – Active [Smart]",
			"Button/__Primary/Small/__Light/Hover – Active [Smart]",
			"Button/__Primary/Small/_Dark/Disabled [Smart]",
			"Button/__Primary/Small/__Light/Disabled [Smart]",
			"Button/__Primary/Small/_Dark/_Default [Smart]",
			"Button/__Primary/Small/__Light/_Default [Smart]",
			"Button/__Primary/Large/_Dark/Hover – Active [Smart]",
			"Button/__Primary/Large/__Light/Hover – Active [Smart]",
			"Button/__Primary/Large/_Dark/Disabled [Smart]",
			"Button/__Primary/Large/__Light/Disabled [Smart]",
			"Button/__Primary/Large/_Dark/_Default [Smart]",
			"Button/__Primary/Large/__Light/_Default [Smart]",
			"Button/__Primary/Tiny/_Dark/Loading",
			"Button/__Primary/Tiny/_Dark/Hover – Active",
			"Button/__Primary/Tiny/_Dark/Disabled",
			"Button/__Primary/Tiny/_Dark/_Default",
			"Button/__Primary/Small/_Dark/Loading",
			"Button/__Primary/Small/_Dark/Hover – Active",
			"Button/__Primary/Small/_Dark/Disabled",
			"Button/__Primary/Small/_Dark/_Default",
			"Button/__Primary/Large/_Dark/Loading",
			"Button/__Primary/Large/_Dark/Hover – Active",
			"Button/__Primary/Large/_Dark/Disabled",
			"Button/__Primary/Large/_Dark/_Default",
			"Button/__Primary/Tiny/__Light/Loading",
			"Button/__Primary/Tiny/__Light/Hover – Active",
			"Button/__Primary/Tiny/__Light/Disabled",
			"Button/__Primary/Tiny/__Light/_Default",
			"Button/__Primary/Small/__Light/Loading",
			"Button/__Primary/Small/__Light/Hover – Active",
			"Button/__Primary/Small/__Light/Disabled",
			"Button/__Primary/Small/__Light/_Default",
			"Button/__Primary/Large/__Light/Loading",
			"Button/__Primary/Large/__Light/Hover – Active",
			"Button/__Primary/Large/__Light/Disabled",
			"Button/__Primary/Large/__Light/_Default",
		]
	},
	{
		componentName: "🌈 Button: Secondary",
		names: [
			"Button/_Secondary/Large/_Dark/Hover – Active [Smart]",
			"Button/_Secondary/Large/__Light/Hover – Active [Smart]",
			"Button/_Secondary/Large/_Dark/Disabled [Smart]",
			"Button/_Secondary/Large/__Light/Disabled [Smart]",
			"Button/_Secondary/Large/_Dark/_Default [Smart]",
			"Button/_Secondary/Large/__Light/_Default [Smart]",
			"Button/_Secondary/Large/_Dark/Loading",
			"Button/_Secondary/Large/_Dark/Hover – Active",
			"Button/_Secondary/Large/_Dark/Disabled",
			"Button/_Secondary/Large/_Dark/_Default",
			"Button/_Secondary/Large/__Light/Loading",
			"Button/_Secondary/Large/__Light/Hover – Active",
			"Button/_Secondary/Large/__Light/Disabled",
			"Button/_Secondary/Large/__Light/_Default",
			"Button/_Secondary/Small/_Dark/Hover – Active [Smart]",
			"Button/_Secondary/Small/__Light/Hover – Active [Smart]",
			"Button/_Secondary/Small/_Dark/Disabled [Smart]",
			"Button/_Secondary/Small/__Light/Disabled [Smart]",
			"Button/_Secondary/Small/_Dark/_Default [Smart]",
			"Button/_Secondary/Small/__Light/_Default [Smart]",
			"Button/_Secondary/Small/_Dark/Loading",
			"Button/_Secondary/Small/_Dark/Hover – Active",
			"Button/_Secondary/Small/_Dark/Disabled",
			"Button/_Secondary/Small/_Dark/_Default",
			"Button/_Secondary/Small/__Light/Loading",
			"Button/_Secondary/Small/__Light/Hover – Active",
			"Button/_Secondary/Small/__Light/Disabled",
			"Button/_Secondary/Small/__Light/_Default",
			"Button/_Secondary/Tiny/_Dark/Hover – Active [Smart]",
			"Button/_Secondary/Tiny/__Light/Hover – Active [Smart]",
			"Button/_Secondary/Tiny/_Dark/Disabled [Smart]",
			"Button/_Secondary/Tiny/__Light/Disabled [Smart]",
			"Button/_Secondary/Tiny/_Dark/_Default [Smart]",
			"Button/_Secondary/Tiny/__Light/_Default [Smart]",
			"Button/_Secondary/Tiny/_Dark/Loading",
			"Button/_Secondary/Tiny/_Dark/Hover – Active",
			"Button/_Secondary/Tiny/_Dark/Disabled",
			"Button/_Secondary/Tiny/_Dark/_Default",
			"Button/_Secondary/Tiny/__Light/Loading",
			"Button/_Secondary/Tiny/__Light/Hover – Active",
			"Button/_Secondary/Tiny/__Light/Disabled",
			"Button/_Secondary/Tiny/__Light/_Default",
		]
	},
	{
		componentName: "🌈 Button: Tertiary",
		names: [
			"Button/_Tertiary/Large/_Dark/Loading",
			"Button/_Tertiary/Large/_Dark/Hover – Active [Smart]",
			"Button/_Tertiary/Large/__Light/Hover – Active [Smart]",
			"Button/_Tertiary/Large/_Dark/Disabled [Smart]",
			"Button/_Tertiary/Large/__Light/Disabled [Smart]",
			"Button/_Tertiary/Large/_Dark/_Default [Smart]",
			"Button/_Tertiary/Large/__Light/_Default [Smart]",
			"Button/_Tertiary/Large/_Dark/Hover – Active",
			"Button/_Tertiary/Large/_Dark/Disabled",
			"Button/_Tertiary/Large/_Dark/_Default",
			"Button/_Tertiary/Large/__Light/Loading",
			"Button/_Tertiary/Large/__Light/Hover – Active",
			"Button/_Tertiary/Large/__Light/Disabled",
			"Button/_Tertiary/Large/__Light/_Default",
			"Button/_Tertiary/Large/_Dark/Loading",
			"Button/_Tertiary/Large/_Dark/Hover – Active [Smart]",
			"Button/_Tertiary/Large/__Light/Hover – Active [Smart]",
			"Button/_Tertiary/Large/_Dark/Disabled [Smart]",
			"Button/_Tertiary/Large/__Light/Disabled [Smart]",
			"Button/_Tertiary/Large/_Dark/_Default [Smart]",
			"Button/_Tertiary/Large/__Light/_Default [Smart]",
			"Button/_Tertiary/Large/_Dark/Hover – Active",
			"Button/_Tertiary/Large/_Dark/Disabled",
			"Button/_Tertiary/Large/_Dark/_Default",
			"Button/_Tertiary/Large/__Light/Loading",
			"Button/_Tertiary/Large/__Light/Hover – Active",
			"Button/_Tertiary/Large/__Light/Disabled",
			"Button/_Tertiary/Large/__Light/_Default",
			"Button/_Tertiary/Small/_Dark/Hover – Active [Smart]",
			"Button/_Tertiary/Small/__Light/Hover – Active [Smart]",
			"Button/_Tertiary/Small/_Dark/Disabled [Smart]",
			"Button/_Tertiary/Small/__Light/Disabled [Smart]",
			"Button/_Tertiary/Small/_Dark/_Default [Smart]",
			"Button/_Tertiary/Small/__Light/_Default [Smart]",
			"Button/_Tertiary/Small/_Dark/Loading",
			"Button/_Tertiary/Small/_Dark/Hover – Active",
			"Button/_Tertiary/Small/_Dark/Disabled",
			"Button/_Tertiary/Small/_Dark/_Default",
			"Button/_Tertiary/Small/__Light/Loading",
			"Button/_Tertiary/Small/__Light/Hover – Active",
			"Button/_Tertiary/Small/__Light/Disabled",
			"Button/_Tertiary/Small/__Light/_Default",
			"Button/_Tertiary/Small/_Dark/Hover – Active [Smart]",
			"Button/_Tertiary/Small/__Light/Hover – Active [Smart]",
			"Button/_Tertiary/Small/_Dark/Disabled [Smart]",
			"Button/_Tertiary/Small/__Light/Disabled [Smart]",
			"Button/_Tertiary/Small/_Dark/_Default [Smart]",
			"Button/_Tertiary/Small/__Light/_Default [Smart]",
			"Button/_Tertiary/Small/_Dark/Loading",
			"Button/_Tertiary/Small/_Dark/Hover – Active",
			"Button/_Tertiary/Small/_Dark/Disabled",
			"Button/_Tertiary/Small/_Dark/_Default",
			"Button/_Tertiary/Small/__Light/Loading",
			"Button/_Tertiary/Small/__Light/Hover – Active",
			"Button/_Tertiary/Small/__Light/Disabled",
			"Button/_Tertiary/Small/__Light/_Default",
			"Button/_Tertiary/Tiny/_Dark/Hover – Active [Smart]",
			"Button/_Tertiary/Tiny/__Light/Hover – Active [Smart]",
			"Button/_Tertiary/Tiny/_Dark/Disabled [Smart]",
			"Button/_Tertiary/Tiny/__Light/Disabled [Smart]",
			"Button/_Tertiary/Tiny/_Dark/_Default [Smart]",
			"Button/_Tertiary/Tiny/__Light/_Default [Smart]",
			"Button/_Tertiary/Tiny/_Dark/Loading",
			"Button/_Tertiary/Tiny/_Dark/Hover – Active",
			"Button/_Tertiary/Tiny/_Dark/Disabled",
			"Button/_Tertiary/Tiny/_Dark/_Default",
			"Button/_Tertiary/Tiny/__Light/Loading",
			"Button/_Tertiary/Tiny/__Light/Hover – Active",
			"Button/_Tertiary/Tiny/__Light/Disabled",
			"Button/_Tertiary/Tiny/__Light/_Default",
		]
	},
	{
		componentName: "🌈 Button: Sticky",
		names: [
			"Button/_Sticky/01 Default",
			"Button/_Sticky/02 Hover – Active",
			"Button/_Sticky/04 Disabled",
			"Button/_Sticky/03 Loading",
		]
	},
	{
		componentName: "🌈 Card",
		names: [
			"Card/__Light/_Base",
			"Card/_Dark/_Base",
			"Card/__Light/_Base [Dismissable]",
			"Card/_Dark/_Base [Dismissable]",
		]
	},
	{
		componentName: "🌈 CardDetails",
		names: [
			"Card/__Light/Detail/M-XL/_Default",
			"Card/__Light/Detail/M-XL/With icon",
			"Card/__Light/Detail/M-XL/With image",
			"Card/_Dark/Detail/M-XL/_Default",
			"Card/_Dark/Detail/M-XL/With icon",
			"Card/_Dark/Detail/M-XL/With image",
			"Card/__Light/Detail/XS-S/_Default",
			"Card/__Light/Detail/XS-S/With icon",
			"Card/__Light/Detail/XS-S/With image",
			"Card/_Dark/Detail/XS-S/_Default",
			"Card/_Dark/Detail/XS-S/With icon",
			"Card/_Dark/Detail/XS-S/With image"
		]
	},
	{
		componentName: "⚠️ CardValueInformation",
		names: [
			"Card/__Light/Value Information/XS-S",
			"Card/__Light/Value Information/M-XL",
			"Card/_Dark/Value Information/XS-S",
			"Card/_Dark/Value Information/M-XL",
		]
	},
	{
		componentName: "⚠️ CardInformation",
		names: [
			"Card/__Light/Information/XS-S",
			"Card/_Dark/Information/XS-S",
			"Card/_Dark/Information/M-XL",
			"Card/__Light/Information/M-XL",
		]
	},
	{
		componentName: "⚠️ CardAccount",
		names: [
			"Card/_Account/M-XL",
			"Card/_Account/XS-S",
		]
	},
	{
		componentName: "⚠️ CardCrossSell",
		names: [
			"Card/_Dark/Cross-sell/M-XL",
			"Card/_Dark/Cross-sell/XS-S",
			"Card/__Light/Cross-sell/XS-S",
			"Card/__Light/Cross-sell/M-XL",
		]
	},
	{
		componentName: "⚠️ Cell",
		names: [
			"Cell/__Light/01 Text only/01 Title",
			"Cell/__Light/01 Text only/02 Title + Description",
			"Cell/__Light/01 Text only/03 Description + Title",
			"Cell/__Light/02 With Icon/01 Title",
			"Cell/__Light/02 With Icon/02 Title + Description",
			"Cell/__Light/02 With Icon/03 Description + Title",
			"Cell/_Dark/01 Text only/01 Title",
			"Cell/_Dark/01 Text only/02 Title + Description",
			"Cell/_Dark/01 Text only/03 Description + Title",
			"Cell/_Dark/02 With Icon/01 Title",
			"Cell/_Dark/02 With Icon/02 Title + Description",
			"Cell/_Dark/02 With Icon/03 Description + Title",
		]
	},
	{
		componentName: "⚠️ CellValue",
		names: [
			"Cell/Text only/Value",
		]
	},
	{
		componentName: "🌈 Checkbox",
		names: [
			"Form/_Dark/_Checkbox/☞ Field/_Default/Compact",
			"Form/__Light/_Checkbox/☞ Field/_Traditional/Compact",
			"Form/_Dark/_Checkbox/☞ Field/_Default/_Default [Disabled]",
			"Form/_Dark/_Checkbox/☞ Field/_Default/With Description [Disabled]",
			"Form/__Light/_Checkbox/☞ Field/_Traditional/_Default [Disabled]",
			"Form/__Light/_Checkbox/☞ Field/_Traditional/With Description [Disabled]",
			"Form/_Dark/_Checkbox/☞ Field/_Default/Compact [Disabled]",
			"Form/__Light/_Checkbox/☞ Field/_Traditional/Compact [Disabled]",
			"Form/_Dark/_Checkbox/_Desktop/Simple",
			"Form/_Dark/_Checkbox/_Desktop/_Default",
			"Form/__Light/_Checkbox/_Traditional [L-XL]/Simple",
			"Form/__Light/_Checkbox/_Traditional [L-XL]/_Default",
			"Form/_Dark/_Checkbox/☞ Field/_Default/_Default",
			"Form/_Dark/_Checkbox/☞ Field/_Default/With Description",
			"Form/__Light/_Checkbox/☞ Field/_Traditional/_Default",
			"Form/__Light/_Checkbox/☞ Field/_Traditional/With Description",
		]
	},
	{
		componentName: "🌈 ContextualHelp",
		names: [
			"_global/info-contextual/Dark",
			"_global/info-contextual/Light",
			"_global/info-contextual/Overlay",
		]
	},
	{
		componentName: "🌈 Criteria",
		names: [
			"Form/_overrides/__Light/Criteria/Warning",
			"Form/_overrides/__Light/Criteria/Error",
			"Form/_overrides/__Light/Criteria/Success",
			"Form/_overrides/_Dark/Criteria/Warning",
			"Form/_overrides/_Dark/Criteria/Error",
			"Form/_overrides/_Dark/Criteria/Success",
		]
	},
	{
		componentName: "⚠️ [DonutPrimary]: DonutPrimary.SlideScore",
		names: [
			"Donuts/Primary/01 XS-S/Score/01 Alpha",
			"Donuts/Primary/02 M-XL/Score/01 Alpha",
			"Donuts/Primary/01 XS-S/Score/00 Theta",
			"Donuts/Primary/02 M-XL/Score/00 Theta",
			"Donuts/Primary/01 XS-S/Score/02 Beta",
			"Donuts/Primary/02 M-XL/Score/02 Beta",
			"Donuts/Primary/01 XS-S/Score/03 Gamma",
			"Donuts/Primary/02 M-XL/Score/03 Gamma",
			"Donuts/Primary/01 XS-S/Score/04 Delta",
			"Donuts/Primary/02 M-XL/Score/04 Delta",
			"Donuts/Primary/01 XS-S/Score/05 Epsilon",
			"Donuts/Primary/02 M-XL/Score/05 Epsilon",
		]
	},
	{
		componentName: "⚠️ [DonutPrimary]: DonutPrimary.Countdown",
		names: [
			"Donuts/Primary/01 XS-S/Countdown",
			"Donuts/Primary/02 M-XL/Countdown",
		]
	},
	{
		componentName: "⚠️ [DonutPrimary]: DonutPrimary.Offers",
		names: [
			"Donuts/Primary/01 XS-S/Offers/Cards",
			"Donuts/Primary/02 M-XL/Offers/Cards",
			"Donuts/Primary/01 XS-S/Offers/Loans",
			"Donuts/Primary/02 M-XL/Offers/Loans",
			"Donuts/Primary/01 XS-S/Offers/Car Finance",
			"Donuts/Primary/02 M-XL/Offers/Car Finance",
		]
	},
	{
		componentName: "⚠️ [DonutPrimary]: DonutPrimary.Change",
		names: [
			"Donuts/Primary/01 XS-S/Change/Up",
			"Donuts/Primary/02 M-XL/Change/Up",
			"Donuts/Primary/01 XS-S/Change/Down",
			"Donuts/Primary/01 XS-S/Change/Stable",
			"Donuts/Primary/02 M-XL/Change/Down",
			"Donuts/Primary/02 M-XL/Change/Stable",
		]
	},
	{
		componentName: "⚠️ [DonutPrimary]: DonutPrimary.Debt",
		names: [
			"Donuts/Primary/01 XS-S/Short Term Debt/Down",
			"Donuts/Primary/02 M-XL/Short Term Debt/Down",
			"Donuts/Primary/01 XS-S/Long Term Debt/Down",
			"Donuts/Primary/02 M-XL/Long Term Debt/Down",
			"Donuts/Primary/01 XS-S/Short Term Debt/Up",
			"Donuts/Primary/01 XS-S/Short Term Debt/No change",
			"Donuts/Primary/02 M-XL/Short Term Debt/Up",
			"Donuts/Primary/02 M-XL/Short Term Debt/No change",
			"Donuts/Primary/01 XS-S/Long Term Debt/Up",
			"Donuts/Primary/01 XS-S/Long Term Debt/No change",
			"Donuts/Primary/02 M-XL/Long Term Debt/Up",
			"Donuts/Primary/02 M-XL/Long Term Debt/No change",
		]
	},
	{
		componentName: "🌈 [DonutSecondary]: DonutSecondary.SlideText",
		names: [
			"Donuts/Secondary/01 XS-S/Default",
			"Donuts/Secondary/02 M-XL/Default",
		]
	},
	{
		componentName: "🌈 [DonutSecondary]: DonutSecondary.SlideOffers",
		names: [
			"Donuts/Secondary/01 XS-S/Number",
			"Donuts/Secondary/02 M-XL/Number",
		]
	},
	{
		componentName: "🌈 DonutSimple",
		names: [
			"Donuts/Simple/Large/05 Epsilon",
			"Donuts/Simple/Large/04 Delta",
			"Donuts/Simple/Large/03 Gamma",
			"Donuts/Simple/Large/02 Beta",
			"Donuts/Simple/Large/01 Alpha",
			"Donuts/Simple/Large/00 Theta",
			"Donuts/Simple/Tiny/Dark/05 Epsilon",
			"Donuts/Simple/Tiny/Dark/04 Delta",
			"Donuts/Simple/Tiny/Dark/03 Gamma",
			"Donuts/Simple/Tiny/Dark/02 Beta",
			"Donuts/Simple/Tiny/Dark/01 Alpha",
			"Donuts/Simple/Tiny/Dark/00 Theta",
			"Donuts/Simple/Tiny/Light/01 Alpha",
			"Donuts/Simple/Tiny/Light/00 Theta",
			"Donuts/Simple/Tiny/Light/02 Beta",
			"Donuts/Simple/Tiny/Light/03 Gamma",
			"Donuts/Simple/Tiny/Light/04 Delta",
			"Donuts/Simple/Tiny/Light/05 Epsilon",
			"Donuts/Simple/Small/00 Theta",
			"Donuts/Simple/Small/02 Beta",
			"Donuts/Simple/Small/03 Gamma",
			"Donuts/Simple/Small/04 Delta",
			"Donuts/Simple/Small/05 Epsilon",
			"Donuts/Simple/Medium/01 Alpha",
			"Donuts/Simple/Medium/00 Theta",
			"Donuts/Simple/Medium/02 Beta",
			"Donuts/Simple/Medium/03 Gamma",
			"Donuts/Simple/Medium/04 Delta",
			"Donuts/Simple/Medium/05 Epsilon",
			"Donuts/Simple/Small/02 Alpha",
		]
	},
	{
		componentName: "🌈 [DonutTertiary]: DonutTertiary.Start",
		names: [
			"Donuts/Tertiary/01 XS-S/Start",
			"Donuts/Tertiary/02 M-XL/Start",
		]
	},
	{
		componentName: "🌈 [DonutTertiary]: DonutTertiary.Continue",
		names: [
			"Donuts/Tertiary/01 XS-S/Continue",
			"Donuts/Tertiary/02 M-XL/Continue",
		]
	},
	{
		componentName: "🌈 [DonutTertiary]: DonutTertiary.Tasks",
		names: [
			"Donuts/Tertiary/01 XS-S/Tasks",
			"Donuts/Tertiary/02 M-XL/Tasks",
		]
	},
	{
		componentName: "🌈 Drawer",
		names: [
			"_global/Drawer/_Right/01 XS-S",
			"_global/Drawer/_Right/02 M",
			"_global/Drawer/_Right/03 L-XL",
			"_global/Drawer/Bottom/01 XS-S",
			"_global/Drawer/Bottom/02 M-XL",
		]
	},
	{
		componentName: "🌈 Dropdown",
		names: [
			"Form/_Dark/☞ Field/Dropdown/Disabled",
			"Form/__Light/☞ Field/Dropdown/Disabled",
			"Form/_Dark/☞ Field/Dropdown/Error",
			"Form/_Dark/☞ Field/Dropdown/Warning",
			"Form/__Light/☞ Field/Dropdown/Error",
			"Form/__Light/☞ Field/Dropdown/Warning",
			"Form/_Dark/☞ Field/Dropdown/Success",
			"Form/_Dark/☞ Field/Dropdown/Dirty",
			"Form/_Dark/☞ Field/Dropdown/Active",
			"Form/_Dark/☞ Field/Dropdown/_Default",
			"Form/__Light/☞ Field/Dropdown/Success",
			"Form/__Light/☞ Field/Dropdown/Dirty",
			"Form/__Light/☞ Field/Dropdown/Active",
			"Form/__Light/☞ Field/Dropdown/_Default",
		]
	},
	{
		componentName: "⚠️ Footer",
		names: [
			"Footer/01 XL",
			"Footer/02 L",
			"Footer/03 M",
			"Footer/04 S",
			"Footer/05 XS",
		]
	},
	{
		componentName: "🌈 Header",
		names: [
			"Text/Full-width title/__Light/Without Description/04 XS-S/02 Switch",
			"Text/Full-width title/__Light/Without Description/03 M",
			"Text/Full-width title/__Light/Without Description/02 L",
			"Text/Full-width title/__Light/Without Description/01 XL",
			"Text/Full-width title/__Light/With Description/03 M",
			"Text/Full-width title/__Light/With Description/02 L",
			"Text/Full-width title/__Light/With Description/01 L-XL",
			"Text/Full-width title/_Dark/Without Description/04 XS-S/02 Switch",
			"Text/Full-width title/_Dark/Without Description/03 M",
			"Text/Full-width title/_Dark/Without Description/02 L",
			"Text/Full-width title/_Dark/Without Description/01 XL",
			"Text/Full-width title/_Dark/With Description/03 M",
			"Text/Full-width title/_Dark/With Description/02 L",
			"Text/Full-width title/_Dark/With Description/01 L-XL",
		]
	},
	{
		componentName: "🌈 Information",
		names: [
			"Text/Information/_Dark",
			"Text/Information/__Light",
		]
	},
	{
		componentName: "⚠️ Input",
		names: [
			"Form/Label + Field/_Dark/Simple Criteria",
			"Form/Label + Field/_Dark/Criteria",
			"Form/Label + Field/_Dark/Simple Disabled",
			"Form/Label + Field/_Dark/Disabled",
			"Form/Label + Field/_Dark/Simple",
			"Form/Label + Field/_Dark/_Default",
			"Form/Label + Field/__Light/Simple Criteria",
			"Form/Label + Field/__Light/Criteria",
			"Form/Label + Field/__Light/Simple Disabled",
			"Form/Label + Field/__Light/Disabled",
			"Form/Label + Field/__Light/Simple",
			"Form/Label + Field/__Light/_Default",
		]
	},
	{
		componentName: "🌈 Label",
		names: [
			"Form/__Light/_Label/Default Disabled",
			"Form/_Dark/_Label/Default Disabled",
			"Form/__Light/_Label/Simple Disabled",
			"Form/_Dark/_Label/Simple Disabled",
			"Form/__Light/_Label/_Default",
			"Form/_Dark/_Label/_Default",
			"Form/__Light/_Label/Simple",
			"Form/_Dark/_Label/Simple",
		]
	},
	{
		componentName: "🌈 [List] List item",
		names: [
			"Text/Bullet/_Dark/04 With Link",
			"Text/Bullet/_Dark/03 Negative",
			"Text/Bullet/_Dark/02 Positive",
			"Text/Bullet/_Dark/01 Default",
			"Text/Bullet/__Light/04 With Link",
			"Text/Bullet/__Light/03 Negative",
			"Text/Bullet/__Light/02 Positive",
			"Text/Bullet/__Light/01 Default",
		]
	},
	{
		componentName: "🌈 MegaLoader",
		names: [
			"_global/Mega Spinner/Text only",
			"_global/Mega Spinner/With image",
		]
	},
	{
		componentName: "🌈 MenuSecondary",
		names: [
			"Navigation/_SecondaryNav/_XS-S/No scroll",
			"Navigation/_SecondaryNav/_XS-S/Right aligned",
			"Navigation/_SecondaryNav/_XS-S/Center aligned",
			"Navigation/_SecondaryNav/_XS-S/Left aligned",
			"Navigation/_SecondaryNav/M",
			"Navigation/_SecondaryNav/L",
			"Navigation/_SecondaryNav/XL",
		]
	},
	{
		componentName: "🌈 MultiSelect",
		names: [
			"Form/__Light/_Multi Select/_Default",
			"Form/__Light/_Multi Select/Hover",
			"Form/__Light/_Multi Select/Active",
		]
	},
	{
		componentName: "🌈 Notification",
		names: [
			"Notifications/_Dark/XS-S",
			"Notifications/_Dark/M-XL",
			"Notifications/__Light/XS-S",
			"Notifications/__Light/M-XL",
		]
	},
	{
		componentName: "🌈 Pager",
		names: [
			"_global/Pager/On Dark/08/08",
			"_global/Pager/On Dark/08/07",
			"_global/Pager/On Dark/08/06",
			"_global/Pager/On Dark/08/05",
			"_global/Pager/On Dark/08/04",
			"_global/Pager/On Dark/08/03",
			"_global/Pager/On Dark/08/02",
			"_global/Pager/On Dark/08/01",
			"_global/Pager/On Dark/07/07",
			"_global/Pager/On Dark/07/06",
			"_global/Pager/On Dark/07/05",
			"_global/Pager/On Dark/07/04",
			"_global/Pager/On Dark/07/03",
			"_global/Pager/On Dark/07/02",
			"_global/Pager/On Dark/07/01",
			"_global/Pager/On Dark/06/06",
			"_global/Pager/On Dark/06/05",
			"_global/Pager/On Dark/06/04",
			"_global/Pager/On Dark/06/03",
			"_global/Pager/On Dark/06/02",
			"_global/Pager/On Dark/06/01",
			"_global/Pager/On Dark/05/05",
			"_global/Pager/On Dark/05/04",
			"_global/Pager/On Dark/05/03",
			"_global/Pager/On Dark/05/02",
			"_global/Pager/On Dark/05/01",
			"_global/Pager/On Dark/04/04",
			"_global/Pager/On Dark/04/03",
			"_global/Pager/On Dark/04/02",
			"_global/Pager/On Dark/04/01",
			"_global/Pager/On Dark/03/03",
			"_global/Pager/On Dark/03/02",
			"_global/Pager/On Dark/03/01",
			"_global/Pager/On Light/08/08",
			"_global/Pager/On Light/08/07",
			"_global/Pager/On Light/08/06",
			"_global/Pager/On Light/08/05",
			"_global/Pager/On Light/08/04",
			"_global/Pager/On Light/08/03",
			"_global/Pager/On Light/08/02",
			"_global/Pager/On Light/08/01",
			"_global/Pager/On Light/07/07",
			"_global/Pager/On Light/07/06",
			"_global/Pager/On Light/07/05",
			"_global/Pager/On Light/07/04",
			"_global/Pager/On Light/07/03",
			"_global/Pager/On Light/07/02",
			"_global/Pager/On Light/07/01",
			"_global/Pager/On Light/06/06",
			"_global/Pager/On Light/06/05",
			"_global/Pager/On Light/06/04",
			"_global/Pager/On Light/06/03",
			"_global/Pager/On Light/06/02",
			"_global/Pager/On Light/06/01",
			"_global/Pager/On Light/05/05",
			"_global/Pager/On Light/05/04",
			"_global/Pager/On Light/05/03",
			"_global/Pager/On Light/05/02",
			"_global/Pager/On Light/05/01",
			"_global/Pager/On Light/04/04",
			"_global/Pager/On Light/04/03",
			"_global/Pager/On Light/04/02",
			"_global/Pager/On Light/04/01",
			"_global/Pager/On Light/03/03",
			"_global/Pager/On Light/03/02",
			"_global/Pager/On Light/03/01",
			"_global/Pager/_overrides/02 Dark/02 Active",
			"_global/Pager/_overrides/02 Dark/01 Default",
			"_global/Pager/_overrides/01 Light/02 Active",
			"_global/Pager/_overrides/01 Light/01 Default",
		]
	},
	{
		componentName: "🌈 Password",
		names: [
			"Form/__Light/__Group/Simple Password",
			"Form/__Light/__Group/Password",
			"Form/_Dark/__Group/Simple Password",
			"Form/_Dark/__Group/Password",
			"Form/_Dark/☞ Field/Password/Disabled",
			"Form/_Dark/☞ Field/Password/Visible",
			"Form/__Light/☞ Field/Password/Disabled",
			"Form/__Light/☞ Field/Password/Visible",
			"Form/_Dark/☞ Field/Password/Error",
			"Form/_Dark/☞ Field/Password/Warning",
			"Form/__Light/☞ Field/Password/Error",
			"Form/__Light/☞ Field/Password/Warning",
			"Form/_Dark/☞ Field/Password/Success",
			"Form/_Dark/☞ Field/Password/Dirty",
			"Form/_Dark/☞ Field/Password/Active",
			"Form/_Dark/☞ Field/Password/_Default",
			"Form/__Light/☞ Field/Password/Success",
			"Form/__Light/☞ Field/Password/Dirty",
			"Form/__Light/☞ Field/Password/Active",
			"Form/__Light/☞ Field/Password/_Default",
		]
	},
	{
		componentName: "🌈 Pill",
		names: [
			"Text/Number/_overrides/__Light/01 Body",
			"Text/Number/_overrides/__Light/02 Success",
			"Text/Number/_overrides/__Light/03 Failure",
			"Text/Number/_overrides/__Light/04 Disabled",
			"Text/Number/_overrides/_Dark/01 Body",
			"Text/Number/_overrides/_Dark/02 Success",
			"Text/Number/_overrides/_Dark/03 Failure",
			"Text/Number/_overrides/_Dark/04 Disabled",
			"Text/Number/_Dark/01 Default",
			"Text/Number/_Dark/02 Disabled",
			"Text/Number/__Light/01 Default",
			"Text/Number/__Light/02 Disabled",
		]
	},
	{
		componentName: "🌈 Popover",
		names: [
			"_global/Popup position/On Light/04 Left",
			"_global/Popup position/On Light/03 Right",
			"_global/Popup position/On Light/02 Bottom",
			"_global/Popup position/On Light/01 Top",
			"_global/Popup position/On Dark/04 Left",
			"_global/Popup position/On Dark/03 Right",
			"_global/Popup position/On Dark/02 Bottom",
			"_global/Popup position/On Dark/01 Top",
			"Text/Popup/__Light/01 Default",
			"Text/Popup/_Dark/01 Default",
			"Text/Popup/_Dark/02 Choice/02 XS-S",
			"Text/Popup/_Dark/02 Choice/01 M-XL",
			"Text/Popup/__Light/02 Choice/02 XS-S",
			"Text/Popup/__Light/02 Choice/01 M-XL",
		]
	},
	{
		componentName: "🌈 Progress",
		names: [
			"_global/Progress/__Light/Linked/Link",
			"_global/Progress/__Light/Linked/Unavailable",
			"_global/Progress/__Light/Solo/Link",
			"_global/Progress/__Light/Linked/_Default",
			"_global/Progress/__Light/Solo/_Default",
			"_global/Progress/__Light/Solo/Unavailable",
			"_global/Progress/_Dark/Linked/Link",
			"_global/Progress/_Dark/Linked/Unavailable",
			"_global/Progress/_Dark/Solo/Link",
			"_global/Progress/_Dark/Linked/_Default",
			"_global/Progress/_Dark/Solo/_Default",
			"_global/Progress/_Dark/Solo/Unavailable",
			"_global/Progress/Ω _overrides/_Dark/02 Other/03 Unavailable",
			"_global/Progress/Ω _overrides/_Dark/02 Other/02 Done",
			"_global/Progress/Ω _overrides/_Dark/02 Other/01 Todo",
			"_global/Progress/Ω _overrides/_Dark/01 Top/02 Done",
			"_global/Progress/Ω _overrides/_Dark/01 Top/01 Todo",
			"_global/Progress/Ω _overrides/_Dark/01 Top/03 Unavailable",
			"_global/Progress/Ω _overrides/__Light/02 Other/03 Unavailable",
			"_global/Progress/Ω _overrides/__Light/02 Other/02 Done",
			"_global/Progress/Ω _overrides/__Light/02 Other/01 Todo",
			"_global/Progress/Ω _overrides/__Light/01 Top/02 Done",
			"_global/Progress/Ω _overrides/__Light/01 Top/01 Todo",
			"_global/Progress/Ω _overrides/__Light/01 Top/03 Unavailable",
		]
	},
	{
		componentName: "🌈 ProgressRing",
		names: [
			"Donuts/_overrides/Ring/Epsilon/100%",
			"Donuts/_overrides/Ring/Tertiary/100%",
			"Donuts/_overrides/Ring/Short Term Debt/100%",
			"Donuts/_overrides/Ring/Long Term Debt/100%",
			"Donuts/_overrides/Ring/Alpha/30%",
			"Donuts/_overrides/Ring/Tertiary/30%",
			"Donuts/_overrides/Ring/Alpha/25%",
			"Donuts/_overrides/Ring/Tertiary/25%",
			"Donuts/_overrides/Ring/Short Term Debt/25%",
			"Donuts/_overrides/Ring/Long Term Debt/25%",
			"Donuts/_overrides/Ring/Alpha/15%",
			"Donuts/_overrides/Ring/Change/Alpha/Up",
			"Donuts/_overrides/Ring/Change/Beta/Up",
			"Donuts/_overrides/Ring/Change/Gamma/Up",
			"Donuts/_overrides/Ring/Change/Delta/Up",
			"Donuts/_overrides/Ring/Change/Epsilon/Up",
			"Donuts/_overrides/Ring/Change/Alpha/Down",
			"Donuts/_overrides/Ring/Change/Beta/Down",
			"Donuts/_overrides/Ring/Change/Gamma/Down",
			"Donuts/_overrides/Ring/Change/Delta/Down",
			"Donuts/_overrides/Ring/Change/Epsilon/Down",
			"Donuts/_overrides/Ring/Tertiary/15%",
			"Donuts/_overrides/Ring/Beta/35%",
			"Donuts/_overrides/Ring/Tertiary/35%",
			"Donuts/_overrides/Ring/Gamma/50%",
			"Donuts/_overrides/Ring/Tertiary/50%",
			"Donuts/_overrides/Ring/Short Term Debt/50%",
			"Donuts/_overrides/Ring/Long Term Debt/50%",
			"Donuts/_overrides/Ring/Beta/40%",
			"Donuts/_overrides/Ring/Tertiary/40%",
			"Donuts/_overrides/Ring/Epsilon/85%",
			"Donuts/_overrides/Ring/Tertiary/85%",
			"Donuts/_overrides/Ring/Epsilon/75%",
			"Donuts/_overrides/Ring/Tertiary/75%",
			"Donuts/_overrides/Ring/Short Term Debt/75%",
			"Donuts/_overrides/Ring/Long Term Debt/75%",
			"Donuts/_overrides/Ring/Delta/70%",
			"Donuts/_overrides/Ring/Delta/62%",
			"Donuts/_overrides/Ring/Tertiary/62%",
			"Donuts/_overrides/Ring/Gamma/55%",
			"Donuts/_overrides/Ring/Tertiary/55%",
		]
	},
	{
		componentName: "🌈 Prompt",
		names: [
			"Prompt/_Dark/04 XL",
			"Prompt/_Dark/03 L",
			"Prompt/_Dark/02 M",
			"Prompt/_Dark/01 XS-S",
			"Prompt/__Light/04 XL",
			"Prompt/__Light/03 L",
			"Prompt/__Light/02 M",
			"Prompt/__Light/01 XS-S",
		]
	},
	{
		componentName: "🌈 Radio",
		names: [
			"Form/_Dark/_Radio/☞ Field/02 Desktop/_Default [Disabled]",
			"Form/_Dark/_Radio/☞ Field/01 Mobile/_Default [Disabled]",
			"Form/_Dark/_Radio/☞ Field/02 Desktop/With Description [Disabled]",
			"Form/_Dark/_Radio/☞ Field/01 Mobile/With Description [Disabled]",
			"Form/__Light/_Radio/☞ Field/02 Desktop/_Default [Disabled]",
			"Form/__Light/_Radio/☞ Field/01 Mobile/_Default [Disabled]",
			"Form/__Light/_Radio/☞ Field/02 Desktop/With Description [Disabled]",
			"Form/__Light/_Radio/☞ Field/01 Mobile/With Description [Disabled]",
			"Form/_Dark/_Radio/☞ Field/02 Desktop/Compact [Disabled]",
			"Form/_Dark/_Radio/☞ Field/01 Mobile/Compact [Disabled]",
			"Form/__Light/_Radio/☞ Field/02 Desktop/Compact [Disabled]",
			"Form/__Light/_Radio/☞ Field/01 Mobile/Compact [Disabled]",
			"Form/_Dark/_Radio/☞ Field/02 Desktop/Compact",
			"Form/_Dark/_Radio/☞ Field/01 Mobile/Compact",
			"Form/__Light/_Radio/☞ Field/02 Desktop/Compact",
			"Form/__Light/_Radio/☞ Field/01 Mobile/Compact",
			"Form/_Dark/_Radio/☞ Field/02 Desktop/_Default",
			"Form/_Dark/_Radio/☞ Field/01 Mobile/_Default",
			"Form/_Dark/_Radio/☞ Field/02 Desktop/With Description",
			"Form/_Dark/_Radio/☞ Field/01 Mobile/With Description",
			"Form/__Light/_Radio/☞ Field/02 Desktop/_Default",
			"Form/__Light/_Radio/☞ Field/01 Mobile/_Default",
			"Form/__Light/_Radio/☞ Field/02 Desktop/With Description",
			"Form/__Light/_Radio/☞ Field/01 Mobile/With Description",
		]
	},
	{
		componentName: "🌈 RadioGroup",
		names: [
			"Form/_Dark/_Radio/_Desktop/Simple",
			"Form/_Dark/_Radio/__Mobile/Simple",
			"Form/_Dark/_Radio/_Desktop/_Default",
			"Form/_Dark/_Radio/__Mobile/_Default",
			"Form/__Light/_Radio/_L-XL/Simple",
			"Form/__Light/_Radio/__XS-M/Simple",
			"Form/__Light/_Radio/_L-XL/_Default",
			"Form/__Light/_Radio/__XS-M/_Default",
		]
	},
	{
		componentName: "🌈 Ratings",
		names: [
			"_global/Rating/5",
			"_global/Rating/4.5",
			"_global/Rating/4",
			"_global/Rating/3.5",
			"_global/Rating/3",
			"_global/Rating/2.5",
			"_global/Rating/2",
			"_global/Rating/1.5",
			"_global/Rating/1",
			"_global/Rating/0.5",
			"_global/Rating/0",
			"_global/Rating/_Rating with count",
		]
	},
	{
		componentName: "🌈 SectionTitle",
		names: [
			"Text/SectionTitle/M-XL",
			"Text/SectionTitle/XS-S",
		]
	},
	{
		componentName: "🌈 SegmentedControl",
		names: [
			"Form/__Light/_Segmented control/_Group/Large/2 options",
			"Form/__Light/_Segmented control/_Group/Small/2 options",
			"Form/__Light/_Segmented control/_Group/Large/3 options",
			"Form/__Light/_Segmented control/_Group/Small/3 options",
		]
	},
	{
		componentName: "🌈 SegmentedControlOption",
		names: [
			"Form/Segmented control/Option/Small/Disabled",
			"Form/Segmented control/Option/Small/Active",
			"Form/Segmented control/Option/Small/Hover",
			"Form/Segmented control/Option/Small/_default",
			"Form/Segmented control/Option/Large/Disabled",
			"Form/Segmented control/Option/Large/Active",
			"Form/Segmented control/Option/Large/Hover",
			"Form/Segmented control/Option/Large/_default",
		]
	},
	{
		componentName: "🌈 Tag",
		names: [
			"_global/Tag/__Light/_Default [Smart]",
			"_global/Tag/__Light/_Default [Fixed]",
			"_global/Tag/__Light/Secondary [Smart]",
			"_global/Tag/__Light/Secondary [Fixed]",
			"_global/Tag/__Light/Negative [Smart]",
			"_global/Tag/__Light/Negative [Fixed]",
			"_global/Tag/__Light/Positive [Smart]",
			"_global/Tag/__Light/Positive [Fixed]",
			"_global/Tag/__Light/Attention [Smart]",
			"_global/Tag/__Light/Attention [Fixed]",
			"_global/Tag/__Light/Information [Smart]",
			"_global/Tag/__Light/Information [Fixed]",
			"_global/Tag/__Light/Outline",
			"_global/Tag/_Dark/_Default [Smart]",
			"_global/Tag/_Dark/_Default [Fixed]",
			"_global/Tag/_Dark/Secondary [Smart]",
			"_global/Tag/_Dark/Secondary [Fixed]",
			"_global/Tag/_Dark/Negative [Smart]",
			"_global/Tag/_Dark/Negative [Fixed]",
			"_global/Tag/_Dark/Positive [Smart]",
			"_global/Tag/_Dark/Positive [Fixed]",
			"_global/Tag/_Dark/Attention [Smart]",
			"_global/Tag/_Dark/Information [Fixed]",
			"_global/Tag/_Dark/Information [Smart]",
			"_global/Tag/_Dark/Attention [Fixed]",
			"_global/Tag/_Dark/Outline",
			"_global/Tag/Overlay [Lighten] [Fixed]",
			"_global/Tag/Overlay [Lighten] [Smart]",
			"_global/Tag/Overlay [Darken] [Fixed]",
			"_global/Tag/Overlay [Darken] [Smart]",
		]
	},
	{
		componentName: "🌈 TextInput",
		names: [
			"Form/_Dark/☞ Field/Input/Disabled",
			"Form/__Light/☞ Field/Input/Disabled",
			"Form/_Dark/☞ Field/Input/Error",
			"Form/_Dark/☞ Field/Input/Warning",
			"Form/__Light/☞ Field/Input/Error",
			"Form/__Light/☞ Field/Input/Warning",
			"Form/_Dark/☞ Field/Input/Success",
			"Form/_Dark/☞ Field/Input/Dirty",
			"Form/_Dark/☞ Field/Input/Active",
			"Form/_Dark/☞ Field/Input/_Default",
			"Form/__Light/☞ Field/Input/Success",
			"Form/__Light/☞ Field/Input/Dirty",
			"Form/__Light/☞ Field/Input/Active",
			"Form/__Light/☞ Field/Input/_Default",
			"Form/_Dark/☞ Field/Input + Prefix/Disabled",
			"Form/__Light/☞ Field/Input + Prefix/Disabled",
			"Form/_Dark/☞ Field/Input + Prefix/Error",
			"Form/_Dark/☞ Field/Input + Prefix/Warning",
			"Form/__Light/☞ Field/Input + Prefix/Error",
			"Form/__Light/☞ Field/Input + Prefix/Warning",
			"Form/_Dark/☞ Field/Input + Prefix/Success",
			"Form/_Dark/☞ Field/Input + Prefix/Dirty",
			"Form/_Dark/☞ Field/Input + Prefix/Active",
			"Form/_Dark/☞ Field/Input + Prefix/_Default",
			"Form/__Light/☞ Field/Input + Prefix/Success",
			"Form/__Light/☞ Field/Input + Prefix/Dirty",
			"Form/__Light/☞ Field/Input + Prefix/Active",
			"Form/__Light/☞ Field/Input + Prefix/_Default",
			"Form/_Dark/☞ Field/Input + Suffix/Disabled",
			"Form/__Light/☞ Field/Input + Suffix/Disabled",
			"Form/_Dark/☞ Field/Input + Suffix/Error",
			"Form/_Dark/☞ Field/Input + Suffix/Warning",
			"Form/__Light/☞ Field/Input + Suffix/Error",
			"Form/__Light/☞ Field/Input + Suffix/Warning",
			"Form/_Dark/☞ Field/Input + Suffix/Success",
			"Form/_Dark/☞ Field/Input + Suffix/Dirty",
			"Form/_Dark/☞ Field/Input + Suffix/Active",
			"Form/_Dark/☞ Field/Input + Suffix/_Default",
			"Form/__Light/☞ Field/Input + Suffix/Success",
			"Form/__Light/☞ Field/Input + Suffix/Dirty",
			"Form/__Light/☞ Field/Input + Suffix/Active",
			"Form/__Light/☞ Field/Input + Suffix/_Default",
			"Form/_Dark/☞ Field/Input + Prefix + Suffix/Disabled",
			"Form/__Light/☞ Field/Input + Prefix + Suffix/Disabled",
			"Form/_Dark/☞ Field/Input + Prefix + Suffix/Error",
			"Form/_Dark/☞ Field/Input + Prefix + Suffix/Warning",
			"Form/__Light/☞ Field/Input + Prefix + Suffix/Error",
			"Form/__Light/☞ Field/Input + Prefix + Suffix/Warning",
			"Form/_Dark/☞ Field/Input + Prefix + Suffix/Success",
			"Form/_Dark/☞ Field/Input + Prefix + Suffix/Dirty",
			"Form/_Dark/☞ Field/Input + Prefix + Suffix/Active",
			"Form/_Dark/☞ Field/Input + Prefix + Suffix/_Default",
			"Form/__Light/☞ Field/Input + Prefix + Suffix/Success",
			"Form/__Light/☞ Field/Input + Prefix + Suffix/Dirty",
			"Form/__Light/☞ Field/Input + Prefix + Suffix/Active",
			"Form/__Light/☞ Field/Input + Prefix + Suffix/_Default",
		]
	},
	{
		componentName: "🌈 TextAreaInput",
		names: [
			"Form/_Dark/☞ Field/Text Area/Disabled",
			"Form/__Light/☞ Field/Text Area/Disabled",
			"Form/_Dark/☞ Field/Text Area/Error",
			"Form/_Dark/☞ Field/Text Area/Warning",
			"Form/__Light/☞ Field/Text Area/Error",
			"Form/__Light/☞ Field/Text Area/Warning",
			"Form/_Dark/☞ Field/Text Area/Success",
			"Form/_Dark/☞ Field/Text Area/Dirty",
			"Form/_Dark/☞ Field/Text Area/Active",
			"Form/_Dark/☞ Field/Text Area/_Default",
			"Form/__Light/☞ Field/Text Area/Success",
			"Form/__Light/☞ Field/Text Area/Dirty",
			"Form/__Light/☞ Field/Text Area/Active",
			"Form/__Light/☞ Field/Text Area/_Default",
		]
	},
	{
		componentName: "⚠️ TimeMachine",
		names: [
			"Widgets/Time Machine/_XS-S/Basic",
			"Widgets/Time Machine/M-XL/Basic",
			"Widgets/Time Machine/_XS-S/_Default",
			"Widgets/Time Machine/M-XL/_Default",
		]
	},
	{
		componentName: "🌈 ToggleSwitch",
		names: [
			"Form/_Dark/_Checkbox/☞ Field/Switch/Compact",
			"Form/__Light/_Checkbox/☞ Field/__Switch/Compact",
			"Form/_Dark/_Checkbox/☞ Field/Switch/_Default [Disabled]",
			"Form/_Dark/_Checkbox/☞ Field/Switch/With Description [Disabled]",
			"Form/__Light/_Checkbox/☞ Field/__Switch/_Default [Disabled]",
			"Form/__Light/_Checkbox/☞ Field/__Switch/With Description [Disabled]",
			"Form/_Dark/_Checkbox/☞ Field/Switch/Compact [Disabled]",
			"Form/__Light/_Checkbox/☞ Field/__Switch/Compact [Disabled]",
			"Form/_Dark/_Checkbox/__Mobile/Simple",
			"Form/_Dark/_Checkbox/__Mobile/_Default",
			"Form/__Light/_Checkbox/__Switch [XS-M]/Simple",
			"Form/__Light/_Checkbox/__Switch [XS-M]/_Default",
			"Form/_Dark/_Checkbox/☞ Field/Switch/_Default",
			"Form/_Dark/_Checkbox/☞ Field/Switch/With Description",
			"Form/__Light/_Checkbox/☞ Field/__Switch/_Default",
			"Form/__Light/_Checkbox/☞ Field/__Switch/With Description",
		]
	},
	{
		componentName: "🌈 PrimaryNav",
		names: [
			"Navigation/__PrimaryNav/_XS-S",
			"Navigation/__PrimaryNav/M",
			"Navigation/__PrimaryNav/L",
			"Navigation/__PrimaryNav/XL",
			"Navigation/__PrimaryNav/_XS-S [Menu]",
		]
	},
	{
		componentName: "🌈 MenuItem",
		names: [
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Dashboard/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Dashboard/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Dashboard/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Report/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Report/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Offers/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Offers/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Protect/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Protect/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Timeline/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Timeline/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Coaching/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/Coaching/Active",
			"Navigation /🚫 overrides / __PrimaryNav / MenuItem / XS - S / Dashboard / _Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Dashboard/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Report/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Report/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Offers/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Offers/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Protect/_Default",
			"Navigation/🚫 overrides/_MyAccountMenu/MenuItem/My Account/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Protect/Active",
			"Navigation/🚫 overrides/_MyAccountMenu/MenuItem/Account drawer/My Account/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Timeline/_Default",
			"Navigation/🚫 overrides/_MyAccountMenu/MenuItem/Account drawer/Help/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Timeline/Active",
			"Navigation/🚫 overrides/_MyAccountMenu/MenuItem/Account drawer/Help/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Coaching/_Default",
			"Navigation/🚫 overrides/_MyAccountMenu/MenuItem/Account drawer/Log out/_Default",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/Coaching/Active",
			"Navigation/🚫 overrides/_MyAccountMenu/MenuItem/Account drawer/Log out/Active",
			"Navigation/🚫 overrides/MyAccountItem/L-XL",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/XS-S/_Template",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/M-XL/_Template",
			"Navigation/🚫 overrides/_MyAccountMenu/MenuItem/My Account/Active",
			"Navigation/🚫 overrides/__PrimaryNav/MenuItem/L-XL/My Account",
		]
	},
	{
		componentName: "🌈 MyAccountMenu",
		names: [
			"Navigation/_MyAccountMenu/_XS-S",
			"Navigation/_MyAccountMenu/M",
			"Navigation/_MyAccountMenu/L-XL",
		]
	},
	{
		componentName: "🌈 TextValue",
		names: [
			"Text/Value information/_Dark",
			"Text/Value information/__Light",
			"Text/Value information/_overrides/__Light/Label",
			"Text/Value information/_overrides/_Dark/Label",
		]
	}
];

export default symbols;
