const CSWeb_TO_ADD = [
	// _global
	"_global/Full width CTA/04 XS-S",
	"_global/Full width CTA/03 M",
	"_global/Full width CTA/01 XL",
	"_global/Full width CTA/02 L",
	"_global/Full width CTA/_overrides/Text/02 XS-S",
	"_global/Full width CTA/_overrides/Text/01 M-XL",
	"_global/Shadow",
	"_global/FTW Pimple",
	"_global/Secure/Light",
	"_global/Secure/Dark",
	"_global/Outline/06 Bottom Rounded",
	"_global/Outline/05 Top Rounded",
	"_global/Outline/04 Right Rounded",
	"_global/Outline/03 Left Rounded",
	"_global/Outline/02 Square",
	"_global/Outline/01 Rounded",
	"_global/Full width CTA/_overrides/Image",
	"_global/Notch/M",
	"_global/Notch/XS-S",
	"_global/Notch/L",
	"_global/Notch/XL",
	"_global/_Default Image/Logos/Square/Natwest",
	"_global/Progress bar/25%",
	"_global/Progress bar/50%",
	"_global/Progress bar/75%",
	"_global/Progress bar/100%",
	"_global/Tag/Overlay/Lighten [Fixed]",
	"_global/Tag/Overlay/White [Fixed]",
	"_global/Tag/Overlay/Lighten [Smart]",
	"_global/Tag/Overlay/White [Smart]",
	"_global/Tag/Overlay/Darken [Fixed]",
	"_global/Tag/Overlay/Darken [Smart]",
	"_global/Notification Dot/__Light",
	"_global/Notification Dot/_Dark",

	// Accordion
	"Accordion/02 Content/02 Rating",
	"Accordion/02 Content/01 Tabs/02 XS-S",
	"Accordion/02 Content/01 Tabs/01 M-XL",
	"Accordion/_overrides/Content type/04 Center Notch",
	"Accordion/_overrides/Content type/05 Bottom Fill",
	"Accordion/_overrides/Content type/03 Center Fill",
	"Accordion/_overrides/Content type/01 Center",
	"Accordion/_overrides/Content type/02 Bottom",
	"Accordion/_overrides/Header type/03 Open",
	"Accordion/_overrides/Header type/02 Multiple",
	"Accordion/_overrides/Header type/01 Single",
	"Accordion/_overrides/Details Row/01 M-XL",
	"Accordion/_overrides/Details Row/02 XS-S",
	"Accordion/_overrides/Content Accordion row/01 M-XL",
	"Accordion/_overrides/Content Accordion row/02 XS-S",

	// Account balance
	"Account balance/01 Balance",
	"Account balance/_overrides/Other",
	"Account balance/_overrides/Short Term",
	"Account balance/_overrides/Long Term",
	"Account balance/_overrides/No Limit",
	"Account balance/_overrides/Limit outline",
	"Account balance/_overrides/Near or above limit",
	"Account balance/_overrides/No limit",
	"Account balance/_overrides/Fill/5",
	"Account balance/_overrides/Fill/4",
	"Account balance/_overrides/Fill/3",
	"Account balance/_overrides/Fill/2",
	"Account balance/_overrides/Fill/1",

	// Button
	"Button/🚫 overrides/02 Loading/04 Dark",
	"Button/🚫 overrides/02 Loading/02 Link",
	"Button/🚫 overrides/02 Loading/01 Default",
	"Button/🚫 overrides/Shadow/01 On Light",
	"Button/🚫 overrides/Shadow/02 On Dark",

	// Cards
	"Card/🚫 Overrides/_Dark/Flag/04 Coming Soon",
	"Card/🚫 Overrides/_Dark/Flag/03 Complete",
	"Card/🚫 Overrides/_Dark/Flag/02 Active",
	"Card/🚫 Overrides/_Dark/Flag/01 Recommended",
	"Card/_Dark/Product Verticals/Small/02 Active",
	"Card/_Dark/Product Verticals/Small/01 Default",
	"Card/_Dark/Product Verticals/Small/03 Hover",
	"Card/_Dark/Product Verticals/Large/02 Active",
	"Card/_Dark/Product Verticals/Large/03 Hover",
	"Card/_Dark/Product Verticals/Large/01 Default",
	"Card/🚫 Overrides/_Dark/Notification",
	"Card/🚫 Overrides/_Dark/Notify CTA",
	"Card/🚫 Overrides/_Dark/Detail/Footer/XS-S/Tag",
	"Card/🚫 Overrides/_Dark/Detail/Header/Icon",
	"Card/_Dark/Coaching/State 3",
	"Card/_Dark/Coaching/State 2",
	"Card/_Dark/Coaching/State 1",
	"Card/🚫 Overrides/_Dark/Detail/Footer/M-XL/Button",
	"Card/🚫 Overrides/_Dark/Detail/Footer/XS-S/Button",
	"Card/🚫 Overrides/_Dark/Detail/Date",
	"Card/🚫 Overrides/_Dark/Detail/Header/Tag",
	"Card/_Dark/Label + Value",
	"Card/🚫 Overrides/_Dark/Detail/Footer/M-XL/Tag",
	"Card/🚫 Overrides/_Dark/Detail/Header/Multiple tags",
	"Card/🚫 Overrides/__Light/Detail/Footer/XS-S/Tag",
	"Card/🚫 Overrides/__Light/Detail/Header/Icon",
	"Card/__Light/Product Verticals/Small/02 Active",
	"Card/__Light/Product Verticals/Small/01 Default",
	"Card/__Light/Product Verticals/Small/03 Hover",
	"Card/__Light/Product Verticals/Large/02 Active",
	"Card/__Light/Product Verticals/Large/03 Hover",
	"Card/__Light/Product Verticals/Large/01 Default",
	"Card/__Light/Coaching/State 3",
	"Card/__Light/Coaching/State 2",
	"Card/__Light/Coaching/State 1",
	"Card/🚫 Overrides/__Light/Notification",
	"Card/🚫 Overrides/__Light/Flag/04 Coming Soon",
	"Card/🚫 Overrides/__Light/Flag/03 Complete",
	"Card/🚫 Overrides/__Light/Flag/02 Active",
	"Card/🚫 Overrides/__Light/Flag/01 Recommended",
	"Card/🚫 Overrides/__Light/Notify CTA",
	"Card/🚫 Overrides/__Light/Detail/Footer/M-XL/Button",
	"Card/🚫 Overrides/__Light/Detail/Date",
	"Card/🚫 Overrides/__Light/Detail/New",
	"Card/🚫 Overrides/__Light/Detail/Header/Tag",
	"Card/__Light/Label + Value",
	"Card/🚫 Overrides/__Light/Detail/Footer/M-XL/Tag",
	"Card/🚫 Overrides/__Light/Detail/Header/Multiple tags",
	"Card/🚫 Overrides/__Light/Detail/Footer/XS-S/Button",
	"Card/🚫 Overrides/_Dark/Detail/New",

	// Cells
	"Cell/_overrides/_Dark/Border/Text indent",
	"Cell/_overrides/_Dark/Border/Full width",
	"Cell/_overrides/_Dark/Border/Icon indent",
	"Cell/_Dark/_Base",
	"Cell/_overrides/_Dark/Right accessory/Link",
	"Cell/_overrides/_Dark/Right accessory/Switch",
	"Cell/_overrides/__Light/Border/Text indent",
	"Cell/_overrides/__Light/Border/Full width",
	"Cell/_overrides/__Light/Border/Icon indent",
	"Cell/__Light/_Base",
	"Cell/_overrides/__Light/Right accessory/Link",
	"Cell/_overrides/__Light/Right accessory/Switch",

	// Chat
	"Chat/01 Message/02 User",
	"Chat/01 Message/03 Special",
	"Chat/01 Message/01 Bot",
	"Chat/02 Response/3",
	"Chat/02 Response/2",
	"Chat/_overrides/04 Special",
	"Chat/_overrides/05 Image",
	"Chat/_overrides/02 Right",
	"Chat/_overrides/01 Left",

	// Donuts
	"Donuts/_overrides/Core/Primary/XS-S/Score",
	"Donuts/_overrides/Core/Primary/XS-S/_Default",
	"Donuts/_overrides/Core/Primary/M-XL/Score",
	"Donuts/_overrides/Core/Primary/M-XL/_Default",
	"Donuts/_overrides/Core/Primary/XS-S/Offer",
	"Donuts/_overrides/Core/Primary/M-XL/Offer",
	"Donuts/_overrides/Core/Primary/XS-S/Change",
	"Donuts/_overrides/Core/Primary/M-XL/Change",
	"Donuts/_overrides/Core/Primary/XS-S/Short term debt",
	"Donuts/_overrides/Core/Primary/M-XL/Short-term debt",
	"Donuts/_overrides/Core/Primary/XS-S/Long term debt",
	"Donuts/_overrides/Core/Primary/M-XL/Long-term debt",
	"Donuts/_overrides/Core/Secondary/01 XS-S",
	"Donuts/_overrides/Core/Secondary/02 M-XL",
	"Donuts/_overrides/Core/Simple/Tiny/On Dark",
	"Donuts/_overrides/Core/Simple/Tiny/On Light",
	"Donuts/_overrides/Core/Simple/Medium",
	"Donuts/_overrides/Core/Simple/Small",
	"Donuts/_overrides/Core/Simple/Large",

	// Footer
	"Footer/_overrides/Legal line",
	"Footer/_overrides/Data Provider",
	"Footer/_overrides/Data Provider/Equifax",
	"Footer/_overrides/Data Provider/Experian",
	"Footer/_overrides/Data Provider/TransUnion",

	// Forms
	"Navigation/_Progress/XL",
	"Navigation/_Progress/L",
	"Navigation/_Progress/_XS-S",
	"Navigation/_Progress/M",

	"Form/_Dark/__Group/Simple Criteria",
	"Form/_Dark/__Group/Criteria",
	"Form/_Dark/__Group/Simple Disabled",
	"Form/_Dark/__Group/Disabled",
	"Form/_Dark/__Group/Simple",
	"Form/_Dark/__Group/_Default",
	"Form/__Light/__Group/Simple Criteria",
	"Form/__Light/__Group/Criteria",
	"Form/__Light/__Group/Simple Disabled",
	"Form/__Light/__Group/Disabled",
	"Form/__Light/__Group/Simple",
	"Form/__Light/__Group/_Default",


	// Navigation
	"Navigation/🚫 overrides/_SecondaryNav/Options/Back",
	"Navigation/🚫 overrides/_SecondaryNav/Options/Right",
	"Navigation/🚫 overrides/_SecondaryNav/Options/Center",
	"Navigation/🚫 overrides/_SecondaryNav/Options/_Left",
	"Navigation/🚫 overrides/_SecondaryNav/MenuItem/Active",
	"Navigation/🚫 overrides/_SecondaryNav/MenuItem/_Default",
	"Navigation/🚫 overrides/__PrimaryNav/Options/XS-S",
	"Navigation/🚫 overrides/__PrimaryNav/Options/M-XL",
	"Navigation/🚫 overrides/Blur Overlay",
	"Navigation/🚫 overrides/__PrimaryNav/Icon/XS-S",
	"Navigation/🚫 overrides/_MyAccountMenu/Content",

	// Notifications
	"Notifications/_overrides/_Dark/Background",
	"Notifications/_overrides/_Dark/Desktop/With close",
	"Notifications/_overrides/_Dark/Mobile/With close",
	"Notifications/_overrides/_Dark/CTA/Text-link [M-XL]",
	"Notifications/_overrides/_Dark/Icon Left/Success",
	"Notifications/_overrides/_Dark/Mobile/Text only",
	"Notifications/_overrides/_Dark/Icon Left/Information",
	"Notifications/_overrides/_Dark/Close",
	"Notifications/_overrides/_Dark/CTA/Button + Link[M-XL]",
	"Notifications/_overrides/_Dark/Icon Left/Attention",
	"Notifications/_overrides/_Dark/CTA/Button + Link [XS-S]",
	"Notifications/_overrides/_Dark/CTA/Text-link [XS-S]",
	"Notifications/_overrides/_Dark/CTA/Text-link left [XS-S]",
	"Notifications/_overrides/_Dark/Desktop/Text only",
	"Notifications/_overrides/__Light/Background",
	"Notifications/_overrides/__Light/Desktop/With close",
	"Notifications/_overrides/__Light/Mobile/With close",
	"Notifications/_overrides/__Light/CTA/Text-link [M-XL]",
	"Notifications/_overrides/__Light/Icon Left/Success",
	"Notifications/_overrides/__Light/Mobile/Text only",
	"Notifications/_overrides/__Light/Icon Left/Information",
	"Notifications/_overrides/__Light/Close",
	"Notifications/_overrides/__Light/CTA/Button + Link[M-XL]",
	"Notifications/_overrides/__Light/Icon Left/Attention",
	"Notifications/_overrides/__Light/CTA/Button + Link [XS-S]",
	"Notifications/_overrides/__Light/CTA/Text-link [XS-S]",
	"Notifications/_overrides/__Light/CTA/Text-link left [XS-S]",
	"Notifications/_overrides/__Light/Desktop/Text only",

	// Product panel
	"Product Panel/_overrides/Headers/Credit cards [XS-S]",
	"Product Panel/_overrides/Headers/Other [XS-S]",
	"Product Panel/_overrides/Titles/_overrides/Detail",
	"Product Panel/_overrides/Labels/_overrides/Pre-approved [XS-XL]",
	"Product Panel/_overrides/Cells/Feature caption",
	"Product Panel/_overrides/Cells/Feature caption with link",
	"Product Panel/_overrides/Titles/Double line title with labels and rating [XS-S]",
	"Product Panel/_overrides/Titles/Double line title and rating [XS-S]",
	"Product Panel/_overrides/Labels/Offer [XS-S]",
	"Product Panel/_overrides/Labels/Pre-approved with offer [XS-S]",
	"Product Panel/_overrides/Labels/Eligibility [XS-S]",
	"Product Panel/03 XS-S",
	"Product Panel/_overrides/Labels/Eligibility [M-XL]",
	"Product Panel/_overrides/Titles/Double line title with labels and rating [M-XL]",
	"Product Panel/_overrides/Labels/Pre-approved with offer and rating [M-XL]",
	"Product Panel/_overrides/Labels/Offer and rating [M-XL]",
	"Product Panel/_overrides/Labels/Rating [M-XL]",
	"Product Panel/02 M",
	"Product Panel/01 L-XL",
	"Product Panel/_overrides/Headers/Credit cards [M]",
	"Product Panel/_overrides/Headers/Other [M]",
	"Product Panel/_overrides/Headers/Credit cards [L-XL]",
	"Product Panel/_overrides/Headers/Other [L-XL]",
	"Product Panel/_overrides/Cells/Feature caption with icon",
	"Product Panel/_overrides/Titles/Double line title [XS-S]",
	"Product Panel/_overrides/Titles/Double line title [M-XL]",
	"Product Panel/_overrides/Labels/Pre-approved with rating [M-XL]",
	"Product Panel/06 Car Insurance XS-S",
	"Product Panel/05 Car Insurance M",
	"Product Panel/04 Car Insurance L-XL",
	"Product Panel/12 Other XS-S",
	"Product Panel/11 Other M",
	"Product Panel/10 Other L-XL",
	"Product Panel/_overrides/Titles/Single line title with labels and rating [XS-S]",
	"Product Panel/_overrides/Titles/Single line title and rating [XS-S]",
	"Product Panel/_overrides/Titles/Single line title [XS-S]",
	"Product Panel/_overrides/Titles/Single line title with labels and rating [M-XL]",
	"Product Panel/_overrides/Titles/Single line title [M-XL]",
	"Product Panel/09 Mortgages XS-S",
	"Product Panel/08 Mortgages M",
	"Product Panel/07 Mortgages L-XL",
	"Product Panel/_overrides/Cells/Feature emphasis",
	"Product Panel/_overrides/Cells/Positive emphasis",

	// Text
	"Text/Full-width title/_Dark/Without Description/04 S",
	"Text/Full-width title/_Dark/Without Description/05 XS",
	"Text/Full-width title/_Dark/With Description/04 S",
	"Text/Full-width title/_Dark/With Description/05 XS",
	"Text/List Item with icon/_Dark/01 Default",
	"Text/List Item with icon/_Dark/02 Negative",
	"Text/List Item with icon/_Dark/03 Positive",
	"Text/Puller/02 No CTA/04 XS-S",
	"Text/Puller/02 No CTA/03 M",
	"Text/Puller/02 No CTA/02 L",
	"Text/Puller/02 No CTA/01 XL",
	"Text/Puller/01 With CTA/04 XS-S",
	"Text/Puller/01 With CTA/03 M",
	"Text/Puller/01 With CTA/02 L",
	"Text/Puller/01 With CTA/01 XL",
	"Text/Full-width title/__Light/Without Description/04 S",
	"Text/Full-width title/__Light/Without Description/05 XS",
	"Text/Full-width title/__Light/With Description/04 S",
	"Text/Full-width title/__Light/With Description/05 XS",
	"Text/List Item with icon/__Light/01 Default",
	"Text/List Item with icon/__Light/02 Negative",
	"Text/List Item with icon/__Light/03 Positive",
	"Text/Information/_overrides/__Light/Title",
	"Text/Information/_overrides/_Dark/Title",
	"Text/Information/_overrides/__Light/Description",
	"Text/Information/_overrides/_Dark/Description",
	"Text/Information/_overrides/_Dark/Link",
	"Text/Information/_overrides/__Light/Link",
	"Text/SectionTitle/_overrides/Description",
	"Text/SectionTitle/_overrides/CTA",
	"Text/Value information/_overrides/__Light/Value",
	"Text/Value information/_overrides/_Dark/Value",
	"Text/Value information/_overrides/_Dark/Link",
	"Text/Value information/_overrides/__Light/Link",

	// To-do
	"To-do list/03 Pop-up",
	"To-do list/02 Task-done",
	"To-do list/01 Task/02 XS-S",
	"To-do list/01 Task/01 M-XL",

	// Widgets
	"Widgets/Payment history/_overrides/No data",
	"Widgets/Payment history/_overrides/Missed Widgets/Payment",
	"Widgets/Payment history/_overrides/On time",
	"Widgets/Payment history/_overrides/Year XS",
	"Widgets/Payment history/_overrides/Year S",
	"Widgets/Payment history/_overrides/Year M",
	"Widgets/Payment history/_overrides/Year L",
	"Widgets/Payment history/_overrides/Year XL",
	"Widgets/Payment history/XS",
	"Widgets/Payment history/S",
	"Widgets/Payment history/M",
	"Widgets/Payment history/L",
	"Widgets/Payment history/XL",
	"Widgets/Time Machine/_overrides/Provider/Experian",
	"Widgets/Time Machine/_overrides/Provider/Equifax",
	"Widgets/Time Machine/_overrides/Change/Up",
	"Widgets/Time Machine/_overrides/Provider/TransUnion",
	"Widgets/Time Machine/_overrides/Scrubber/XS-S",
	"Widgets/Time Machine/_overrides/Change/Down",
	"Widgets/Time Machine/_overrides/Scrubber/M-XL",

];
